export const kpopGroupsData = {
  groups: [
    {
      name: "BTS",
      gender: "male",
      agency: "BigHit Music",
      members: [
        {
          name: "RM",
          position: ["Leader", "Main Rapper"],
          birthYear: 1994,
          personality: ["leadership", "intelligent", "charismatic"],
        },
        {
          name: "Jin",
          position: ["Sub Vocalist", "Visual"],
          birthYear: 1992,
          personality: ["funny", "confident", "caring"],
        },
        {
          name: "SUGA",
          position: ["Lead Rapper"],
          birthYear: 1993,
          personality: ["calm", "passionate", "talented"],
        },
        {
          name: "j-hope",
          position: ["Main Dancer", "Sub Rapper", "Sub Vocalist"],
          birthYear: 1994,
          personality: ["energetic", "positive", "cheerful"],
        },
        {
          name: "Jimin",
          position: ["Main Dancer", "Lead Vocalist"],
          birthYear: 1995,
          personality: ["charming", "hardworking", "kind"],
        },
        {
          name: "V",
          position: ["Lead Dancer", "Sub Vocalist", "Visual"],
          birthYear: 1995,
          personality: ["artistic", "unique", "playful"],
        },
        {
          name: "Jungkook",
          position: [
            "Main Vocalist",
            "Lead Dancer",
            "Sub Rapper",
            "Center",
            "Maknae",
          ],
          birthYear: 1997,
          personality: ["talented", "competitive", "cute"],
        },
      ],
    },
    {
      name: "BLACKPINK",
      gender: "female",
      agency: "YG Entertainment",
      members: [
        {
          name: "Jisoo",
          position: ["Lead Vocalist", "Visual"],
          birthYear: 1995,
          personality: ["elegant", "calm", "professional"],
        },
        {
          name: "Jennie",
          position: ["Main Rapper", "Lead Vocalist"],
          birthYear: 1996,
          personality: ["charismatic", "confident", "fashionable"],
        },
        {
          name: "Rosé",
          position: ["Main Vocalist", "Lead Dancer"],
          birthYear: 1997,
          personality: ["artistic", "sweet", "talented"],
        },
        {
          name: "Lisa",
          position: ["Main Dancer", "Lead Rapper", "Sub Vocalist", "Maknae"],
          birthYear: 1997,
          personality: ["energetic", "charismatic", "cheerful"],
        },
      ],
    },
    {
      name: "IVE",
      gender: "female",
      agency: "Starship Entertainment",
      members: [
        {
          name: "Yujin",
          position: ["Leader", "Lead Vocalist"],
          birthYear: 2003,
          personality: ["leadership", "reliable", "professional"],
        },
        {
          name: "Gaeul",
          position: ["Main Rapper", "Sub Vocalist"],
          birthYear: 2002,
          personality: ["calm", "chic", "cool"],
        },
        {
          name: "Rei",
          position: ["Rapper", "Sub Vocalist"],
          birthYear: 2004,
          personality: ["cute", "talented", "charming"],
        },
        {
          name: "Wonyoung",
          position: ["Lead Dancer", "Sub Vocalist", "Visual", "Center"],
          birthYear: 2004,
          personality: ["elegant", "confident", "graceful"],
        },
        {
          name: "Liz",
          position: ["Main Vocalist"],
          birthYear: 2004,
          personality: ["sweet", "talented", "hardworking"],
        },
        {
          name: "Leeseo",
          position: ["Sub Vocalist", "Maknae"],
          birthYear: 2007,
          personality: ["cute", "energetic", "cheerful"],
        },
      ],
    },
    {
      name: "aespa",
      gender: "female",
      agency: "SM Entertainment",
      members: [
        {
          name: "Karina",
          position: [
            "Leader",
            "Main Dancer",
            "Lead Rapper",
            "Sub Vocalist",
            "Visual",
            "Center",
          ],
          birthYear: 2000,
          personality: ["leadership", "charismatic", "talented"],
        },
        {
          name: "Giselle",
          position: ["Main Rapper", "Sub Vocalist"],
          birthYear: 2000,
          personality: ["confident", "unique", "cool"],
        },
        {
          name: "Winter",
          position: ["Lead Vocalist", "Lead Dancer", "Visual"],
          birthYear: 2001,
          personality: ["talented", "charming", "professional"],
        },
        {
          name: "Ningning",
          position: ["Main Vocalist", "Maknae"],
          birthYear: 2002,
          personality: ["cute", "talented", "energetic"],
        },
      ],
    },
    {
      name: "(G)I-DLE",
      gender: "female",
      agency: "CUBE Entertainment",
      members: [
        {
          name: "Soyeon",
          position: ["Leader", "Main Rapper", "Center", "Sub Vocalist"],
          birthYear: 1998,
          personality: ["Leadership", "Creative (Producer)", "Charismatic"],
        },
        {
          name: "Minnie",
          position: ["Main Vocalist"],
          birthYear: 1997,
          personality: ["Emotional", "Calm", "Warm-hearted"],
        },
        {
          name: "Yuqi",
          position: ["Lead Dancer", "Sub Vocalist", "Sub Rapper"],
          birthYear: 1999,
          personality: ["Cheerful", "Energetic", "Friendly"],
        },
        {
          name: "Shuhua",
          position: ["Sub Vocalist", "Visual", "Maknae"],
          birthYear: 2000,
          personality: ["Honest", "Confident", "Playful"],
        },
        {
          name: "Miyeon",
          position: ["Main Vocalist", "Visual"],
          birthYear: 1997,
          personality: ["Elegant", "Composed", "Considerate"],
        },
      ],
    },
    {
      name: "KIIRAS",
      gender: "female",
      agency: "LeanBranding",
      members: [
        {
          name: "Lingling",
          position: ["Leader", "Main Rapper", "Sub Vocalist"], birthYear: 2006, personality: ["Multilingual", "Leader", "Trailblazer"],
        },
        { name: "Kurumi", position: ["Main Vocalist"], birthYear: 2007, personality: ["SweetVoice", "Calm", "Reliable"] },
        { name: "Harin", position: ["Center"], birthYear: 2008, personality: ["Studious", "Precise", "Charming"] },
        { name: "Kylie", position: ["Main Rapper"], birthYear: 2009, personality: ["PowerfulRap", "Energetic", "Confident"] },
        { name: "Doyeon", position: ["Sub Vocalist"], birthYear: 2010, personality: ["RisingStar", "Youthful", "AllRounder"] },
        { name: "Roah", position: ["Main Vocalist", "Maknae"], birthYear: 2012, personality: ["Youngest", "VocalTalent", "Bright"] },
      ],
    },
    {
      name: "KickFlip",
      gender: "male",
      agency: "JYP Entertainment",
      members: [
        { name: "Kyehoon", position: ["Leader", "Ace"], birthYear: 2004, personality: ["Leader", "Ace", "StrongStagePresence"] },
        { name: "Amaru", position: ["Vocal", "Rap"], birthYear: 2005, personality: ["Versatile", "SmoothVoice", "Charismatic"] },
        { name: "Donghwa", position: ["Dance"], birthYear: 2006, personality: ["DanceMaster", "Energetic", "SilentPower"] },
        { name: "Juwang", position: ["Vocal"], birthYear: 2005, personality: ["PowerVocals", "Steady", "Warm"] },
        { name: "Minje", position: ["Visual", "Rap"], birthYear: 2006, personality: ["Visual", "RapSkill", "BrightSmile"] },
        { name: "Keiju", position: ["Dance"], birthYear: 2007, personality: ["DanceLine", "Flexible", "Energetic"] },
        { name: "Donghyeon", position: ["Maknae", "Vocal"], birthYear: 2008, personality: ["Youngest", "RisingVocal", "Fresh"] },
      ],
    },
    {
      name: "Hearts2Hearts",
      gender: "female",
      agency: "SM Entertainment",
      members: [
        { name: "Jiwoo", position: ["Leader", "Main Dancer", "Visual"], birthYear: 2006, personality: ["Elegant", "StrongDancer", "Leader"] },
        { name: "Carmen", position: ["Main Vocalist"], birthYear: 2006, personality: ["PowerVocals", "Soulful", "Confident"] },
        { name: "Yuha", position: ["Lead Vocalist", "Lead Dancer"], birthYear: 2007, personality: ["DualTalents", "Energetic", "Passionate"] },
        { name: "Stella", position: ["Lead Vocalist"], birthYear: 2007, personality: ["BrightVoice", "Friendly", "Charismatic"] },
        {
          name: "Juun",
          position: ["Main Dancer", "Main Rapper", "Sub Vocalist"], birthYear: 2005, personality: ["DanceRapHybrid", "Dynamic", "Cool"],
        },
        { name: "A-na", position: ["Lead Vocalist", "Visual"], birthYear: 2008, personality: ["Visual", "GentleVoice", "AllRounder"] },
        {
          name: "Ian",
          position: ["Center", "Visual", "Lead Dancer", "Sub Vocalist"], birthYear: 2009, personality: ["Center", "Visual", "MultiTalented"],
        },
        { name: "Ye-on", position: ["Lead Vocalist", "Maknae"], birthYear: 2010, personality: ["Youngest", "BrightFuture", "Charming"] },
      ],
    },
    {
      name: "ifeye",
      gender: "female",
      agency: "Hi-Hat Entertainment",
      members: [
        { name: "Kasia", position: ["Leader", "Rapper"], birthYear: 2004, personality: ["Leader", "RapMaster", "Bold"] },
        { name: "Won Hwayeon", position: ["Vocalist", "Center"], birthYear: 2005, personality: ["MainVocal", "Calm", "Graceful"] },
        { name: "Taerin", position: ["Main Dancer"], birthYear: 2006, personality: ["DanceLeader", "Energetic", "Bright"] },
        { name: "Rahee", position: ["All-Rounder"], birthYear: 2007, personality: ["AllRounder", "Adaptable", "Friendly"] },
        { name: "Meu", position: ["Lead Vocalist", "Dancer"], birthYear: 2008, personality: ["LeadVocal", "DanceSkill", "Charismatic"] },
        { name: "Sasha", position: ["Main Vocalist", "Maknae"], birthYear: 2009, personality: ["Youngest", "StrongVoice", "BrightEnergy"] },
      ],
    },
    {
      name: "Stray Kids",
      gender: "male",
      agency: "JYP Entertainment",
      members: [
        {
          name: "Bang Chan",
          position: [
            "Leader",
            "Producer",
            "Lead Vocalist",
            "Lead Dancer",
            "Rapper",
          ],
          birthYear: 1997,
          personality: ["leadership", "professional", "talented"],
        },
        {
          name: "Lee Know",
          position: ["Main Dancer", "Vocalist", "Sub Rapper"],
          birthYear: 1998,
          personality: ["calm", "chic", "charismatic"],
        },
        {
          name: "Changbin",
          position: ["Main Rapper", "Producer", "Vocalist"],
          birthYear: 1999,
          personality: ["passionate", "intense", "confident"],
        },
        {
          name: "Hyunjin",
          position: ["Main Dancer", "Lead Rapper", "Sub Vocalist", "Visual"],
          birthYear: 2000,
          personality: ["artistic", "emotional", "graceful"],
        },
        {
          name: "Han",
          position: ["Main Rapper", "Lead Vocalist", "Producer"],
          birthYear: 2000,
          personality: ["talented", "positive", "energetic"],
        },
        {
          name: "Felix",
          position: ["Lead Dancer", "Lead Rapper", "Sub Vocalist"],
          birthYear: 2000,
          personality: ["bright", "friendly", "charismatic"],
        },
        {
          name: "Seungmin",
          position: ["Main Vocalist"],
          birthYear: 2000,
          personality: ["calm", "delicate", "professional"],
        },
        {
          name: "I.N",
          position: ["Vocalist", "Maknae"],
          birthYear: 2001,
          personality: ["cute", "energetic", "talented"],
        },
      ],
    },
    {
      name: "ATEEZ",
      gender: "male",
      agency: "KQ Entertainment",
      members: [
        { name: "Hongjoong", position: ["Leader", "Rapper", "Composer"], birthYear: 1998, personality: ["Visionary", "Leader", "Creative"] },
        { name: "Seonghwa", position: ["Vocalist", "Visual"], birthYear: 1998, personality: ["Gentle", "VisualImpact", "Reliable"] },
        { name: "Yunho", position: ["Main Dancer", "Vocalist"], birthYear: 1999, personality: ["Energetic", "TallPresence", "Friendly"] },
        { name: "Yeosang", position: ["Lead Dancer", "Vocalist", "Visual"], birthYear: 1999, personality: ["Stylish", "Calm", "Cool"] },
        { name: "San", position: ["Lead Vocalist", "Main Dancer"], birthYear: 1999, personality: ["Expressive", "DynamicPerformer", "Warm"] },
        { name: "Mingi", position: ["Main Rapper", "Performer"], birthYear: 1999, personality: ["PowerfulRap", "Intensity", "Introspective"] },
        {
          name: "Wooyoung",
          position: ["Main Dancer", "Vocalist", "Performer"], birthYear: 1999, personality: ["AllRounder", "Charismatic", "Fun"],
        },
        { name: "Jongho", position: ["Main Vocalist", "Maknae"], birthYear: 2000, personality: ["Youngest", "StrongVoice", "BrightFuture"] },
      ],
    },
    {
      name: "LOONA",
      gender: "female",
      agency: "BlockBerry Creative",
      members: [
        { name: "HeeJin", position: ["Dancer", "Vocalist", "Visual"], birthYear: 2000, personality: ["InnocentCharm", "Bright", "Energetic"] },
        { name: "HyunJin", position: ["Dancer", "Vocalist"], birthYear: 2000, personality: ["Joker", "Playful", "Versatile"] },
        { name: "HaSeul", position: ["Leader", "Vocalist"], birthYear: 1997, personality: ["MomFigure", "Elegant", "Strong"] },
        { name: "YeoJin", position: ["Vocalist", "Maknae"], birthYear: 2002, personality: ["Youngest", "Lively", "Sweet"] },
        { name: "ViVi", position: ["Vocalist"], birthYear: 1996, personality: ["SoftVoice", "Calm", "Mature"] },
        { name: "Kim Lip", position: ["Main Vocalist", "Dancer"], birthYear: 1999, personality: ["PowerVocals", "Charm", "AllRounder"] },
        { name: "JinSoul", position: ["Main Rapper", "Vocalist"], birthYear: 1997, personality: ["CoolRap", "Stylish", "Independent"] },
        { name: "Choerry", position: ["Rapper", "Dancer", "Vocalist"], birthYear: 2001, personality: ["BrightEnergy", "Versatile", "Charismatic"] },
        { name: "Yves", position: ["Vocalist", "Dancer"], birthYear: 1997, personality: ["Graceful", "LeaderMode", "Sincere"] },
        { name: "Chuu", position: ["Main Vocalist", "Face of the Group"], birthYear: 1999, personality: ["Cheerful", "Aegyo", "Friendly"] },
        { name: "Go Won", position: ["Rapper", "Dancer", "Vocalist"], birthYear: 2000, personality: ["Unique", "Stylish", "Bright"] },
        { name: "Olivia Hye", position: ["Lead Rapper", "Dancer", "Vocalist"], birthYear: 2001, personality: ["Cool", "Fierce", "Confident"] },
      ],
    },
    {
      name: "THE BOYZ",
      gender: "male",
      agency: "IST Entertainment",
      members: [
        { name: "Sangyeon", position: ["Leader", "Main Vocalist"], birthYear: 1995, personality: ["Leader", "StrongVoice", "Charismatic"] },
        { name: "Jacob", position: ["Lead Vocalist"], birthYear: 1997, personality: ["Soulful", "Warm", "Reliable"] },
        { name: "Younghoon", position: ["Vocalist", "Visual"], birthYear: 1998, personality: ["Visual", "Gentle", "AllRounder"] },
        {
          name: "Hyunjae",
          position: ["Lead Vocalist", "Lead Dancer", "Visual"], birthYear: 1999, personality: ["DanceVocal", "Bright", "Stylish"],
        },
        { name: "Juyeon", position: ["Main Dancer", "Vocalist", "Visual"], birthYear: 1999, personality: ["Performance", "Energetic", "Confident"] },
        { name: "Kevin", position: ["Main Vocalist"], birthYear: 2000, personality: ["PowerVocals", "Charming", "Gentle"] },
        { name: "New", position: ["Main Vocalist"], birthYear: 2000, personality: ["BrightVoice", "Youthful", "Friendly"] },
        { name: "Q", position: ["Main Dancer", "Vocalist"], birthYear: 2001, personality: ["DanceLeader", "Rhythmic", "Warm"] },
        { name: "Juhaknyeon", position: ["Lead Dancer", "Rapper", "Vocalist"], birthYear: 2001, personality: ["Versatile", "StrongRap", "Dynamic"] },
        { name: "Sunwoo", position: ["Main Rapper"], birthYear: 2001, personality: ["RapMaster", "Confident", "Cool"] },
        { name: "Eric", position: ["Lead Dancer", "Lead Rapper", "Maknae"], birthYear: 2003, personality: ["Youngest", "Energetic", "BrightFuture"] },
        { name: "Hwall", position: ["Lead Dancer", "Vocalist", "Rapper"], birthYear: 2003, personality: ["DanceRap", "StrongPresence", "Passionate"] },
      ],
    },
    {
      name: "Golden Child",
      gender: "male",
      agency: "Woollim Entertainment",
      members: [
        { name: "Dae-yeol", position: ["Leader", "Lead Dancer", "Vocalist"], birthYear: 1996, personality: ["Leader", "Steady", "Protective"] },
        { name: "Y", position: ["Main Vocalist", "Lead Dancer"], birthYear: 1996, personality: ["PowerVocals", "DanceSkill", "AllRounder"] },
        { name: "Jangjun", position: ["Main Rapper", "Lead Dancer"], birthYear: 1997, personality: ["RapSkill", "DanceCharm", "Friendly"] },
        { name: "TAG", position: ["Main Rapper", "Vocalist"], birthYear: 1998, personality: ["SharpRap", "Dynamic", "Cool"] },
        { name: "Seungmin", position: ["Lead Vocalist"], birthYear: 1999, personality: ["ClearVoice", "Bright", "Youthful"] },
        { name: "Jaehyun", position: ["Sub Vocalist"], birthYear: 1999, personality: ["WarmVoice", "Gentle", "Reliable"] },
        { name: "Donghyun", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 2000, personality: ["DanceLine", "SweetVoice", "Friendly"] },
        { name: "Joochan", position: ["Main Vocalist"], birthYear: 2000, personality: ["StrongVoice", "Passionate", "Bright"] },
        { name: "Jibeom", position: ["Lead Vocalist"], birthYear: 2001, personality: ["RisingVocal", "Gentle", "Stylish"] },
        {
          name: "Bomin",
          position: ["Lead Dancer", "Sub Vocalist", "Maknae", "Visual"], birthYear: 2001, personality: ["Youngest", "Visual", "Energetic"],
        },
      ],
    },
    {
      name: "Weki Meki",
      gender: "female",
      agency: "Fantagio",
      members: [
        { name: "Suyeon", position: ["Leader", "Main Vocalist"], birthYear: 1998, personality: ["Leader", "StrongVocals", "Confident"] },
        { name: "Elly", position: ["Main Vocalist"], birthYear: 1999, personality: ["PowerVoices", "Bright", "Cheerful"] },
        {
          name: "Yoojung",
          position: ["Main Rapper", "Main Dancer", "Lead Vocalist"], birthYear: 2000, personality: ["DanceRapHybrid", "Energetic", "Versatile"],
        },
        {
          name: "Doyeon",
          position: ["Lead Vocalist", "Lead Dancer", "Visual", "Center"], birthYear: 2001, personality: ["Center", "Visual", "Performance"],
        },
        { name: "Sei", position: ["Lead Vocalist"], birthYear: 2002, personality: ["BrightVoice", "Youthful", "Friendly"] },
        { name: "Lua", position: ["Main Dancer", "Sub Vocalist", "Rapper"], birthYear: 2002, personality: ["DanceLine", "RapSkill", "Fresh"] },
        { name: "Rina", position: ["Lead Rapper", "Sub Vocalist", "Visual"], birthYear: 2003, personality: ["VisualRapper", "Confident", "Stylish"] },
        { name: "Lucy", position: ["Lead Rapper", "Lead Dancer", "Maknae"], birthYear: 2005, personality: ["Youngest", "Dynamic", "BrightFuture"] },
      ],
    },
    {
      name: "ONF",
      gender: "male",
      agency: "WM Entertainment",
      members: [
        { name: "Hyojin", position: ["Leader (ON Team)", "Main Vocalist"], birthYear: 1994, personality: ["Leader", "Stable", "WarmVoice"] },
        { name: "E-Tion", position: ["Lead Vocalist"], birthYear: 1996, personality: ["Reliable", "Bright", "SmoothVoice"] },
        {
          name: "J-Us",
          position: ["Leader (OFF Team)", "Main Dancer", "Lead Vocalist"], birthYear: 1995, personality: ["Energetic", "DanceLeader", "Friendly"],
        },
        { name: "Wyatt", position: ["Main Rapper", "Lead Dancer"], birthYear: 1995, personality: ["DeepVoice", "Charismatic", "Cool"] },
        { name: "MK", position: ["Main Vocalist"], birthYear: 1995, personality: ["UniqueTone", "Cheerful", "Creative"] },
        { name: "U", position: ["Main Dancer", "Vocalist", "Maknae"], birthYear: 1999, personality: ["Youngest", "DanceKing", "Positive"] },
        { name: "Laun", position: ["Lead Dancer", "Vocalist"], birthYear: 1995, personality: ["AllRounder", "Charming", "Gentle"] },
      ],
    },
    {
      name: "Dreamcatcher",
      gender: "female",
      agency: "Dreamcatcher Company",
      members: [
        {
          name: "JiU",
          position: ["Leader", "Lead Dancer", "Vocalist", "Visual"], birthYear: 1994, personality: ["Leader", "Elegant", "Reliable"],
        },
        { name: "SuA", position: ["Main Dancer", "Lead Rapper", "Vocalist"], birthYear: 1994, personality: ["PerformanceQueen", "Energetic", "Fun"] },
        { name: "Siyeon", position: ["Main Vocalist"], birthYear: 1995, personality: ["PowerVocal", "Emotional", "Strong"] },
        { name: "Handong", position: ["Vocalist"], birthYear: 1996, personality: ["SoftVoice", "Gentle", "Elegant"] },
        { name: "Yoohyeon", position: ["Lead Vocalist"], birthYear: 1997, personality: ["Bright", "Sweet", "Playful"] },
        { name: "Dami", position: ["Main Rapper", "Lead Dancer"], birthYear: 1997, personality: ["CoolRapper", "Calm", "Independent"] },
        {
          name: "Gahyeon",
          position: ["Lead Rapper", "Sub Vocalist", "Maknae"], birthYear: 1999, personality: ["Youngest", "Confident", "Cute"],
        },
      ],
    },
    {
      name: "fromis_9",
      gender: "female",
      agency: "Off The Record Entertainment",
      members: [
        {
          name: "Saerom",
          position: ["Leader", "Lead Dancer", "Vocalist", "Visual"], birthYear: 1997, personality: ["Leader", "Graceful", "Reliable"],
        },
        { name: "Hayoung", position: ["Lead Vocalist", "Lead Dancer"], birthYear: 1997, personality: ["Kind", "Warm", "Positive"] },
        { name: "Gyuri", position: ["Lead Vocalist", "Visual"], birthYear: 1997, personality: ["Gentle", "Charming", "Calm"] },
        { name: "Jiwon", position: ["Main Vocalist"], birthYear: 1998, personality: ["PowerVoice", "Bright", "Energetic"] },
        { name: "Jisun", position: ["Lead Vocalist", "Lead Dancer", "Center"], birthYear: 1998, personality: ["Center", "Lively", "Charming"] },
        {
          name: "Seoyeon",
          position: ["Main Rapper", "Vocalist", "Main Dancer"], birthYear: 2000, personality: ["Performance", "Charisma", "Creative"],
        },
        {
          name: "Chaeyoung",
          position: ["Main Rapper", "Main Dancer", "Vocalist"], birthYear: 1999, personality: ["talented", "bright", "reliable"],
        },
        {
          name: "Nagyung",
          position: ["Lead Rapper", "Sub Vocalist", "Visual"], birthYear: 2000, personality: ["Elegant", "Visual", "Chic"],
        },
        { name: "Jiheon", position: ["Lead Vocalist", "Maknae"], birthYear: 2003, personality: ["Youngest", "Cute", "Bright"] },
      ],
    },
    {
      name: "NATURE",
      gender: "female",
      agency: "n.CH Entertainment",
      members: [
        { name: "Lu", position: ["Leader", "Main Vocalist"], birthYear: 1997, personality: ["Leader", "StrongVocal", "Warm"] },
        { name: "Saebom", position: ["Lead Rapper", "Vocalist"], birthYear: 1999, personality: ["Energetic", "Versatile", "Charming"] },
        { name: "Aurora", position: ["Main Dancer", "Vocalist"], birthYear: 1997, personality: ["Performance", "Bright", "Fun"] },
        { name: "Chaebin", position: ["Main Vocalist"], birthYear: 1999, personality: ["SoftVoice", "Positive", "Friendly"] },
        { name: "Haru", position: ["Main Dancer", "Vocalist"], birthYear: 2000, personality: ["DanceLine", "Bright", "Cute"] },
        { name: "Loha", position: ["Main Vocalist"], birthYear: 2001, personality: ["Pure", "Emotional", "Calm"] },
        { name: "Uchae", position: ["Lead Dancer", "Vocalist", "Visual"], birthYear: 2002, personality: ["Visual", "Gentle", "Warm"] },
        { name: "Sunshine", position: ["Lead Vocalist"], birthYear: 2002, personality: ["Bright", "Cheerful", "Optimistic"] },
        { name: "Sohee", position: ["Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "Playful", "Sweet"] },
      ],
    },
    {
      name: "D-CRUNCH",
      gender: "male",
      agency: "All-S Company",
      members: [
        { name: "O.V", position: ["Leader", "Main Rapper"], birthYear: 1995, personality: ["Leader", "Cool", "Powerful"] },
        { name: "Hyunwook", position: ["Main Vocalist"], birthYear: 1996, personality: ["StrongVoice", "Reliable", "Calm"] },
        { name: "Hyunho", position: ["Lead Vocalist"], birthYear: 1998, personality: ["WarmTone", "Gentle", "Bright"] },
        { name: "Hyunoh", position: ["Vocalist"], birthYear: 1999, personality: ["Cheerful", "Soft", "Friendly"] },
        { name: "Hyunwoo", position: ["Sub Vocalist"], birthYear: 1999, personality: ["Bright", "Supportive", "TeamPlayer"] },
        { name: "Minhyuk", position: ["Sub Rapper"], birthYear: 2000, personality: ["YoungEnergy", "Versatile", "Energetic"] },
        { name: "Chanyoung", position: ["Main Dancer", "Lead Rapper"], birthYear: 2000, personality: ["DanceLeader", "RapLine", "Charismatic"] },
        { name: "Jungseung", position: ["Lead Vocalist"], birthYear: 2001, personality: ["Gentle", "Bright", "Emotional"] },
        { name: "Dylan", position: ["Rapper", "Maknae"], birthYear: 2002, personality: ["Youngest", "Fun", "Stylish"] },
      ],
    },
    {
      name: "DreamNote",
      gender: "female",
      agency: "iMe Korea",
      members: [
        { name: "Sumin", position: ["Leader", "Lead Vocalist"], birthYear: 2001, personality: ["Leader", "Calm", "Kind"] },
        { name: "Eunjo", position: ["Lead Dancer", "Vocalist"], birthYear: 2002, personality: ["DanceLine", "Cheerful", "Sweet"] },
        { name: "Lara", position: ["Main Vocalist"], birthYear: 2000, personality: ["StrongVocal", "Bright", "Positive"] },
        { name: "Miso", position: ["Main Dancer", "Lead Rapper"], birthYear: 1999, personality: ["Performance", "Fun", "Energetic"] },
        { name: "Youi", position: ["Lead Vocalist", "Visual"], birthYear: 2004, personality: ["Visual", "Bright", "Friendly"] },
        { name: "Boni", position: ["Lead Vocalist"], birthYear: 2001, personality: ["Cheerful", "Gentle", "AllRounder"] },
        { name: "Habin", position: ["Main Dancer", "Rapper"], birthYear: 2002, personality: ["DanceLine", "Cool", "Active"] },
        { name: "Hanbyeol", position: ["Vocalist", "Maknae"], birthYear: 2004, personality: ["Youngest", "Playful", "Bright"] },
      ],
    },
    {
      name: "IZ*ONE",
      gender: "female",
      agency: "Off The Record Entertainment",
      members: [
        { name: "Eunbi", position: ["Leader", "Lead Vocalist", "Lead Dancer"], birthYear: 1995, personality: ["Leader", "Reliable", "Graceful"] },
        { name: "Sakura", position: ["Sub Vocalist", "Visual"], birthYear: 1998, personality: ["Elegant", "Charming", "Calm"] },
        { name: "Hyewon", position: ["Lead Rapper", "Sub Vocalist"], birthYear: 1999, personality: ["Cool", "Stylish", "Quiet"] },
        { name: "Yuri", position: ["Main Vocalist"], birthYear: 2001, personality: ["StrongVocal", "Bright", "Sincere"] },
        { name: "Yena", position: ["Main Rapper", "Lead Dancer", "Vocalist"], birthYear: 1999, personality: ["Energetic", "Fun", "Versatile"] },
        {
          name: "Chaeyeon",
          position: ["Main Dancer", "Lead Vocalist", "Lead Rapper"], birthYear: 2000, personality: ["DanceQueen", "Warm", "Focused"],
        },
        { name: "Minju", position: ["Lead Rapper", "Sub Vocalist", "Visual"], birthYear: 2001, personality: ["Bright", "Playful", "Charming"] },
        { name: "Nako", position: ["Sub Vocalist"], birthYear: 2001, personality: ["Cute", "Positive", "Gentle"] },
        { name: "Hitomi", position: ["Sub Vocalist", "Lead Dancer"], birthYear: 2001, personality: ["Cheerful", "Hardworking", "Sweet"] },
        { name: "Yujin", position: ["Lead Vocalist", "Lead Dancer", "Center"], birthYear: 2003, personality: ["LeaderPotential", "Energetic", "Bright"] },
        {
          name: "Wonyoung",
          position: ["Lead Dancer", "Sub Vocalist", "Visual", "Maknae"], birthYear: 2004, personality: ["Youngest", "Visual", "Elegant"],
        },
        { name: "Chaewon", position: ["Lead Vocalist"], birthYear: 2000, personality: ["Gentle", "BrightVoice", "Warm"] },
      ],
    },
    {
      name: "PRISTIN",
      gender: "female",
      agency: "Pledis Entertainment",
      members: [
        { name: "Nayoung", position: ["Leader", "Main Rapper", "Lead Dancer"], birthYear: 1995, personality: ["Leader", "Confident", "Stylish"] },
        { name: "Roa", position: ["Lead Vocalist"], birthYear: 1997, personality: ["Gentle", "Elegant", "Charming"] },
        { name: "Yuha", position: ["Lead Vocalist"], birthYear: 1997, personality: ["SoftVoice", "Sweet", "Positive"] },
        { name: "Eunwoo", position: ["Lead Vocalist"], birthYear: 1998, personality: ["Bright", "Cheerful", "Kind"] },
        { name: "Rena", position: ["Main Rapper", "Lead Vocalist"], birthYear: 1998, personality: ["RapQueen", "Dynamic", "Cool"] },
        {
          name: "Kyulkyung",
          position: ["Main Dancer", "Sub Vocalist", "Visual"], birthYear: 1999, personality: ["Visual", "Graceful", "Charismatic"],
        },
        { name: "Yehana", position: ["Main Vocalist"], birthYear: 1999, personality: ["PowerVocal", "Calm", "Kind"] },
        { name: "Sungyeon", position: ["Main Vocalist", "Main Producer"], birthYear: 1999, personality: ["Producer", "Creative", "Strong"] },
        { name: "Xiyeon", position: ["Lead Rapper", "Lead Vocalist"], birthYear: 2000, personality: ["Versatile", "Bright", "Friendly"] },
        { name: "Kyla", position: ["Lead Rapper", "Sub Vocalist", "Maknae"], birthYear: 2001, personality: ["Youngest", "Cute", "Charming"] },
      ],
    },
    {
      name: "ELRIS",
      gender: "female",
      agency: "Hunus Entertainment",
      members: [
        { name: "Bella", position: ["Leader", "Main Rapper", "Sub Vocalist"], birthYear: 1999, personality: ["Leader", "Creative", "Strong"] },
        { name: "Hyeseong", position: ["Lead Vocalist", "Main Dancer"], birthYear: 2000, personality: ["Bright", "Energetic", "Friendly"] },
        { name: "Yukyung", position: ["Main Dancer", "Sub Vocalist"], birthYear: 1999, personality: ["Charming", "DanceLine", "Positive"] },
        { name: "Sohee", position: ["Main Vocalist", "Face of the Group"], birthYear: 1999, personality: ["Visual", "Kind", "SoftVoice"] },
        { name: "Karin", position: ["Sub Vocalist", "Maknae"], birthYear: 2002, personality: ["Youngest", "Cute", "Cheerful"] },
      ],
    },
    {
      name: "IN2IT",
      gender: "male",
      agency: "MMO Entertainment",
      members: [
        { name: "Jiahn", position: ["Leader", "Main Vocalist"], birthYear: 1991, personality: ["Leader", "Reliable", "Calm"] },
        { name: "Yeontae", position: ["Main Vocalist"], birthYear: 1992, personality: ["StrongVoice", "Sincere", "Warm"] },
        { name: "Inpyo", position: ["Lead Dancer", "Vocalist"], birthYear: 1994, personality: ["DanceLine", "Gentle", "Friendly"] },
        { name: "Isaac", position: ["Vocalist"], birthYear: 1994, personality: ["GlobalMember", "Positive", "Bright"] },
        { name: "Inho", position: ["Lead Vocalist"], birthYear: 1995, personality: ["SmoothVoice", "Calm", "Reliable"] },
        { name: "Hyunuk", position: ["Main Dancer", "Rapper"], birthYear: 1996, personality: ["DanceLeader", "Charismatic", "Confident"] },
        { name: "Jinsub", position: ["Main Vocalist"], birthYear: 1995, personality: ["StrongTone", "Kind", "Dedicated"] },
        { name: "Sunghyun", position: ["Main Dancer", "Maknae"], birthYear: 1996, personality: ["Youngest", "Bright", "Energetic"] },
      ],
    },
    {
      name: "The Rose",
      gender: "male",
      agency: "J&Star Company",
      members: [
        {
          name: "Woosung",
          position: ["Leader", "Main Vocalist", "Electric Guitar"], birthYear: 1993, personality: ["Leader", "Soulful", "Creative"],
        },
        {
          name: "Dojoon",
          position: ["Keyboard", "Acoustic Guitar", "Main Vocalist"], birthYear: 1993, personality: ["WarmVoice", "Gentle", "Passionate"],
        },
        { name: "Hajoon", position: ["Drummer", "Sub Vocalist", "Rapper"], birthYear: 1994, personality: ["Energetic", "Cool", "Reliable"] },
        {
          name: "Jaehyeong",
          position: ["Bassist", "Sub Vocalist", "Visual", "Maknae"], birthYear: 1994, personality: ["Youngest", "Stylish", "Charming"],
        },
      ],
    },
    {
      name: "ITZY",
      gender: "female",
      agency: "JYP Entertainment",
      members: [
        {
          name: "Yeji",
          position: ["Leader", "Main Dancer", "Lead Vocalist", "Sub Rapper"], birthYear: 2000, personality: ["Leader", "Charismatic", "Powerful"],
        },
        { name: "Lia", position: ["Main Vocalist"], birthYear: 2000, personality: ["SoftVoice", "Elegant", "Warm"] },
        {
          name: "Ryujin",
          position: ["Main Rapper", "Lead Dancer", "Center", "Sub Vocalist"], birthYear: 2001, personality: ["Cool", "Confident", "Stylish"],
        },
        {
          name: "Chaeryeong",
          position: ["Main Dancer", "Sub Vocalist", "Sub Rapper"], birthYear: 2001, personality: ["DanceQueen", "Bright", "Kind"],
        },
        {
          name: "Yuna",
          position: ["Lead Rapper", "Lead Dancer", "Visual", "Maknae"], birthYear: 2003, personality: ["Youngest", "Energetic", "Charming"],
        },
      ],
    },
    {
      name: "TXT (Tomorrow X Together)",
      gender: "male",
      agency: "BigHit Music",
      members: [
        { name: "Soobin", position: ["Leader", "Vocalist", "Rapper"], birthYear: 2000, personality: ["Leader", "Gentle", "Reliable"] },
        { name: "Yeonjun", position: ["Rapper", "Dancer", "Vocalist"], birthYear: 1999, personality: ["PerformanceKing", "Charismatic", "Confident"] },
        {
          name: "Beomgyu",
          position: ["Vocalist", "Dancer", "Rapper", "Center", "Visual"], birthYear: 2001, personality: ["Stylish", "Playful", "Expressive"],
        },
        { name: "Taehyun", position: ["Main Vocalist", "Dancer"], birthYear: 2002, personality: ["StrongVocal", "Smart", "Focused"] },
        {
          name: "Huening Kai",
          position: ["Lead Vocalist", "Dancer", "Maknae"], birthYear: 2002, personality: ["Youngest", "Bright", "Lovable"],
        },
      ],
    },
    {
      name: "TREASURE",
      gender: "male",
      agency: "YG Entertainment",
      members: [
        {
          name: "Choi Hyunsuk",
          position: ["Leader", "Main Rapper", "Main Dancer"], birthYear: 1999, personality: ["Leader", "Powerful", "Charismatic"],
        },
        {
          name: "Jihoon",
          position: ["Leader", "Lead Vocalist", "Lead Dancer"], birthYear: 2000, personality: ["Bright", "Reliable", "Friendly"],
        },
        { name: "Yoshi", position: ["Lead Rapper", "Vocalist"], birthYear: 2000, personality: ["Cool", "Artistic", "Calm"] },
        { name: "Junkyu", position: ["Lead Vocalist", "Visual"], birthYear: 2000, personality: ["Visual", "Charming", "Warm"] },
        {
          name: "Mashiho",
          position: ["Lead Dancer", "Lead Vocalist", "Visual"], birthYear: 2001, personality: ["Bright", "Energetic", "Cute"],
        },
        { name: "Yoon Jae-hyuk", position: ["Sub Vocalist"], birthYear: 2001, personality: ["SoftVoice", "Gentle", "Friendly"] },
        { name: "Asahi", position: ["Lead Vocalist", "Visual"], birthYear: 2001, personality: ["Artistic", "Calm", "Creative"] },
        { name: "Bang Yedam", position: ["Main Vocalist"], birthYear: 2002, personality: ["PowerVoice", "Passionate", "Emotional"] },
        { name: "Doyoung", position: ["Main Dancer", "Vocalist"], birthYear: 2003, personality: ["DanceLine", "Fun", "Kind"] },
        { name: "Haruto", position: ["Main Rapper", "Visual"], birthYear: 2004, personality: ["Young", "Cool", "Stylish"] },
        { name: "Park Jeongwoo", position: ["Main Vocalist"], birthYear: 2004, personality: ["StrongVocal", "Gentle", "Warm"] },
        {
          name: "So Junghwan",
          position: ["Lead Dancer", "Sub Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "Bright", "Cheerful"],
        },
      ],
    },
    {
      name: "CRAVITY",
      gender: "male",
      agency: "Starship Entertainment",
      members: [
        { name: "Serim", position: ["Leader", "Main Rapper", "Visual"], birthYear: 1999, personality: ["Leader", "Calm", "Chic"] },
        { name: "Allen", position: ["Main Dancer", "Lead Rapper"], birthYear: 1999, personality: ["Performance", "Gentle", "Global"] },
        { name: "Jungmo", position: ["Lead Vocalist", "Visual"], birthYear: 2000, personality: ["Visual", "SweetVoice", "Kind"] },
        { name: "Woobin", position: ["Main Vocalist"], birthYear: 2000, personality: ["StrongVocal", "Reliable", "Bright"] },
        { name: "Wonjin", position: ["Lead Vocalist", "Lead Dancer"], birthYear: 2001, personality: ["Energetic", "Friendly", "Positive"] },
        { name: "Minhee", position: ["Lead Vocalist", "Visual"], birthYear: 2002, personality: ["Visual", "Gentle", "SoftSpoken"] },
        { name: "Hyeongjun", position: ["Main Dancer", "Vocalist"], birthYear: 2002, personality: ["Performance", "Bright", "Fun"] },
        { name: "Taeyoung", position: ["Lead Dancer", "Vocalist"], birthYear: 2003, personality: ["DanceLine", "Charming", "Warm"] },
        { name: "Seongmin", position: ["Lead Vocalist", "Maknae"], birthYear: 2003, personality: ["Youngest", "Bright", "Friendly"] },
      ],
    },
    {
      name: "MCND",
      gender: "male",
      agency: "TOP Media",
      members: [
        { name: "Castle J", position: ["Leader", "Main Rapper"], birthYear: 1999, personality: ["Leader", "Powerful", "Confident"] },
        { name: "BIC", position: ["Main Dancer", "Lead Rapper"], birthYear: 2001, personality: ["DanceLine", "Strong", "Cool"] },
        { name: "Minjae", position: ["Main Vocalist"], birthYear: 2003, personality: ["Bright", "Passionate", "Friendly"] },
        { name: "Huijun", position: ["Main Vocalist"], birthYear: 2003, personality: ["Warm", "Charming", "Cheerful"] },
        { name: "Win", position: ["Lead Rapper", "Maknae"], birthYear: 2004, personality: ["Youngest", "Energetic", "Stylish"] },
      ],
    },
    {
      name: "cignature",
      gender: "female",
      agency: "J9 Entertainment",
      members: [
        { name: "Chaesol", position: ["Leader", "Lead Dancer", "Vocalist"], birthYear: 1998, personality: ["Leader", "Reliable", "Bright"] },
        { name: "Jeewon", position: ["Lead Vocalist", "Lead Rapper"], birthYear: 2000, personality: ["Versatile", "Cool", "Friendly"] },
        { name: "Seline", position: ["Lead Vocalist"], birthYear: 2001, personality: ["SoftVoice", "Kind", "Gentle"] },
        { name: "Chloe", position: ["Main Rapper", "Sub Vocalist"], birthYear: 2001, personality: ["Charming", "Stylish", "Bright"] },
        { name: "Semi", position: ["Main Dancer", "Lead Vocalist"], birthYear: 2002, personality: ["DanceLine", "Energetic", "Positive"] },
        { name: "Dohee", position: ["Lead Vocalist"], birthYear: 2002, personality: ["Sweet", "Gentle", "Warm"] },
        { name: "Belle", position: ["Main Vocalist"], birthYear: 2004, personality: ["StrongVocal", "Bright", "YoungestEnergy"] },
      ],
    },
    {
      name: "STAYC",
      gender: "female",
      agency: "High Up Entertainment",
      members: [
        {
          name: "Sumin",
          position: ["Leader", "Lead Vocalist", "Lead Dancer", "Rapper"], birthYear: 2001, personality: ["Leader", "Reliable", "Bright"],
        },
        { name: "Sieun", position: ["Main Vocalist"], birthYear: 2001, personality: ["PowerVocal", "Warm", "Cheerful"] },
        { name: "Isa", position: ["Lead Vocalist"], birthYear: 2002, personality: ["Elegant", "Calm", "Kind"] },
        { name: "Seeun", position: ["Sub Vocalist"], birthYear: 2003, personality: ["Sweet", "Pure", "Gentle"] },
        { name: "Yoon", position: ["Lead Vocalist", "Lead Dancer"], birthYear: 2004, personality: ["Bright", "Playful", "Energetic"] },
        { name: "J", position: ["Main Rapper", "Lead Vocalist", "Maknae"], birthYear: 2004, personality: ["Youngest", "Chic", "Confident"] },
      ],
    },
    {
      name: "Weeekly",
      gender: "female",
      agency: "IST Entertainment",
      members: [
        {
          name: "Soojin",
          position: ["Leader", "Main Dancer", "Lead Vocalist"], birthYear: 2001, personality: ["Leader", "Reliable", "Graceful"],
        },
        { name: "Jiyoon", position: ["Main Rapper", "Lead Vocalist"], birthYear: 2002, personality: ["Cool", "Creative", "Versatile"] },
        { name: "Monday", position: ["Main Vocalist", "Main Dancer"], birthYear: 2002, personality: ["StrongVocal", "Bright", "Hardworking"] },
        { name: "Soeun", position: ["Main Dancer", "Lead Rapper", "Vocalist"], birthYear: 2002, personality: ["Performance", "Energetic", "Fun"] },
        { name: "Jaehee", position: ["Lead Vocalist", "Sub Rapper"], birthYear: 2004, personality: ["Gentle", "Kind", "Friendly"] },
        {
          name: "Jihan",
          position: ["Lead Vocalist", "Visual", "Face of the Group"], birthYear: 2004, personality: ["Visual", "Bright", "Cheerful"],
        },
        { name: "Zoa", position: ["Lead Rapper", "Sub Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "Playful", "Cute"] },
      ],
    },
    {
      name: "ENHYPEN",
      gender: "male",
      agency: "Belift Lab (HYBE x CJ ENM)",
      members: [
        {
          name: "Jungwon",
          position: ["Leader", "Lead Dancer", "Lead Vocalist", "Rapper"], birthYear: 2004, personality: ["Leader", "Calm", "Reliable"],
        },
        { name: "Heeseung", position: ["Main Vocalist", "Center", "Dancer"], birthYear: 2001, personality: ["Talented", "Passionate", "Focused"] },
        { name: "Jay", position: ["Main Rapper", "Lead Dancer", "Vocalist"], birthYear: 2002, personality: ["Charismatic", "Strong", "Cool"] },
        { name: "Jake", position: ["Lead Rapper", "Vocalist"], birthYear: 2002, personality: ["Gentle", "Warm", "GlobalCharm"] },
        { name: "Sunghoon", position: ["Lead Dancer", "Vocalist", "Visual"], birthYear: 2002, personality: ["Visual", "Calm", "Elegant"] },
        { name: "Sunoo", position: ["Lead Vocalist"], birthYear: 2003, personality: ["Bright", "Fun", "Cheerful"] },
        { name: "Ni-ki", position: ["Main Dancer", "Sub Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "DanceKing", "Energetic"] },
      ],
    },
    {
      name: "E'LAST",
      gender: "male",
      agency: "E Entertainment",
      members: [
        { name: "Rano", position: ["Leader", "Main Rapper", "Main Dancer"], birthYear: 1998, personality: ["Leader", "Charismatic", "Passionate"] },
        { name: "Choi In", position: ["Main Vocalist"], birthYear: 1999, personality: ["PowerVocal", "Gentle", "Focused"] },
        { name: "Seungyeop", position: ["Lead Vocalist"], birthYear: 2000, personality: ["BrightVoice", "Kind", "Reliable"] },
        { name: "Baekgyeol", position: ["Vocalist", "Visual"], birthYear: 1999, personality: ["Visual", "Calm", "Graceful"] },
        { name: "Romin", position: ["Lead Vocalist", "Visual"], birthYear: 2001, personality: ["Charming", "Elegant", "Bright"] },
        { name: "Won Hyuk", position: ["Main Rapper", "Vocalist"], birthYear: 2002, personality: ["Cool", "Creative", "Dynamic"] },
        { name: "Wonjun", position: ["Lead Rapper", "Vocalist"], birthYear: 2002, personality: ["Energetic", "Friendly", "Fun"] },
        { name: "Yejun", position: ["Lead Vocalist", "Maknae"], birthYear: 2002, personality: ["Youngest", "Warm", "Cheerful"] },
      ],
    },
    {
      name: "DRIPPIN",
      gender: "male",
      agency: "Woollim Entertainment",
      members: [
        { name: "Yunseong", position: ["Leader", "Main Dancer", "Vocalist"], birthYear: 2000, personality: ["Leader", "Reliable", "Calm"] },
        { name: "Hyeop", position: ["Main Vocalist"], birthYear: 1999, personality: ["StrongVocal", "Bright", "Sincere"] },
        { name: "Changuk", position: ["Lead Vocalist"], birthYear: 2002, personality: ["Gentle", "Kind", "Charming"] },
        { name: "Dongyun", position: ["Main Rapper", "Lead Dancer"], birthYear: 2002, personality: ["Cool", "Energetic", "Charismatic"] },
        { name: "Minseo", position: ["Lead Vocalist", "Maknae"], birthYear: 2002, personality: ["Youngest", "Bright", "Friendly"] },
        { name: "Junho", position: ["Lead Dancer", "Vocalist", "Visual"], birthYear: 2002, personality: ["Visual", "Chic", "Graceful"] },
        {
          name: "Alex",
          position: ["Rapper", "Vocalist", "Maknae (2019~2022 ?�동)"], birthYear: 2004, personality: ["Global", "Cheerful", "Youngest"],
        },
      ],
    },
    {
      name: "Secret Number",
      gender: "female",
      agency: "Vine Entertainment",
      members: [
        { name: "Léa", position: ["Leader", "Lead Vocalist"], birthYear: 1995, personality: ["Leader", "Calm", "Graceful"] },
        { name: "Dita", position: ["Main Dancer", "Sub Vocalist"], birthYear: 1996, personality: ["PerformanceQueen", "Bright", "Kind"] },
        {
          name: "Jinny",
          position: ["Main Rapper", "Lead Dancer", "Sub Vocalist"], birthYear: 1998, personality: ["Confident", "Energetic", "Cool"],
        },
        { name: "Minji", position: ["Main Vocalist"], birthYear: 1999, personality: ["PowerVocal", "Reliable", "Warm"] },
        { name: "Soodam", position: ["Lead Dancer", "Sub Vocalist", "Visual"], birthYear: 1999, personality: ["Visual", "Bright", "Charming"] },
        { name: "Zuu", position: ["Sub Rapper", "Sub Vocalist"], birthYear: 2001, personality: ["Youthful", "Sweet", "Positive"] },
      ],
    },
    {
      name: "BDC (Boys Da Capo)",
      gender: "male",
      agency: "Brand New Music",
      members: [
        {
          name: "Seongjun",
          position: ["Leader", "Main Rapper", "Sub Vocalist"], birthYear: 1996, personality: ["Leader", "Cool", "Confident"],
        },
        { name: "Sihoon", position: ["Main Dancer", "Lead Vocalist"], birthYear: 1999, personality: ["DanceLine", "Bright", "Cheerful"] },
        { name: "Jung Hwan", position: ["Main Vocalist", "Maknae"], birthYear: 2001, personality: ["Youngest", "SoftVoice", "Warm"] },
      ],
    },
    {
      name: "BOTOPASS",
      gender: "female",
      agency: "WKS ENE / JMG",
      members: [
        { name: "Mihee", position: ["Leader", "Main Vocalist"], birthYear: 1995, personality: ["Leader", "PowerVocal", "Reliable"] },
        { name: "Seoyoon", position: ["Lead Vocalist"], birthYear: 1996, personality: ["SoftVoice", "Gentle", "Bright"] },
        { name: "Ria", position: ["Lead Rapper", "Vocalist"], birthYear: 1997, personality: ["Cool", "Energetic", "Charismatic"] },
        { name: "Shiyeon", position: ["Main Dancer", "Lead Vocalist"], birthYear: 1998, personality: ["DanceLine", "Graceful", "Confident"] },
        { name: "Harin", position: ["Lead Dancer", "Vocalist"], birthYear: 1999, personality: ["Performance", "Bright", "Fun"] },
        { name: "Jiwon", position: ["Main Rapper", "Sub Vocalist"], birthYear: 1999, personality: ["RapLine", "Stylish", "Chic"] },
        { name: "Cyan", position: ["Main Vocalist"], birthYear: 2000, personality: ["StrongVocal", "Calm", "Elegant"] },
        { name: "Ahyoon", position: ["Vocalist", "Maknae"], birthYear: 2001, personality: ["Youngest", "Cute", "Friendly"] },
      ],
    },
    {
      name: "LE SSERAFIM",
      gender: "female",
      agency: "Source Music / HYBE",
      members: [
        { name: "Chaewon", position: ["Leader", "Vocalist", "Dancer"], birthYear: 2000, personality: ["Leader", "Calm", "Graceful"] },
        { name: "Sakura", position: ["Sub Vocalist", "Sub Rapper", "Visual"], birthYear: 1998, personality: ["Elegant", "Global", "Charming"] },
        { name: "Yunjin", position: ["Main Vocalist"], birthYear: 2001, personality: ["PowerVocal", "Confident", "Bright"] },
        {
          name: "Kazuha",
          position: ["Lead Rapper", "Lead Dancer", "Sub Vocalist"], birthYear: 2003, personality: ["Graceful", "Elegant", "Calm"],
        },
        {
          name: "Eunchae",
          position: ["Lead Dancer", "Sub Vocalist", "Maknae"], birthYear: 2006, personality: ["Youngest", "Energetic", "Bright"],
        },
      ],
    },
    {
      name: "NewJeans",
      gender: "female",
      agency: "ADOR (HYBE)",
      members: [
        {
          name: "Minji",
          position: ["Leader", "Lead Rapper", "Sub Vocalist"],
          birthYear: 2004,
          personality: ["leadership", "calm", "reliable"],
        },
        {
          name: "Hanni",
          position: ["Main Vocalist"],
          birthYear: 2004,
          personality: ["cheerful", "charming", "friendly"],
        },
        {
          name: "Danielle",
          position: ["Lead Vocalist", "Lead Dancer"],
          birthYear: 2005,
          personality: ["bright", "energetic", "talented"],
        },
        {
          name: "Haerin",
          position: ["Main Vocalist", "Sub Rapper"],
          birthYear: 2006,
          personality: ["cute", "calm", "cool"],
        },
        {
          name: "Hyein",
          position: ["Lead Vocalist", "Maknae"],
          birthYear: 2008,
          personality: ["cute", "energetic", "talented"],
        },
      ],
    },
    {
      name: "Kep1er",
      gender: "female",
      agency: "Wake One Entertainment / Swing Entertainment",
      members: [
        {
          name: "Yujin",
          position: ["Leader", "Lead Dancer", "Sub Vocalist", "Sub Rapper"], birthYear: 1996, personality: ["Leader", "Graceful", "Reliable"],
        },
        {
          name: "Mashiro",
          position: ["Co-Leader", "Sub Vocalist", "Sub Rapper"], birthYear: 1999, personality: ["Kind", "Gentle", "Organized"],
        },
        { name: "Xiaoting", position: ["Main Dancer", "Sub Vocalist"], birthYear: 1999, personality: ["Elegant", "Calm", "Graceful"] },
        { name: "Chaehyun", position: ["Main Vocalist"], birthYear: 2002, personality: ["PowerVocal", "Warm", "Friendly"] },
        {
          name: "Dayeon",
          position: ["Main Dancer", "Sub Vocalist", "Sub Rapper"], birthYear: 2003, personality: ["Performance", "Energetic", "Positive"],
        },
        { name: "Hikaru", position: ["Main Rapper", "Lead Dancer"], birthYear: 2004, personality: ["Charismatic", "Cool", "Dynamic"] },
        { name: "Huening Bahiyyih", position: ["Sub Vocalist", "Sub Rapper"], birthYear: 2004, personality: ["Sweet", "Soft", "Gentle"] },
        {
          name: "Youngeun",
          position: ["Main Dancer", "Lead Rapper", "Sub Vocalist"], birthYear: 2004, personality: ["Performance", "Bright", "Charming"],
        },
        { name: "Yeseo", position: ["Lead Dancer", "Lead Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "Cute", "Energetic"] },
      ],
    },
    {
      name: "NMIXX",
      gender: "female",
      agency: "JYP Entertainment",
      members: [
        { name: "Haewon", position: ["Leader", "Main Vocalist"], birthYear: 2003, personality: ["Leader", "Reliable", "StrongVocal"] },
        { name: "Lily", position: ["Main Vocalist"], birthYear: 2002, personality: ["Global", "Passionate", "Bright"] },
        { name: "Sullyoon", position: ["Vocalist", "Visual"], birthYear: 2004, personality: ["Visual", "Gentle", "Graceful"] },
        { name: "Bae", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 2004, personality: ["Calm", "Elegant", "Charming"] },
        {
          name: "Jiwoo",
          position: ["Main Rapper", "Main Dancer", "Sub Vocalist"], birthYear: 2005, personality: ["Charismatic", "Confident", "Stylish"],
        },
        { name: "Kyujin", position: ["Main Dancer", "Lead Rapper", "Maknae"], birthYear: 2006, personality: ["Youngest", "Energetic", "Bright"] },
      ],
    },
    {
      name: "XG",
      gender: "female",
      agency: "XGALX",
      members: [
        { name: "Jurin", position: ["Leader", "Main Rapper", "Lead Dancer"], birthYear: 2002, personality: ["Leader", "Powerful", "Charismatic"] },
        { name: "Chisa", position: ["Main Vocalist"], birthYear: 2002, personality: ["SoftVoice", "Warm", "Gentle"] },
        { name: "Harvey", position: ["Lead Rapper", "Lead Dancer"], birthYear: 2002, personality: ["Cool", "Confident", "Creative"] },
        { name: "Hinata", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 2002, personality: ["Graceful", "Calm", "Bright"] },
        { name: "Juria", position: ["Main Vocalist"], birthYear: 2004, personality: ["StrongVocal", "Kind", "Cheerful"] },
        { name: "Maya", position: ["Main Rapper", "Lead Vocalist"], birthYear: 2005, personality: ["Versatile", "Energetic", "Chic"] },
        { name: "Cocona", position: ["Main Rapper", "Maknae"], birthYear: 2005, personality: ["Youngest", "Bold", "Cool"] },
      ],
    },
    {
      name: "TNX",
      gender: "male",
      agency: "PNation",
      members: [
        { name: "Taehun", position: ["Leader", "Main Vocalist"], birthYear: 2000, personality: ["Leader", "Gentle", "Reliable"] },
        { name: "Kyungjun", position: ["Lead Rapper"], birthYear: 2003, personality: ["Cool", "Bright", "Friendly"] },
        { name: "Hyunsoo", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 2003, personality: ["Performance", "Cheerful", "Charming"] },
        { name: "Junhyeok", position: ["Main Rapper", "Lead Dancer"], birthYear: 2004, personality: ["Dynamic", "Strong", "Confident"] },
        { name: "Hwi", position: ["Main Vocalist", "Sub Rapper"], birthYear: 2004, personality: ["Bright", "Warm", "Positive"] },
        { name: "Sungjun", position: ["Lead Rapper", "Maknae"], birthYear: 2005, personality: ["Youngest", "Playful", "Energetic"] },
      ],
    },
    {
      name: "BAE173",
      gender: "male",
      agency: "PocketDol Studio",
      members: [
        { name: "J-Min", position: ["Leader", "Main Rapper"], birthYear: 1999, personality: ["Leader", "Confident", "Calm"] },
        { name: "Hangyul", position: ["Main Dancer", "Lead Vocalist"], birthYear: 1999, personality: ["Bright", "Friendly", "Charming"] },
        { name: "Yoojun", position: ["Lead Rapper", "Vocalist"], birthYear: 2000, personality: ["Cool", "Stylish", "Reliable"] },
        { name: "Muzin", position: ["Main Dancer", "Sub Rapper"], birthYear: 2000, personality: ["DanceLine", "Energetic", "Fun"] },
        { name: "Junseo", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 2001, personality: ["Gentle", "Kind", "Bright"] },
        { name: "Youngseo", position: ["Main Vocalist"], birthYear: 2001, personality: ["PowerVocal", "Warm", "Sincere"] },
        { name: "Doha", position: ["Main Rapper", "Sub Vocalist"], birthYear: 2004, personality: ["Young", "Confident", "Stylish"] },
        { name: "Bit", position: ["Sub Rapper", "Vocalist"], birthYear: 2004, personality: ["Bright", "Friendly", "Playful"] },
        { name: "Dohyon", position: ["Main Rapper", "Maknae"], birthYear: 2004, personality: ["Youngest", "Bold", "Energetic"] },
      ],
    },
    {
      name: "BOYNEXTDOOR",
      gender: "male",
      agency: "KOZ Entertainment (HYBE)",
      members: [
        { name: "Jaehyun", position: ["Leader", "Vocalist", "Rapper"], birthYear: 2003, personality: ["Leader", "Cool", "Calm"] },
        { name: "Sungho", position: ["Main Vocalist"], birthYear: 2003, personality: ["Bright", "Warm", "Friendly"] },
        { name: "Riwoo", position: ["Main Dancer", "Vocalist"], birthYear: 2003, personality: ["DanceLine", "Energetic", "Cheerful"] },
        { name: "Taesan", position: ["Main Rapper", "Vocalist"], birthYear: 2004, personality: ["Charismatic", "Confident", "Stylish"] },
        { name: "Leehan", position: ["Sub Vocalist", "Visual"], birthYear: 2004, personality: ["Visual", "Gentle", "Elegant"] },
        { name: "Woonhak", position: ["Lead Rapper", "Maknae"], birthYear: 2006, personality: ["Youngest", "Playful", "Bright"] },
      ],
    },
    {
      name: "ZEROBASEONE (ZB1)",
      gender: "male",
      agency: "WakeOne Entertainment",
      members: [
        {
          name: "Sung Hanbin",
          position: ["Leader", "Main Dancer", "Lead Vocalist"], birthYear: 2001, personality: ["Leader", "Elegant", "Reliable"],
        },
        { name: "Kim Jiwoong", position: ["Lead Vocalist", "Visual"], birthYear: 1998, personality: ["Cool", "Charming", "Calm"] },
        { name: "Zhang Hao", position: ["Center", "Main Vocalist"], birthYear: 2000, personality: ["Gentle", "Focused", "Sincere"] },
        { name: "Seok Matthew", position: ["Lead Vocalist"], birthYear: 2002, personality: ["Bright", "Energetic", "Friendly"] },
        { name: "Kim Taerae", position: ["Main Vocalist"], birthYear: 2002, personality: ["Warm", "Kind", "Reliable"] },
        { name: "Ricky", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 2004, personality: ["Stylish", "Confident", "Calm"] },
        {
          name: "Kim Gyuvin",
          position: ["Main Dancer", "Sub Vocalist", "Visual"], birthYear: 2004, personality: ["Visual", "Charming", "Bright"],
        },
        { name: "Park Gunwook", position: ["Main Rapper", "Lead Dancer"], birthYear: 2005, personality: ["Cool", "Dynamic", "Confident"] },
        {
          name: "Han Yujin",
          position: ["Lead Dancer", "Sub Vocalist", "Maknae"], birthYear: 2007, personality: ["Youngest", "Energetic", "Cheerful"],
        },
      ],
    },
    {
      name: "RIIZE",
      gender: "male",
      agency: "SM Entertainment",
      members: [
        { name: "Shotaro", position: ["Main Dancer", "Lead Rapper"], birthYear: 2000, personality: ["Performance", "Bright", "Kind"] },
        { name: "Eunseok", position: ["Lead Rapper", "Visual"], birthYear: 2001, personality: ["Visual", "Calm", "Gentle"] },
        { name: "Sungchan", position: ["Main Rapper", "Lead Dancer"], birthYear: 2000, personality: ["Charismatic", "Confident", "Cool"] },
        { name: "Wonbin", position: ["Lead Rapper", "Lead Vocalist"], birthYear: 2002, personality: ["Stylish", "SoftVoice", "Graceful"] },
        { name: "Sohee", position: ["Main Vocalist"], birthYear: 2001, personality: ["PowerVocal", "Bright", "Warm"] },
        { name: "Anton", position: ["Lead Vocalist", "Maknae"], birthYear: 2004, personality: ["Youngest", "Gentle", "Sweet"] },
      ],
    },
    {
      name: "KISS OF LIFE",
      gender: "female",
      agency: "S2 Entertainment",
      members: [
        { name: "Julie", position: ["Leader", "Main Rapper"], birthYear: 2000, personality: ["Leader", "Charismatic", "Bold"] },
        { name: "Natty", position: ["Main Dancer", "Lead Vocalist"], birthYear: 2002, personality: ["Performance", "Energetic", "Cheerful"] },
        { name: "Belle", position: ["Main Vocalist"], birthYear: 2004, personality: ["BrightVoice", "Kind", "Sincere"] },
        { name: "Haneul", position: ["Lead Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "SoftVoice", "Friendly"] },
      ],
    },
    {
      name: "PLAVE",
      gender: "male",
      agency: "Vlast",
      members: [
        { name: "Yejun", position: ["Leader", "Main Vocalist"], birthYear: 2002, personality: ["Leader", "Calm", "Warm"] },
        { name: "Noah", position: ["Main Rapper", "Sub Vocalist"], birthYear: 2003, personality: ["Creative", "Confident", "Charming"] },
        { name: "Bamby", position: ["Main Dancer", "Vocalist"], birthYear: 2003, personality: ["DanceLine", "Bright", "Playful"] },
        { name: "Eunho", position: ["Lead Rapper", "Vocalist"], birthYear: 2004, personality: ["Kind", "Chic", "Cool"] },
        { name: "Hamin", position: ["Lead Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "Bright", "Cute"] },
      ],
    },
    {
      name: "BABYMONSTER",
      gender: "female",
      agency: "YG Entertainment",
      members: [
        { name: "Ruka", position: ["Main Rapper", "Lead Dancer"], birthYear: 2002, personality: ["Charismatic", "Confident", "Cool"] },
        { name: "Pharita", position: ["Main Vocalist"], birthYear: 2005, personality: ["StrongVocal", "Warm", "Graceful"] },
        { name: "Asa", position: ["Main Rapper", "Lead Dancer"], birthYear: 2006, personality: ["Powerful", "Energetic", "Creative"] },
        { name: "Ahyeon", position: ["Main Vocalist", "Lead Rapper"], birthYear: 2007, personality: ["Bright", "Versatile", "Cheerful"] },
        { name: "Rami (Haram)", position: ["Main Vocalist"], birthYear: 2007, personality: ["Elegant", "Calm", "Warm"] },
        { name: "Chiquita", position: ["Lead Vocalist", "Maknae"], birthYear: 2009, personality: ["Youngest", "Cute", "Energetic"] },
        { name: "Rora", position: ["Lead Vocalist"], birthYear: 2008, personality: ["Sweet", "Bright", "Friendly"] },
      ],
    },
    {
      name: "ILLIT",
      gender: "female",
      agency: "Belift Lab (HYBE)",
      members: [
        { name: "Yunah", position: ["Leader", "Main Vocalist"], birthYear: 2004, personality: ["Leader", "Gentle", "Reliable"] },
        { name: "Minju", position: ["Main Rapper", "Lead Dancer"], birthYear: 2004, personality: ["Confident", "Stylish", "Cool"] },
        { name: "Moka", position: ["Lead Vocalist"], birthYear: 2004, personality: ["Calm", "Elegant", "Graceful"] },
        { name: "Wonhee", position: ["Main Vocalist", "Center"], birthYear: 2007, personality: ["Bright", "Charming", "Positive"] },
        { name: "Iroha", position: ["Lead Dancer", "Sub Vocalist", "Maknae"], birthYear: 2008, personality: ["Youngest", "Cute", "Energetic"] },
      ],
    },
    {
      name: "UNIS",
      gender: "female",
      agency: "F&F Entertainment / Kakao Entertainment",
      members: [
        { name: "Jin Hyeonju", position: ["Leader", "Main Vocalist"], birthYear: 2002, personality: ["Leader", "StrongVocal", "Reliable"] },
        { name: "Im Yoonseo", position: ["Lead Vocalist"], birthYear: 2004, personality: ["Bright", "Friendly", "Warm"] },
        { name: "Nanami", position: ["Lead Dancer", "Vocalist"], birthYear: 2005, personality: ["Graceful", "Calm", "Kind"] },
        { name: "Kotone", position: ["Lead Rapper", "Vocalist"], birthYear: 2006, personality: ["Cool", "Creative", "Energetic"] },
        { name: "Elisia", position: ["Main Vocalist"], birthYear: 2009, personality: ["Young", "StrongVocal", "Passionate"] },
        { name: "Oh Yewon", position: ["Lead Rapper", "Sub Vocalist"], birthYear: 2008, personality: ["Playful", "Bright", "Friendly"] },
        { name: "Camila", position: ["Main Dancer", "Vocalist"], birthYear: 2006, personality: ["Performance", "Energetic", "Charming"] },
        { name: "Lim Seowon", position: ["Sub Vocalist", "Maknae"], birthYear: 2008, personality: ["Youngest", "Cute", "Positive"] },
      ],
    },
    {
      name: "TWS",
      gender: "male",
      agency: "Pledis Entertainment (HYBE)",
      members: [
        { name: "Shinyu", position: ["Leader", "Lead Rapper", "Sub Vocalist"], birthYear: 2003, personality: ["Leader", "Calm", "Reliable"] },
        { name: "Dohoon", position: ["Main Vocalist"], birthYear: 2005, personality: ["Bright", "Warm", "Cheerful"] },
        { name: "Youngjae", position: ["Lead Vocalist"], birthYear: 2005, personality: ["Gentle", "Positive", "Friendly"] },
        { name: "Kyungmin", position: ["Main Rapper"], birthYear: 2004, personality: ["Confident", "Stylish", "Cool"] },
        { name: "Hanjin", position: ["Main Dancer", "Vocalist"], birthYear: 2006, personality: ["DanceLine", "Energetic", "Fun"] },
        { name: "Jihoon", position: ["Lead Dancer", "Sub Vocalist", "Maknae"], birthYear: 2007, personality: ["Youngest", "Cute", "Bright"] },
      ],
    },
    {
      name: "KATSEYE",
      gender: "female",
      agency: "HYBE x Geffen Records",
      members: [
        { name: "Lara Rajagopal", position: ["Leader", "Main Vocalist"], birthYear: 2005, personality: ["Leader", "Graceful", "Confident"] },
        { name: "Sophia Laforteza", position: ["Main Rapper", "Lead Dancer"], birthYear: 2002, personality: ["Cool", "Powerful", "Creative"] },
        {
          name: "Daniela Avanzini",
          position: ["Main Dancer", "Lead Vocalist"], birthYear: 2004, personality: ["Charming", "Energetic", "Bright"],
        },
        { name: "Manon Bannerman", position: ["Lead Rapper", "Vocalist"], birthYear: 2003, personality: ["Stylish", "Chic", "Confident"] },
        { name: "Megan Skiendziel", position: ["Lead Vocalist"], birthYear: 2006, personality: ["SoftVoice", "Friendly", "Positive"] },
        { name: "Yoonchae Jeong", position: ["Sub Vocalist", "Maknae"], birthYear: 2007, personality: ["Youngest", "Cute", "Cheerful"] },
      ],
    },
    {
      name: "RESCENE",
      gender: "female",
      agency: "Great M Entertainment",
      members: [
        { name: "Woni", position: ["Leader", "Main Dancer", "Vocalist"], birthYear: 2004, personality: ["Leader", "Bright", "Charming"] },
        { name: "Liv", position: ["Main Vocalist"], birthYear: 2005, personality: ["StrongVocal", "Graceful", "Kind"] },
        { name: "Minami", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 2005, personality: ["DanceLine", "Calm", "Cute"] },
        { name: "Mayu", position: ["Main Rapper", "Sub Vocalist"], birthYear: 2006, personality: ["Cool", "Creative", "Fun"] },
        { name: "Yuzu", position: ["Lead Vocalist", "Maknae"], birthYear: 2007, personality: ["Youngest", "Bright", "Playful"] },
      ],
    },
    {
      name: "ALL(H)OURS",
      gender: "male",
      agency: "EDEN Entertainment",
      members: [
        { name: "Mingyu", position: ["Leader", "Main Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Jungmin", position: ["Main Dancer", "Lead Rapper"], birthYear: 2003, personality: ["Energetic", "Performance", "Charming"] },
        { name: "Hyunwoo", position: ["Main Rapper", "Vocalist"], birthYear: 2003, personality: ["Cool", "Stylish", "Confident"] },
        { name: "Yoonmin", position: ["Lead Vocalist", "Sub Rapper"], birthYear: 2003, personality: ["Gentle", "Friendly", "Bright"] },
        { name: "Jinsung", position: ["Main Dancer", "Sub Vocalist"], birthYear: 2004, personality: ["DanceLine", "Fun", "Positive"] },
        { name: "Sion", position: ["Lead Vocalist", "Maknae"], birthYear: 2005, personality: ["Youngest", "Cute", "Warm"] },
      ],
    },
    {
      name: "AMPERS&ONE",
      gender: "male",
      agency: "FNC Entertainment",
      members: [
        { name: "Kamden", position: ["Leader", "Main Rapper"], birthYear: 2001, personality: ["Leader", "Confident", "Stylish"] },
        { name: "Brian", position: ["Main Vocalist"], birthYear: 2003, personality: ["Bright", "Gentle", "Warm"] },
        { name: "Jiho", position: ["Lead Vocalist"], birthYear: 2004, personality: ["Calm", "Charming", "Kind"] },
        { name: "Seungmo", position: ["Main Dancer", "Vocalist"], birthYear: 2003, personality: ["Performance", "Energetic", "Friendly"] },
        { name: "Kyrell", position: ["Lead Rapper"], birthYear: 2003, personality: ["Cool", "Creative", "Chic"] },
        { name: "Sangmin", position: ["Main Vocalist"], birthYear: 2004, personality: ["PowerVocal", "Bright", "Positive"] },
        { name: "Kyungmin", position: ["Lead Rapper", "Maknae"], birthYear: 2006, personality: ["Youngest", "Playful", "Energetic"] },
      ],
    },
    {
      name: "NOWADAYS",
      gender: "male",
      agency: "Cube Entertainment",
      members: [
        { name: "Jinhyuk", position: ["Leader", "Main Vocalist"], birthYear: 2004, personality: ["Leader", "Reliable", "Bright"] },
        { name: "Woohyuk", position: ["Main Rapper", "Lead Dancer"], birthYear: 2004, personality: ["Cool", "Confident", "Dynamic"] },
        { name: "Seokmin", position: ["Lead Vocalist"], birthYear: 2005, personality: ["Gentle", "Kind", "Bright"] },
        { name: "Yujin", position: ["Main Dancer", "Vocalist"], birthYear: 2005, personality: ["DanceLine", "Cheerful", "Friendly"] },
        { name: "Hyunseo", position: ["Lead Rapper", "Maknae"], birthYear: 2006, personality: ["Youngest", "Playful", "Cute"] },
      ],
    },
    {
      name: "EXO",
      gender: "male",
      agency: "SM Entertainment",
      members: [
        { name: "Suho", position: ["Leader", "Lead Vocalist"], birthYear: 1991, personality: ["talented", "bright", "reliable"] },
        { name: "Xiumin", position: ["Lead Vocalist", "Lead Dancer"], birthYear: 1990, personality: ["talented", "bright", "reliable"] },
        { name: "Lay", position: ["Main Dancer", "Vocalist"], birthYear: 1991, personality: ["talented", "bright", "reliable"] },
        { name: "Baekhyun", position: ["Main Vocalist"], birthYear: 1992, personality: ["talented", "bright", "reliable"] },
        { name: "Chen", position: ["Main Vocalist"], birthYear: 1992, personality: ["talented", "bright", "reliable"] },
        { name: "Chanyeol", position: ["Main Rapper", "Vocalist"], birthYear: 1992, personality: ["talented", "bright", "reliable"] },
        { name: "D.O.", position: ["Main Vocalist"], birthYear: 1993, personality: ["talented", "bright", "reliable"] },
        {
          name: "Kai",
          position: ["Main Dancer", "Sub Rapper", "Visual", "Center"], birthYear: 1994, personality: ["talented", "bright", "reliable"],
        },
        {
          name: "Sehun",
          position: ["Lead Dancer", "Sub Rapper", "Visual", "Maknae"], birthYear: 1994, personality: ["talented", "bright", "reliable"],
        },
      ],
    },
    {
      name: "Red Velvet",
      gender: "female",
      agency: "SM Entertainment",
      members: [
        {
          name: "Irene",
          position: ["Leader", "Main Rapper", "Lead Dancer", "Visual"], birthYear: 1991, personality: ["talented", "bright", "reliable"],
        },
        { name: "Seulgi", position: ["Main Dancer", "Lead Vocalist"], birthYear: 1994, personality: ["talented", "bright", "reliable"] },
        { name: "Wendy", position: ["Main Vocalist"], birthYear: 1994, personality: ["talented", "bright", "reliable"] },
        { name: "Joy", position: ["Lead Rapper", "Sub Vocalist"], birthYear: 1996, personality: ["talented", "bright", "reliable"] },
        { name: "Yeri", position: ["Sub Vocalist", "Sub Rapper", "Maknae"], birthYear: 1999, personality: ["talented", "bright", "reliable"] },
      ],
    },
    {
      name: "SEVENTEEN",
      gender: "male",
      agency: "Pledis Entertainment (HYBE)",
      members: [
        {
          name: "S.Coups",
          position: ["Leader", "Hip-Hop Team Leader", "Main Rapper"], birthYear: 1995, personality: ["talented", "bright", "reliable"],
        },
        { name: "Jeonghan", position: ["Lead Vocalist"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
        { name: "Joshua", position: ["Lead Vocalist"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
        { name: "Jun", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 1996, personality: ["talented", "bright", "reliable"] },
        {
          name: "Hoshi",
          position: ["Performance Team Leader", "Main Dancer", "Lead Vocalist"], birthYear: 1996, personality: ["talented", "bright", "reliable"],
        },
        { name: "Wonwoo", position: ["Lead Rapper"], birthYear: 1996, personality: ["talented", "bright", "reliable"] },
        {
          name: "Woozi",
          position: ["Vocal Team Leader", "Lead Vocalist", "Producer"], birthYear: 1996, personality: ["talented", "bright", "reliable"],
        },
        { name: "DK", position: ["Main Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Mingyu", position: ["Lead Rapper", "Visual"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "The8", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Seungkwan", position: ["Main Vocalist"], birthYear: 1998, personality: ["talented", "bright", "reliable"] },
        { name: "Vernon", position: ["Main Rapper"], birthYear: 1998, personality: ["talented", "bright", "reliable"] },
        { name: "Dino", position: ["Main Dancer", "Sub Vocalist", "Maknae"], birthYear: 1999, personality: ["talented", "bright", "reliable"] },
      ],
    },
    {
      name: "TWICE",
      gender: "female",
      agency: "JYP Entertainment",
      members: [
        { name: "Nayeon", position: ["Lead Vocalist", "Center"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
        { name: "Jeongyeon", position: ["Lead Vocalist"], birthYear: 1996, personality: ["talented", "bright", "reliable"] },
        {
          name: "Momo",
          position: ["Main Dancer", "Sub Vocalist", "Sub Rapper"], birthYear: 1996, personality: ["talented", "bright", "reliable"],
        },
        { name: "Sana", position: ["Sub Vocalist"], birthYear: 1996, personality: ["talented", "bright", "reliable"] },
        { name: "Jihyo", position: ["Leader", "Main Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Mina", position: ["Main Dancer", "Sub Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Dahyun", position: ["Lead Rapper", "Sub Vocalist"], birthYear: 1998, personality: ["talented", "bright", "reliable"] },
        { name: "Chaeyoung", position: ["Main Rapper", "Sub Vocalist"], birthYear: 1999, personality: ["talented", "bright", "reliable"] },
        {
          name: "Tzuyu",
          position: ["Lead Dancer", "Sub Vocalist", "Visual", "Maknae"], birthYear: 1999, personality: ["talented", "bright", "reliable"],
        },
      ],
    },
    {
      name: "GFRIEND",
      gender: "female",
      agency: "Source Music",
      members: [
        { name: "Sowon", position: ["Leader", "Sub Vocalist", "Visual"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
        { name: "Yerin", position: ["Lead Dancer", "Sub Vocalist"], birthYear: 1996, personality: ["talented", "bright", "reliable"] },
        { name: "Eunha", position: ["Lead Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Yuju", position: ["Main Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "SinB", position: ["Main Dancer", "Sub Vocalist"], birthYear: 1998, personality: ["talented", "bright", "reliable"] },
        { name: "Umji", position: ["Sub Vocalist", "Maknae"], birthYear: 1998, personality: ["talented", "bright", "reliable"] },
      ],
    },
    {
      name: "MAMAMOO",
      gender: "female",
      agency: "RBW Entertainment",
      members: [
        { name: "Solar", position: ["Leader", "Main Vocalist"], birthYear: 1991, personality: ["talented", "bright", "reliable"] },
        { name: "Moonbyul", position: ["Main Rapper", "Main Dancer"], birthYear: 1992, personality: ["talented", "bright", "reliable"] },
        { name: "Wheein", position: ["Lead Vocalist", "Lead Dancer"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
        { name: "Hwasa", position: ["Lead Rapper", "Sub Vocalist", "Maknae"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
      ],
    },
    {
      name: "iKON",
      gender: "male",
      agency: "YG Entertainment",
      members: [
        { name: "B.I", position: ["Leader", "Main Rapper"], birthYear: 1996, personality: ["talented", "bright", "reliable"] },
        { name: "Bobby", position: ["Main Rapper", "Vocalist"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
        { name: "Jinhwan", position: ["Main Vocalist", "Lead Dancer"], birthYear: 1994, personality: ["talented", "bright", "reliable"] },
        { name: "Yunhyeong", position: ["Lead Vocalist"], birthYear: 1995, personality: ["talented", "bright", "reliable"] },
        { name: "Donghyuk", position: ["Main Dancer", "Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Junhoe", position: ["Main Vocalist"], birthYear: 1997, personality: ["talented", "bright", "reliable"] },
        { name: "Chanwoo", position: ["Sub Vocalist", "Maknae"], birthYear: 1998, personality: ["talented", "bright", "reliable"] },
      ],
    },
    {
      name: "WINNER",
      gender: "male",
      agency: "YG Entertainment",
      members: [
        { name: "Jinu", position: ["Lead Vocalist", "Visual"], birthYear: 1991, personality: ["talented", "bright", "reliable"] },
        { name: "Seunghoon", position: ["Main Dancer", "Rapper"], birthYear: 1992, personality: ["talented", "bright", "reliable"] },
        { name: "Mino", position: ["Main Rapper", "Vocalist"], birthYear: 1993, personality: ["talented", "bright", "reliable"] },
        { name: "Seungyoon", position: ["Leader", "Main Vocalist", "Maknae"], birthYear: 1994, personality: ["talented", "bright", "reliable"] },
      ],
    },
  ],
};

export type KpopGroup = (typeof kpopGroupsData.groups)[0];
export type KpopMember = KpopGroup["members"][0];



