export const kpopGroupsData = {
  groups: [
    {
      name: "BTS",
      gender: "male",
      agency: "빅히트 뮤직",
      members: [
        {
          name: "RM",
          position: ["리더", "메인 래퍼"],
          birthYear: 1994,
          personality: ["차분함", "지적", "리더십"],
        },
        {
          name: "진",
          position: ["서브 보컬", "비주얼"],
          birthYear: 1992,
          personality: ["밝음", "유머러스", "친근함"],
        },
        {
          name: "슈가",
          position: ["리드 래퍼"],
          birthYear: 1993,
          personality: ["차분함", "프로페셔널", "섬세함"],
        },
        {
          name: "제이홉",
          position: ["메인 댄서", "서브 래퍼", "서브 보컬"],
          birthYear: 1994,
          personality: ["밝음", "활발함", "긍정적"],
        },
        {
          name: "지민",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 1995,
          personality: ["친근함", "부드러움", "감성적"],
        },
        {
          name: "뷔",
          position: ["리드 댄서", "서브 보컬", "비주얼"],
          birthYear: 1995,
          personality: ["차분함", "예술적", "신비로움"],
        },
        {
          name: "정국",
          position: ["메인 보컬", "리드 댄서", "서브 래퍼", "센터", "막내"],
          birthYear: 1997,
          personality: ["재능있음", "열정적", "올라운더"],
        },
      ],
    },
    {
      name: "BLACKPINK",
      gender: "female",
      agency: "YG 엔터테인먼트",
      members: [
        {
          name: "지수",
          position: ["리드 보컬", "비주얼"],
          birthYear: 1995,
          personality: ["차분함", "우아함", "프로페셔널"],
        },
        {
          name: "제니",
          position: ["메인 래퍼", "리드 보컬"],
          birthYear: 1996,
          personality: ["카리스마", "시크함", "트렌디"],
        },
        {
          name: "로제",
          position: ["메인 보컬", "리드 댄서"],
          birthYear: 1997,
          personality: ["감성적", "섬세함", "예술적"],
        },
        {
          name: "리사",
          position: ["메인 댄서", "리드 래퍼", "서브 보컬", "막내"],
          birthYear: 1997,
          personality: ["활발함", "에너지 넘침", "친근함"],
        },
      ],
    },
    {
      name: "IVE",
      gender: "female",
      agency: "스타쉽 엔터테인먼트",
      members: [
        {
          name: "안유진",
          position: ["리더", "리드 보컬"],
          birthYear: 2003,
          personality: ["밝음", "리더십", "친근함"],
        },
        {
          name: "가을",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 2002,
          personality: ["차분함", "프로페셔널", "카리스마"],
        },
        {
          name: "레이",
          position: ["래퍼", "서브 보컬"],
          birthYear: 2004,
          personality: ["활발함", "귀여움", "친근함"],
        },
        {
          name: "장원영",
          position: ["리드 댄서", "서브 보컬", "비주얼", "센터"],
          birthYear: 2004,
          personality: ["우아함", "시크함", "카리스마"],
        },
        {
          name: "리즈",
          position: ["메인 보컬"],
          birthYear: 2004,
          personality: ["밝음", "긍정적", "열정적"],
        },
        {
          name: "이서",
          position: ["서브 보컬", "막내"],
          birthYear: 2007,
          personality: ["귀여움", "활발함", "에너지 넘침"],
        },
      ],
    },
    {
      name: "aespa",
      gender: "female",
      agency: "SM 엔터테인먼트",
      members: [
        {
          name: "카리나",
          position: [
            "리더",
            "메인 댄서",
            "리드 래퍼",
            "서브 보컬",
            "비주얼",
            "센터",
          ],
          birthYear: 2000,
          personality: ["카리스마", "리더십", "프로페셔널"],
        },
        {
          name: "지젤",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 2000,
          personality: ["시크함", "트렌디", "자신감"],
        },
        {
          name: "윈터",
          position: ["리드 보컬", "리드 댄서", "비주얼"],
          birthYear: 2001,
          personality: ["차분함", "우아함", "감성적"],
        },
        {
          name: "닝닝",
          position: ["메인 보컬", "막내"],
          birthYear: 2002,
          personality: ["밝음", "친근함", "재능있음"],
        },
      ],
    },
    {
      name: "(G)I-DLE",
      gender: "female",
      agency: "큐브 엔터테인먼트",
      members: [
        {
          name: "소연",
          position: ["리더", "메인 래퍼", "센터", "서브 보컬"],
          birthYear: 1998,
          personality: ["리더십", "창의적(프로듀싱)", "카리스마"],
        },
        {
          name: "민니",
          position: ["메인 보컬"],
          birthYear: 1997,
          personality: ["감성적", "차분함", "따뜻함"],
        },
        {
          name: "우기",
          position: ["리드 댄서", "서브 보컬", "서브 래퍼"],
          birthYear: 1999,
          personality: ["유쾌함", "에너지", "친근함"],
        },
        {
          name: "슈화",
          position: ["서브 보컬", "비주얼", "막내"],
          birthYear: 2000,
          personality: ["솔직함", "당찬", "장난기"],
        },
        {
          name: "미연",
          position: ["메인 보컬", "비주얼"],
          birthYear: 1997,
          personality: ["우아함", "차분함", "배려심"],
        },
      ],
    },
    {
      name: "KIIRAS",
      gender: "female",
      agency: "LeanBranding",
      members: [
        {
          name: "링링",
          position: ["리더", "메인 래퍼", "서브 보컬"],
          birthYear: 2006,
          personality: ["Multilingual", "Leader", "Trailblazer"],
        },
        {
          name: "쿠루미",
          position: ["메인 보컬"],
          birthYear: 2007,
          personality: ["SweetVoice", "Calm", "Reliable"],
        },
        {
          name: "하린",
          position: ["센터"],
          birthYear: 2008,
          personality: ["Studious", "Precise", "Charming"],
        },
        {
          name: "카일리",
          position: ["메인 래퍼"],
          birthYear: 2009,
          personality: ["PowerfulRap", "Energetic", "Confident"],
        },
        {
          name: "도연",
          position: ["서브 보컬"],
          birthYear: 2010,
          personality: ["RisingStar", "Youthful", "AllRounder"],
        },
        {
          name: "로아",
          position: ["메인 보컬", "막내"],
          birthYear: 2012,
          personality: ["Youngest", "VocalTalent", "Bright"],
        },
      ],
    },
    {
      name: "KickFlip",
      gender: "male",
      agency: "JYP 엔터테인먼트",
      members: [
        {
          name: "계훈",
          position: ["리더", "에이스"],
          birthYear: 2004,
          personality: ["Leader", "Ace", "StrongStagePresence"],
        },
        {
          name: "아마루",
          position: ["보컬", "랩"],
          birthYear: 2005,
          personality: ["Versatile", "SmoothVoice", "Charismatic"],
        },
        {
          name: "동화",
          position: ["댄스"],
          birthYear: 2006,
          personality: ["DanceMaster", "Energetic", "SilentPower"],
        },
        {
          name: "주왕",
          position: ["보컬"],
          birthYear: 2005,
          personality: ["PowerVocals", "Steady", "Warm"],
        },
        {
          name: "민제",
          position: ["비주얼", "랩"],
          birthYear: 2006,
          personality: ["Visual", "RapSkill", "BrightSmile"],
        },
        {
          name: "케이주",
          position: ["댄스"],
          birthYear: 2007,
          personality: ["DanceLine", "Flexible", "Energetic"],
        },
        {
          name: "동현",
          position: ["막내", "보컬"],
          birthYear: 2008,
          personality: ["Youngest", "RisingVocal", "Fresh"],
        },
      ],
    },
    {
      name: "Hearts2Hearts",
      gender: "female",
      agency: "SM 엔터테인먼트",
      members: [
        {
          name: "지우",
          position: ["리더", "메인 댄서", "비주얼"],
          birthYear: 2006,
          personality: ["Elegant", "StrongDancer", "Leader"],
        },
        {
          name: "카르멘",
          position: ["메인 보컬"],
          birthYear: 2006,
          personality: ["PowerVocals", "Soulful", "Confident"],
        },
        {
          name: "유하",
          position: ["리드 보컬", "리드 댄서"],
          birthYear: 2007,
          personality: ["DualTalents", "Energetic", "Passionate"],
        },
        {
          name: "스텔라",
          position: ["리드 보컬"],
          birthYear: 2007,
          personality: ["BrightVoice", "Friendly", "Charismatic"],
        },
        {
          name: "준",
          position: ["메인 댄서", "메인 래퍼", "서브 보컬"],
          birthYear: 2005,
          personality: ["DanceRapHybrid", "Dynamic", "Cool"],
        },
        {
          name: "아나",
          position: ["리드 보컬", "비주얼"],
          birthYear: 2008,
          personality: ["Visual", "GentleVoice", "AllRounder"],
        },
        {
          name: "이안",
          position: ["센터", "비주얼", "리드 댄서", "서브 보컬"],
          birthYear: 2009,
          personality: ["Center", "Visual", "MultiTalented"],
        },
        {
          name: "예온",
          position: ["리드 보컬", "막내"],
          birthYear: 2010,
          personality: ["Youngest", "BrightFuture", "Charming"],
        },
      ],
    },
    {
      name: "ifeye",
      gender: "female",
      agency: "하이햇 엔터테인먼트",
      members: [
        {
          name: "카시아",
          position: ["리더", "래퍼"],
          birthYear: 2004,
          personality: ["Leader", "RapMaster", "Bold"],
        },
        {
          name: "원화연",
          position: ["보컬", "센터"],
          birthYear: 2005,
          personality: ["MainVocal", "Calm", "Graceful"],
        },
        {
          name: "태린",
          position: ["메인 댄서"],
          birthYear: 2006,
          personality: ["DanceLeader", "Energetic", "Bright"],
        },
        {
          name: "라희",
          position: ["올라운더"],
          birthYear: 2007,
          personality: ["AllRounder", "Adaptable", "Friendly"],
        },
        {
          name: "뮤",
          position: ["리드 보컬", "댄서"],
          birthYear: 2008,
          personality: ["LeadVocal", "DanceSkill", "Charismatic"],
        },
        {
          name: "사샤",
          position: ["메인 보컬", "막내"],
          birthYear: 2009,
          personality: ["Youngest", "StrongVoice", "BrightEnergy"],
        },
      ],
    },
    {
      name: "Stray Kids",
      gender: "male",
      agency: "JYP 엔터테인먼트",
      members: [
        {
          name: "방찬",
          position: ["리더", "프로듀서", "리드 보컬", "리드 댄서", "래퍼"],
          birthYear: 1997,
          personality: ["리더십", "프로페셔널", "재능있음"],
        },
        {
          name: "리노",
          position: ["메인 댄서", "보컬", "서브 래퍼"],
          birthYear: 1998,
          personality: ["차분함", "시크함", "카리스마"],
        },
        {
          name: "창빈",
          position: ["메인 래퍼", "프로듀서", "보컬"],
          birthYear: 1999,
          personality: ["열정적", "강렬함", "자신감"],
        },
        {
          name: "현진",
          position: ["메인 댄서", "리드 래퍼", "서브 보컬", "비주얼"],
          birthYear: 2000,
          personality: ["예술적", "감성적", "우아함"],
        },
        {
          name: "한",
          position: ["메인 래퍼", "리드 보컬", "프로듀서"],
          birthYear: 2000,
          personality: ["재능있음", "긍정적", "활발함"],
        },
        {
          name: "필릭스",
          position: ["리드 댄서", "리드 래퍼", "서브 보컬"],
          birthYear: 2000,
          personality: ["밝음", "친근함", "카리스마"],
        },
        {
          name: "승민",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["차분함", "섬세함", "프로페셔널"],
        },
        {
          name: "아이엔",
          position: ["보컬", "막내"],
          birthYear: 2001,
          personality: ["귀여움", "활발함", "재능있음"],
        },
      ],
    },
    {
      name: "ATEEZ",
      gender: "male",
      agency: "KQ 엔터테인먼트",
      members: [
        {
          name: "홍중",
          position: ["리더", "래퍼", "작곡가"],
          birthYear: 1998,
          personality: ["Visionary", "Leader", "Creative"],
        },
        {
          name: "성화",
          position: ["보컬", "비주얼"],
          birthYear: 1998,
          personality: ["Gentle", "VisualImpact", "Reliable"],
        },
        {
          name: "윤호",
          position: ["메인 댄서", "보컬"],
          birthYear: 1999,
          personality: ["Energetic", "TallPresence", "Friendly"],
        },
        {
          name: "여상",
          position: ["리드 댄서", "보컬", "비주얼"],
          birthYear: 1999,
          personality: ["Stylish", "Calm", "Cool"],
        },
        {
          name: "산",
          position: ["리드 보컬", "메인 댄서"],
          birthYear: 1999,
          personality: ["Expressive", "DynamicPerformer", "Warm"],
        },
        {
          name: "민기",
          position: ["메인 래퍼", "퍼포머"],
          birthYear: 1999,
          personality: ["PowerfulRap", "Intensity", "Introspective"],
        },
        {
          name: "우영",
          position: ["메인 댄서", "보컬", "퍼포머"],
          birthYear: 1999,
          personality: ["AllRounder", "Charismatic", "Fun"],
        },
        {
          name: "종호",
          position: ["메인 보컬", "막내"],
          birthYear: 2000,
          personality: ["Youngest", "StrongVoice", "BrightFuture"],
        },
      ],
    },
    {
      name: "LOONA",
      gender: "female",
      agency: "블록베리 크리에이티브",
      members: [
        {
          name: "희진",
          position: ["댄서", "보컬", "비주얼"],
          birthYear: 2000,
          personality: ["InnocentCharm", "Bright", "Energetic"],
        },
        {
          name: "현진",
          position: ["댄서", "보컬"],
          birthYear: 2000,
          personality: ["Joker", "Playful", "Versatile"],
        },
        {
          name: "하슬",
          position: ["리더", "보컬"],
          birthYear: 1997,
          personality: ["MomFigure", "Elegant", "Strong"],
        },
        {
          name: "여진",
          position: ["보컬", "막내"],
          birthYear: 2002,
          personality: ["Youngest", "Lively", "Sweet"],
        },
        {
          name: "비비",
          position: ["보컬"],
          birthYear: 1996,
          personality: ["SoftVoice", "Calm", "Mature"],
        },
        {
          name: "김립",
          position: ["메인 보컬", "댄서"],
          birthYear: 1999,
          personality: ["PowerVocals", "Charm", "AllRounder"],
        },
        {
          name: "진솔",
          position: ["메인 래퍼", "보컬"],
          birthYear: 1997,
          personality: ["CoolRap", "Stylish", "Independent"],
        },
        {
          name: "최리",
          position: ["래퍼", "댄서", "보컬"],
          birthYear: 2001,
          personality: ["BrightEnergy", "Versatile", "Charismatic"],
        },
        {
          name: "이브",
          position: ["보컬", "댄서"],
          birthYear: 1997,
          personality: ["Graceful", "LeaderMode", "Sincere"],
        },
        {
          name: "츄",
          position: ["메인 보컬", "그룹 얼굴"],
          birthYear: 1999,
          personality: ["Cheerful", "Aegyo", "Friendly"],
        },
        {
          name: "고원",
          position: ["래퍼", "댄서", "보컬"],
          birthYear: 2000,
          personality: ["Unique", "Stylish", "Bright"],
        },
        {
          name: "올리비아 혜",
          position: ["리드 래퍼", "댄서", "보컬"],
          birthYear: 2001,
          personality: ["Cool", "Fierce", "Confident"],
        },
      ],
    },
    {
      name: "THE BOYZ",
      gender: "male",
      agency: "IST 엔터테인먼트",
      members: [
        {
          name: "상연",
          position: ["리더", "메인 보컬"],
          birthYear: 1995,
          personality: ["Leader", "StrongVoice", "Charismatic"],
        },
        {
          name: "제이콥",
          position: ["리드 보컬"],
          birthYear: 1997,
          personality: ["Soulful", "Warm", "Reliable"],
        },
        {
          name: "영훈",
          position: ["보컬", "비주얼"],
          birthYear: 1998,
          personality: ["Visual", "Gentle", "AllRounder"],
        },
        {
          name: "현재",
          position: ["리드 보컬", "리드 댄서", "비주얼"],
          birthYear: 1999,
          personality: ["DanceVocal", "Bright", "Stylish"],
        },
        {
          name: "주연",
          position: ["메인 댄서", "보컬", "비주얼"],
          birthYear: 1999,
          personality: ["Performance", "Energetic", "Confident"],
        },
        {
          name: "케빈",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["PowerVocals", "Charming", "Gentle"],
        },
        {
          name: "뉴",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["BrightVoice", "Youthful", "Friendly"],
        },
        {
          name: "큐",
          position: ["메인 댄서", "보컬"],
          birthYear: 2001,
          personality: ["DanceLeader", "Rhythmic", "Warm"],
        },
        {
          name: "주학년",
          position: ["리드 댄서", "래퍼", "보컬"],
          birthYear: 2001,
          personality: ["Versatile", "StrongRap", "Dynamic"],
        },
        {
          name: "선우",
          position: ["메인 래퍼"],
          birthYear: 2001,
          personality: ["RapMaster", "Confident", "Cool"],
        },
        {
          name: "에릭",
          position: ["리드 댄서", "리드 래퍼", "막내"],
          birthYear: 2003,
          personality: ["Youngest", "Energetic", "BrightFuture"],
        },
        {
          name: "활",
          position: ["리드 댄서", "보컬", "래퍼"],
          birthYear: 2003,
          personality: ["DanceRap", "StrongPresence", "Passionate"],
        },
      ],
    },
    {
      name: "Golden Child",
      gender: "male",
      agency: "울림 엔터테인먼트",
      members: [
        {
          name: "대열",
          position: ["리더", "리드 댄서", "보컬"],
          birthYear: 1996,
          personality: ["Leader", "Steady", "Protective"],
        },
        {
          name: "와이",
          position: ["메인 보컬", "리드 댄서"],
          birthYear: 1996,
          personality: ["PowerVocals", "DanceSkill", "AllRounder"],
        },
        {
          name: "장준",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 1997,
          personality: ["RapSkill", "DanceCharm", "Friendly"],
        },
        {
          name: "태그",
          position: ["메인 래퍼", "보컬"],
          birthYear: 1998,
          personality: ["SharpRap", "Dynamic", "Cool"],
        },
        {
          name: "승민",
          position: ["리드 보컬"],
          birthYear: 1999,
          personality: ["ClearVoice", "Bright", "Youthful"],
        },
        {
          name: "재현",
          position: ["서브 보컬"],
          birthYear: 1999,
          personality: ["WarmVoice", "Gentle", "Reliable"],
        },
        {
          name: "동현",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 2000,
          personality: ["DanceLine", "SweetVoice", "Friendly"],
        },
        {
          name: "주찬",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["StrongVoice", "Passionate", "Bright"],
        },
        {
          name: "지범",
          position: ["리드 보컬"],
          birthYear: 2001,
          personality: ["RisingVocal", "Gentle", "Stylish"],
        },
        {
          name: "보민",
          position: ["리드 댄서", "서브 보컬", "막내", "비주얼"],
          birthYear: 2001,
          personality: ["Youngest", "Visual", "Energetic"],
        },
      ],
    },
    {
      name: "Weki Meki",
      gender: "female",
      agency: "판타지오",
      members: [
        {
          name: "수연",
          position: ["리더", "메인 보컬"],
          birthYear: 1998,
          personality: ["Leader", "StrongVocals", "Confident"],
        },
        {
          name: "엘리",
          position: ["메인 보컬"],
          birthYear: 1999,
          personality: ["PowerVoices", "Bright", "Cheerful"],
        },
        {
          name: "유정",
          position: ["메인 래퍼", "메인 댄서", "리드 보컬"],
          birthYear: 2000,
          personality: ["DanceRapHybrid", "Energetic", "Versatile"],
        },
        {
          name: "도연",
          position: ["리드 보컬", "리드 댄서", "비주얼", "센터"],
          birthYear: 2001,
          personality: ["Center", "Visual", "Performance"],
        },
        {
          name: "세이",
          position: ["리드 보컬"],
          birthYear: 2002,
          personality: ["BrightVoice", "Youthful", "Friendly"],
        },
        {
          name: "루아",
          position: ["메인 댄서", "서브 보컬", "래퍼"],
          birthYear: 2002,
          personality: ["DanceLine", "RapSkill", "Fresh"],
        },
        {
          name: "리나",
          position: ["리드 래퍼", "서브 보컬", "비주얼"],
          birthYear: 2003,
          personality: ["VisualRapper", "Confident", "Stylish"],
        },
        {
          name: "루시",
          position: ["리드 래퍼", "리드 댄서", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Dynamic", "BrightFuture"],
        },
      ],
    },
    {
      name: "ONF",
      gender: "male",
      agency: "WM 엔터테인먼트",
      members: [
        {
          name: "효진",
          position: ["리더(ON팀)", "메인 보컬"],
          birthYear: 1994,
          personality: ["Leader", "Stable", "WarmVoice"],
        },
        {
          name: "이션",
          position: ["리드 보컬"],
          birthYear: 1996,
          personality: ["Reliable", "Bright", "SmoothVoice"],
        },
        {
          name: "제이어스",
          position: ["리더(OFF팀)", "메인 댄서", "리드 보컬"],
          birthYear: 1995,
          personality: ["Energetic", "DanceLeader", "Friendly"],
        },
        {
          name: "와이엇",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 1995,
          personality: ["DeepVoice", "Charismatic", "Cool"],
        },
        {
          name: "엠케이",
          position: ["메인 보컬"],
          birthYear: 1995,
          personality: ["UniqueTone", "Cheerful", "Creative"],
        },
        {
          name: "유",
          position: ["메인 댄서", "보컬", "막내"],
          birthYear: 1999,
          personality: ["Youngest", "DanceKing", "Positive"],
        },
        {
          name: "라운",
          position: ["리드 댄서", "보컬"],
          birthYear: 1995,
          personality: ["AllRounder", "Charming", "Gentle"],
        },
      ],
    },
    {
      name: "Dreamcatcher",
      gender: "female",
      agency: "드림캐쳐 컴퍼니",
      members: [
        {
          name: "지유",
          position: ["리더", "리드 댄서", "보컬", "비주얼"],
          birthYear: 1994,
          personality: ["Leader", "Elegant", "Reliable"],
        },
        {
          name: "수아",
          position: ["메인 댄서", "리드 래퍼", "보컬"],
          birthYear: 1994,
          personality: ["PerformanceQueen", "Energetic", "Fun"],
        },
        {
          name: "시연",
          position: ["메인 보컬"],
          birthYear: 1995,
          personality: ["PowerVocal", "Emotional", "Strong"],
        },
        {
          name: "한동",
          position: ["보컬"],
          birthYear: 1996,
          personality: ["SoftVoice", "Gentle", "Elegant"],
        },
        {
          name: "유현",
          position: ["리드 보컬"],
          birthYear: 1997,
          personality: ["Bright", "Sweet", "Playful"],
        },
        {
          name: "다미",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 1997,
          personality: ["CoolRapper", "Calm", "Independent"],
        },
        {
          name: "가현",
          position: ["리드 래퍼", "서브 보컬", "막내"],
          birthYear: 1999,
          personality: ["Youngest", "Confident", "Cute"],
        },
      ],
    },
    {
      name: "fromis_9",
      gender: "female",
      agency: "오프더레코드 엔터테인먼트",
      members: [
        {
          name: "새롬",
          position: ["리더", "리드 댄서", "보컬", "비주얼"],
          birthYear: 1997,
          personality: ["Leader", "Graceful", "Reliable"],
        },
        {
          name: "하영",
          position: ["리드 보컬", "리드 댄서"],
          birthYear: 1997,
          personality: ["Kind", "Warm", "Positive"],
        },
        {
          name: "규리",
          position: ["리드 보컬", "비주얼"],
          birthYear: 1997,
          personality: ["Gentle", "Charming", "Calm"],
        },
        {
          name: "지원",
          position: ["메인 보컬"],
          birthYear: 1998,
          personality: ["PowerVoice", "Bright", "Energetic"],
        },
        {
          name: "지선",
          position: ["리드 보컬", "리드 댄서", "센터"],
          birthYear: 1998,
          personality: ["Center", "Lively", "Charming"],
        },
        {
          name: "서연",
          position: ["메인 래퍼", "보컬", "메인 댄서"],
          birthYear: 2000,
          personality: ["Performance", "Charisma", "Creative"],
        },
        {
          name: "채영",
          position: ["메인 래퍼", "메인 댄서", "보컬"],
          birthYear: 2000,
          personality: ["DanceRap", "Fun", "Expressive"],
        },
        {
          name: "나경",
          position: ["리드 래퍼", "서브 보컬", "비주얼"],
          birthYear: 2000,
          personality: ["Elegant", "Visual", "Chic"],
        },
        {
          name: "지헌",
          position: ["리드 보컬", "막내"],
          birthYear: 2003,
          personality: ["Youngest", "Cute", "Bright"],
        },
      ],
    },
    {
      name: "NATURE",
      gender: "female",
      agency: "n.CH 엔터테인먼트",
      members: [
        {
          name: "루",
          position: ["리더", "메인 보컬"],
          birthYear: 1997,
          personality: ["Leader", "StrongVocal", "Warm"],
        },
        {
          name: "새봄",
          position: ["리드 래퍼", "보컬"],
          birthYear: 1999,
          personality: ["Energetic", "Versatile", "Charming"],
        },
        {
          name: "오로라",
          position: ["메인 댄서", "보컬"],
          birthYear: 1997,
          personality: ["Performance", "Bright", "Fun"],
        },
        {
          name: "채빈",
          position: ["메인 보컬"],
          birthYear: 1999,
          personality: ["SoftVoice", "Positive", "Friendly"],
        },
        {
          name: "하루",
          position: ["메인 댄서", "보컬"],
          birthYear: 2000,
          personality: ["DanceLine", "Bright", "Cute"],
        },
        {
          name: "로하",
          position: ["메인 보컬"],
          birthYear: 2001,
          personality: ["Pure", "Emotional", "Calm"],
        },
        {
          name: "유채",
          position: ["리드 댄서", "보컬", "비주얼"],
          birthYear: 2002,
          personality: ["Visual", "Gentle", "Warm"],
        },
        {
          name: "선샤인",
          position: ["리드 보컬"],
          birthYear: 2002,
          personality: ["Bright", "Cheerful", "Optimistic"],
        },
        {
          name: "소희",
          position: ["보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Playful", "Sweet"],
        },
      ],
    },
    {
      name: "D-CRUNCH",
      gender: "male",
      agency: "올에스 컴퍼니",
      members: [
        {
          name: "오브이",
          position: ["리더", "메인 래퍼"],
          birthYear: 1995,
          personality: ["Leader", "Cool", "Powerful"],
        },
        {
          name: "현욱",
          position: ["메인 보컬"],
          birthYear: 1996,
          personality: ["StrongVoice", "Reliable", "Calm"],
        },
        {
          name: "현호",
          position: ["리드 보컬"],
          birthYear: 1998,
          personality: ["WarmTone", "Gentle", "Bright"],
        },
        {
          name: "현오",
          position: ["보컬"],
          birthYear: 1999,
          personality: ["Cheerful", "Soft", "Friendly"],
        },
        {
          name: "현우",
          position: ["서브 보컬"],
          birthYear: 1999,
          personality: ["Bright", "Supportive", "TeamPlayer"],
        },
        {
          name: "민혁",
          position: ["서브 래퍼"],
          birthYear: 2000,
          personality: ["YoungEnergy", "Versatile", "Energetic"],
        },
        {
          name: "찬영",
          position: ["메인 댄서", "리드 래퍼"],
          birthYear: 2000,
          personality: ["DanceLeader", "RapLine", "Charismatic"],
        },
        {
          name: "정승",
          position: ["리드 보컬"],
          birthYear: 2001,
          personality: ["Gentle", "Bright", "Emotional"],
        },
        {
          name: "딜런",
          position: ["래퍼", "막내"],
          birthYear: 2002,
          personality: ["Youngest", "Fun", "Stylish"],
        },
      ],
    },
    {
      name: "DreamNote",
      gender: "female",
      agency: "아이미 코리아",
      members: [
        {
          name: "수민",
          position: ["리더", "리드 보컬"],
          birthYear: 2001,
          personality: ["Leader", "Calm", "Kind"],
        },
        {
          name: "은조",
          position: ["리드 댄서", "보컬"],
          birthYear: 2002,
          personality: ["DanceLine", "Cheerful", "Sweet"],
        },
        {
          name: "라라",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["StrongVocal", "Bright", "Positive"],
        },
        {
          name: "미소",
          position: ["메인 댄서", "리드 래퍼"],
          birthYear: 1999,
          personality: ["Performance", "Fun", "Energetic"],
        },
        {
          name: "유이",
          position: ["리드 보컬", "비주얼"],
          birthYear: 2004,
          personality: ["Visual", "Bright", "Friendly"],
        },
        {
          name: "보니",
          position: ["리드 보컬"],
          birthYear: 2001,
          personality: ["Cheerful", "Gentle", "AllRounder"],
        },
        {
          name: "하빈",
          position: ["메인 댄서", "래퍼"],
          birthYear: 2002,
          personality: ["DanceLine", "Cool", "Active"],
        },
        {
          name: "한별",
          position: ["보컬", "막내"],
          birthYear: 2004,
          personality: ["Youngest", "Playful", "Bright"],
        },
      ],
    },
    {
      name: "IZ*ONE",
      gender: "female",
      agency: "오프더레코드 엔터테인먼트",
      members: [
        {
          name: "은비",
          position: ["리더", "리드 보컬", "리드 댄서"],
          birthYear: 1995,
          personality: ["Leader", "Reliable", "Graceful"],
        },
        {
          name: "사쿠라",
          position: ["서브 보컬", "비주얼"],
          birthYear: 1998,
          personality: ["Elegant", "Charming", "Calm"],
        },
        {
          name: "혜원",
          position: ["리드 래퍼", "서브 보컬"],
          birthYear: 1999,
          personality: ["Cool", "Stylish", "Quiet"],
        },
        {
          name: "유리",
          position: ["메인 보컬"],
          birthYear: 2001,
          personality: ["StrongVocal", "Bright", "Sincere"],
        },
        {
          name: "예나",
          position: ["메인 래퍼", "리드 댄서", "보컬"],
          birthYear: 1999,
          personality: ["Energetic", "Fun", "Versatile"],
        },
        {
          name: "채연",
          position: ["메인 댄서", "리드 보컬", "리드 래퍼"],
          birthYear: 2000,
          personality: ["DanceQueen", "Warm", "Focused"],
        },
        {
          name: "민주",
          position: ["리드 래퍼", "서브 보컬", "비주얼"],
          birthYear: 2001,
          personality: ["Bright", "Playful", "Charming"],
        },
        {
          name: "나코",
          position: ["서브 보컬"],
          birthYear: 2001,
          personality: ["Cute", "Positive", "Gentle"],
        },
        {
          name: "히토미",
          position: ["서브 보컬", "리드 댄서"],
          birthYear: 2001,
          personality: ["Cheerful", "Hardworking", "Sweet"],
        },
        {
          name: "유진",
          position: ["리드 보컬", "리드 댄서", "센터"],
          birthYear: 2003,
          personality: ["LeaderPotential", "Energetic", "Bright"],
        },
        {
          name: "원영",
          position: ["리드 댄서", "서브 보컬", "비주얼", "막내"],
          birthYear: 2004,
          personality: ["Youngest", "Visual", "Elegant"],
        },
        {
          name: "채원",
          position: ["리드 보컬"],
          birthYear: 2000,
          personality: ["Gentle", "BrightVoice", "Warm"],
        },
      ],
    },
    {
      name: "PRISTIN",
      gender: "female",
      agency: "플레디스 엔터테인먼트",
      members: [
        {
          name: "나영",
          position: ["리더", "메인 래퍼", "리드 댄서"],
          birthYear: 1995,
          personality: ["Leader", "Confident", "Stylish"],
        },
        {
          name: "로아",
          position: ["리드 보컬"],
          birthYear: 1997,
          personality: ["Gentle", "Elegant", "Charming"],
        },
        {
          name: "유하",
          position: ["리드 보컬"],
          birthYear: 1997,
          personality: ["SoftVoice", "Sweet", "Positive"],
        },
        {
          name: "은우",
          position: ["리드 보컬"],
          birthYear: 1998,
          personality: ["Bright", "Cheerful", "Kind"],
        },
        {
          name: "레나",
          position: ["메인 래퍼", "리드 보컬"],
          birthYear: 1998,
          personality: ["RapQueen", "Dynamic", "Cool"],
        },
        {
          name: "결경",
          position: ["메인 댄서", "서브 보컬", "비주얼"],
          birthYear: 1999,
          personality: ["Visual", "Graceful", "Charismatic"],
        },
        {
          name: "예하나",
          position: ["메인 보컬"],
          birthYear: 1999,
          personality: ["PowerVocal", "Calm", "Kind"],
        },
        {
          name: "성연",
          position: ["메인 보컬", "메인 프로듀서"],
          birthYear: 1999,
          personality: ["Producer", "Creative", "Strong"],
        },
        {
          name: "시연",
          position: ["리드 래퍼", "리드 보컬"],
          birthYear: 2000,
          personality: ["Versatile", "Bright", "Friendly"],
        },
        {
          name: "카일라",
          position: ["리드 래퍼", "서브 보컬", "막내"],
          birthYear: 2001,
          personality: ["Youngest", "Cute", "Charming"],
        },
      ],
    },
    {
      name: "ELRIS",
      gender: "female",
      agency: "휴니스 엔터테인먼트",
      members: [
        {
          name: "벨라",
          position: ["리더", "메인 래퍼", "서브 보컬"],
          birthYear: 1999,
          personality: ["Leader", "Creative", "Strong"],
        },
        {
          name: "혜성",
          position: ["리드 보컬", "메인 댄서"],
          birthYear: 2000,
          personality: ["Bright", "Energetic", "Friendly"],
        },
        {
          name: "유경",
          position: ["메인 댄서", "서브 보컬"],
          birthYear: 1999,
          personality: ["Charming", "DanceLine", "Positive"],
        },
        {
          name: "소희",
          position: ["메인 보컬", "그룹 얼굴"],
          birthYear: 1999,
          personality: ["Visual", "Kind", "SoftVoice"],
        },
        {
          name: "가린",
          position: ["서브 보컬", "막내"],
          birthYear: 2002,
          personality: ["Youngest", "Cute", "Cheerful"],
        },
      ],
    },
    {
      name: "IN2IT",
      gender: "male",
      agency: "MMO 엔터테인먼트",
      members: [
        {
          name: "지안",
          position: ["리더", "메인 보컬"],
          birthYear: 1991,
          personality: ["Leader", "Reliable", "Calm"],
        },
        {
          name: "연태",
          position: ["메인 보컬"],
          birthYear: 1992,
          personality: ["StrongVoice", "Sincere", "Warm"],
        },
        {
          name: "인표",
          position: ["리드 댄서", "보컬"],
          birthYear: 1994,
          personality: ["DanceLine", "Gentle", "Friendly"],
        },
        {
          name: "아이작",
          position: ["보컬"],
          birthYear: 1994,
          personality: ["GlobalMember", "Positive", "Bright"],
        },
        {
          name: "인호",
          position: ["리드 보컬"],
          birthYear: 1995,
          personality: ["SmoothVoice", "Calm", "Reliable"],
        },
        {
          name: "현욱",
          position: ["메인 댄서", "래퍼"],
          birthYear: 1996,
          personality: ["DanceLeader", "Charismatic", "Confident"],
        },
        {
          name: "진섭",
          position: ["메인 보컬"],
          birthYear: 1995,
          personality: ["StrongTone", "Kind", "Dedicated"],
        },
        {
          name: "성현",
          position: ["메인 댄서", "막내"],
          birthYear: 1996,
          personality: ["Youngest", "Bright", "Energetic"],
        },
      ],
    },
    {
      name: "The Rose",
      gender: "male",
      agency: "J&Star 컴퍼니",
      members: [
        {
          name: "우성",
          position: ["리더", "메인 보컬", "일렉 기타"],
          birthYear: 1993,
          personality: ["Leader", "Soulful", "Creative"],
        },
        {
          name: "도준",
          position: ["키보드", "어쿠스틱 기타", "메인 보컬"],
          birthYear: 1993,
          personality: ["WarmVoice", "Gentle", "Passionate"],
        },
        {
          name: "하준",
          position: ["드러머", "서브 보컬", "래퍼"],
          birthYear: 1994,
          personality: ["Energetic", "Cool", "Reliable"],
        },
        {
          name: "재형",
          position: ["베이시스트", "서브 보컬", "비주얼", "막내"],
          birthYear: 1994,
          personality: ["Youngest", "Stylish", "Charming"],
        },
      ],
    },
    {
      name: "ITZY",
      gender: "female",
      agency: "JYP 엔터테인먼트",
      members: [
        {
          name: "예지",
          position: ["리더", "메인 댄서", "리드 보컬", "서브 래퍼"],
          birthYear: 2000,
          personality: ["Leader", "Charismatic", "Powerful"],
        },
        {
          name: "리아",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["SoftVoice", "Elegant", "Warm"],
        },
        {
          name: "류진",
          position: ["메인 래퍼", "리드 댄���", "센터", "서브 보컬"],
          birthYear: 2001,
          personality: ["Cool", "Confident", "Stylish"],
        },
        {
          name: "채령",
          position: ["메인 댄서", "서브 보컬", "서브 래퍼"],
          birthYear: 2001,
          personality: ["DanceQueen", "Bright", "Kind"],
        },
        {
          name: "유나",
          position: ["리드 래퍼", "리드 댄서", "비주얼", "막내"],
          birthYear: 2003,
          personality: ["Youngest", "Energetic", "Charming"],
        },
      ],
    },
    {
      name: "TXT (Tomorrow X Together)",
      gender: "male",
      agency: "빅히트 뮤직",
      members: [
        {
          name: "수빈",
          position: ["리더", "보컬", "래퍼"],
          birthYear: 2000,
          personality: ["Leader", "Gentle", "Reliable"],
        },
        {
          name: "연준",
          position: ["래퍼", "댄서", "보컬"],
          birthYear: 1999,
          personality: ["PerformanceKing", "Charismatic", "Confident"],
        },
        {
          name: "범규",
          position: ["보컬", "댄서", "래퍼", "센터", "비주얼"],
          birthYear: 2001,
          personality: ["Stylish", "Playful", "Expressive"],
        },
        {
          name: "태현",
          position: ["메인 보컬", "댄서"],
          birthYear: 2002,
          personality: ["StrongVocal", "Smart", "Focused"],
        },
        {
          name: "휴닝카이",
          position: ["리드 보컬", "댄서", "막내"],
          birthYear: 2002,
          personality: ["Youngest", "Bright", "Lovable"],
        },
      ],
    },
    {
      name: "TREASURE",
      gender: "male",
      agency: "YG 엔터테인먼트",
      members: [
        {
          name: "최현석",
          position: ["리더", "메인 래퍼", "메인 댄서"],
          birthYear: 1999,
          personality: ["Leader", "Powerful", "Charismatic"],
        },
        {
          name: "지훈",
          position: ["리더", "리드 보컬", "리드 댄서"],
          birthYear: 2000,
          personality: ["Bright", "Reliable", "Friendly"],
        },
        {
          name: "요시",
          position: ["리드 래퍼", "보컬"],
          birthYear: 2000,
          personality: ["Cool", "Artistic", "Calm"],
        },
        {
          name: "준규",
          position: ["리드 보컬", "비주얼"],
          birthYear: 2000,
          personality: ["Visual", "Charming", "Warm"],
        },
        {
          name: "마시호",
          position: ["리드 댄서", "리드 보컬", "비주얼"],
          birthYear: 2001,
          personality: ["Bright", "Energetic", "Cute"],
        },
        {
          name: "윤재혁",
          position: ["서브 보컬"],
          birthYear: 2001,
          personality: ["SoftVoice", "Gentle", "Friendly"],
        },
        {
          name: "아사히",
          position: ["리드 보컬", "비주얼"],
          birthYear: 2001,
          personality: ["Artistic", "Calm", "Creative"],
        },
        {
          name: "방예담",
          position: ["메인 보컬"],
          birthYear: 2002,
          personality: ["PowerVoice", "Passionate", "Emotional"],
        },
        {
          name: "도영",
          position: ["메인 댄서", "보컬"],
          birthYear: 2003,
          personality: ["DanceLine", "Fun", "Kind"],
        },
        {
          name: "하루토",
          position: ["메인 래퍼", "비주얼"],
          birthYear: 2004,
          personality: ["Young", "Cool", "Stylish"],
        },
        {
          name: "박정우",
          position: ["메인 보컬"],
          birthYear: 2004,
          personality: ["StrongVocal", "Gentle", "Warm"],
        },
        {
          name: "소정환",
          position: ["리드 댄서", "서브 보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Bright", "Cheerful"],
        },
      ],
    },
    {
      name: "CRAVITY",
      gender: "male",
      agency: "스타쉽 엔터테인먼트",
      members: [
        {
          name: "세림",
          position: ["리더", "메인 래퍼", "비주얼"],
          birthYear: 1999,
          personality: ["Leader", "Calm", "Chic"],
        },
        {
          name: "앨런",
          position: ["메인 댄서", "리드 래퍼"],
          birthYear: 1999,
          personality: ["Performance", "Gentle", "Global"],
        },
        {
          name: "정모",
          position: ["리드 보컬", "비주얼"],
          birthYear: 2000,
          personality: ["Visual", "SweetVoice", "Kind"],
        },
        {
          name: "우빈",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["StrongVocal", "Reliable", "Bright"],
        },
        {
          name: "원진",
          position: ["리드 보컬", "리드 댄서"],
          birthYear: 2001,
          personality: ["Energetic", "Friendly", "Positive"],
        },
        {
          name: "민희",
          position: ["리드 보컬", "비주얼"],
          birthYear: 2002,
          personality: ["Visual", "Gentle", "SoftSpoken"],
        },
        {
          name: "형준",
          position: ["메인 댄서", "보컬"],
          birthYear: 2002,
          personality: ["Performance", "Bright", "Fun"],
        },
        {
          name: "태영",
          position: ["리드 댄서", "보컬"],
          birthYear: 2003,
          personality: ["DanceLine", "Charming", "Warm"],
        },
        {
          name: "성민",
          position: ["리드 보컬", "막내"],
          birthYear: 2003,
          personality: ["Youngest", "Bright", "Friendly"],
        },
      ],
    },
    {
      name: "MCND",
      gender: "male",
      agency: "티오피미디어",
      members: [
        {
          name: "캐슬제이",
          position: ["리더", "메인 래퍼"],
          birthYear: 1999,
          personality: ["Leader", "Powerful", "Confident"],
        },
        {
          name: "빅",
          position: ["메인 댄서", "리드 래퍼"],
          birthYear: 2001,
          personality: ["DanceLine", "Strong", "Cool"],
        },
        {
          name: "민재",
          position: ["메인 보컬"],
          birthYear: 2003,
          personality: ["Bright", "Passionate", "Friendly"],
        },
        {
          name: "휘준",
          position: ["메인 보컬"],
          birthYear: 2003,
          personality: ["Warm", "Charming", "Cheerful"],
        },
        {
          name: "윈",
          position: ["리드 래퍼", "막내"],
          birthYear: 2004,
          personality: ["Youngest", "Energetic", "Stylish"],
        },
      ],
    },
    {
      name: "cignature",
      gender: "female",
      agency: "J9 엔터테인먼트",
      members: [
        {
          name: "채솔",
          position: ["리더", "리드 댄서", "보컬"],
          birthYear: 1998,
          personality: ["Leader", "Reliable", "Bright"],
        },
        {
          name: "지원",
          position: ["리드 보컬", "리드 래퍼"],
          birthYear: 2000,
          personality: ["Versatile", "Cool", "Friendly"],
        },
        {
          name: "셀린",
          position: ["리드 보컬"],
          birthYear: 2001,
          personality: ["SoftVoice", "Kind", "Gentle"],
        },
        {
          name: "클로이",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 2001,
          personality: ["Charming", "Stylish", "Bright"],
        },
        {
          name: "세미",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 2002,
          personality: ["DanceLine", "Energetic", "Positive"],
        },
        {
          name: "도희",
          position: ["리드 보컬"],
          birthYear: 2002,
          personality: ["Sweet", "Gentle", "Warm"],
        },
        {
          name: "벨",
          position: ["메인 보컬"],
          birthYear: 2004,
          personality: ["StrongVocal", "Bright", "YoungestEnergy"],
        },
      ],
    },
    {
      name: "STAYC",
      gender: "female",
      agency: "하이업 엔터테인먼트",
      members: [
        {
          name: "수민",
          position: ["리더", "리드 보컬", "리드 댄서", "래퍼"],
          birthYear: 2001,
          personality: ["Leader", "Reliable", "Bright"],
        },
        {
          name: "시은",
          position: ["메인 보컬"],
          birthYear: 2001,
          personality: ["PowerVocal", "Warm", "Cheerful"],
        },
        {
          name: "아이사",
          position: ["리드 보컬"],
          birthYear: 2002,
          personality: ["Elegant", "Calm", "Kind"],
        },
        {
          name: "세은",
          position: ["서브 보컬"],
          birthYear: 2003,
          personality: ["Sweet", "Pure", "Gentle"],
        },
        {
          name: "윤",
          position: ["리드 보컬", "리드 댄서"],
          birthYear: 2004,
          personality: ["Bright", "Playful", "Energetic"],
        },
        {
          name: "재이",
          position: ["메인 래퍼", "리드 보컬", "막내"],
          birthYear: 2004,
          personality: ["Youngest", "Chic", "Confident"],
        },
      ],
    },
    {
      name: "Weeekly",
      gender: "female",
      agency: "IST 엔터테인먼트",
      members: [
        {
          name: "수진",
          position: ["리더", "메인 댄서", "리드 보컬"],
          birthYear: 2001,
          personality: ["Leader", "Reliable", "Graceful"],
        },
        {
          name: "지윤",
          position: ["메인 래퍼", "리드 보컬"],
          birthYear: 2002,
          personality: ["Cool", "Creative", "Versatile"],
        },
        {
          name: "먼데이",
          position: ["메인 보컬", "메인 댄서"],
          birthYear: 2002,
          personality: ["StrongVocal", "Bright", "Hardworking"],
        },
        {
          name: "소은",
          position: ["메인 댄서", "리드 래퍼", "보컬"],
          birthYear: 2002,
          personality: ["Performance", "Energetic", "Fun"],
        },
        {
          name: "재희",
          position: ["리드 보컬", "서브 래퍼"],
          birthYear: 2004,
          personality: ["Gentle", "Kind", "Friendly"],
        },
        {
          name: "지한",
          position: ["리드 보컬", "비주얼", "그룹 얼굴"],
          birthYear: 2004,
          personality: ["Visual", "Bright", "Cheerful"],
        },
        {
          name: "조아",
          position: ["리드 래퍼", "서브 보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Playful", "Cute"],
        },
      ],
    },
    {
      name: "ENHYPEN",
      gender: "male",
      agency: "빌리프랩 (하이브 × CJ ENM)",
      members: [
        {
          name: "정원",
          position: ["리더", "리드 댄서", "리드 보컬", "래퍼"],
          birthYear: 2004,
          personality: ["Leader", "Calm", "Reliable"],
        },
        {
          name: "희승",
          position: ["메인 보컬", "센터", "댄서"],
          birthYear: 2001,
          personality: ["Talented", "Passionate", "Focused"],
        },
        {
          name: "제이",
          position: ["메인 래퍼", "리드 댄서", "보컬"],
          birthYear: 2002,
          personality: ["Charismatic", "Strong", "Cool"],
        },
        {
          name: "제이크",
          position: ["리드 래퍼", "보컬"],
          birthYear: 2002,
          personality: ["Gentle", "Warm", "GlobalCharm"],
        },
        {
          name: "성훈",
          position: ["리드 댄서", "보컬", "비주얼"],
          birthYear: 2002,
          personality: ["Visual", "Calm", "Elegant"],
        },
        {
          name: "선우",
          position: ["리드 보컬"],
          birthYear: 2003,
          personality: ["Bright", "Fun", "Cheerful"],
        },
        {
          name: "니키",
          position: ["메인 댄서", "서브 보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "DanceKing", "Energetic"],
        },
      ],
    },
    {
      name: "E'LAST",
      gender: "male",
      agency: "이 엔터테인먼트",
      members: [
        {
          name: "라노",
          position: ["리더", "메인 래퍼", "메인 댄서"],
          birthYear: 1998,
          personality: ["Leader", "Charismatic", "Passionate"],
        },
        {
          name: "최인",
          position: ["메인 보컬"],
          birthYear: 1999,
          personality: ["PowerVocal", "Gentle", "Focused"],
        },
        {
          name: "승엽",
          position: ["리드 보컬"],
          birthYear: 2000,
          personality: ["BrightVoice", "Kind", "Reliable"],
        },
        {
          name: "백결",
          position: ["보컬", "비주얼"],
          birthYear: 1999,
          personality: ["Visual", "Calm", "Graceful"],
        },
        {
          name: "로민",
          position: ["리드 보컬", "비주얼"],
          birthYear: 2001,
          personality: ["Charming", "Elegant", "Bright"],
        },
        {
          name: "원혁",
          position: ["메인 래퍼", "보컬"],
          birthYear: 2002,
          personality: ["Cool", "Creative", "Dynamic"],
        },
        {
          name: "원준",
          position: ["리드 래퍼", "보컬"],
          birthYear: 2002,
          personality: ["Energetic", "Friendly", "Fun"],
        },
        {
          name: "예준",
          position: ["리드 보컬", "막내"],
          birthYear: 2002,
          personality: ["Youngest", "Warm", "Cheerful"],
        },
      ],
    },
    {
      name: "DRIPPIN",
      gender: "male",
      agency: "울림 엔터테인먼트",
      members: [
        {
          name: "윤성",
          position: ["리더", "메인 댄서", "보컬"],
          birthYear: 2000,
          personality: ["Leader", "Reliable", "Calm"],
        },
        {
          name: "협",
          position: ["메인 보컬"],
          birthYear: 1999,
          personality: ["StrongVocal", "Bright", "Sincere"],
        },
        {
          name: "창욱",
          position: ["리드 보컬"],
          birthYear: 2002,
          personality: ["Gentle", "Kind", "Charming"],
        },
        {
          name: "동윤",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2002,
          personality: ["Cool", "Energetic", "Charismatic"],
        },
        {
          name: "민서",
          position: ["리드 보컬", "막내"],
          birthYear: 2002,
          personality: ["Youngest", "Bright", "Friendly"],
        },
        {
          name: "준호",
          position: ["리드 댄서", "보컬", "비주얼"],
          birthYear: 2002,
          personality: ["Visual", "Chic", "Graceful"],
        },
        {
          name: "알렉스",
          position: ["래퍼", "보컬", "막내(2019~2022 활동)"],
          birthYear: 2004,
          personality: ["Global", "Cheerful", "Youngest"],
        },
      ],
    },
    {
      name: "Secret Number",
      gender: "female",
      agency: "바인 엔터테인먼트",
      members: [
        {
          name: "레아",
          position: ["리더", "리드 보컬"],
          birthYear: 1995,
          personality: ["Leader", "Calm", "Graceful"],
        },
        {
          name: "디타",
          position: ["메인 댄서", "서브 보컬"],
          birthYear: 1996,
          personality: ["PerformanceQueen", "Bright", "Kind"],
        },
        {
          name: "진희",
          position: ["메인 래퍼", "리드 댄서", "서브 보컬"],
          birthYear: 1998,
          personality: ["Confident", "Energetic", "Cool"],
        },
        {
          name: "민지",
          position: ["메인 보컬"],
          birthYear: 1999,
          personality: ["PowerVocal", "Reliable", "Warm"],
        },
        {
          name: "수담",
          position: ["리드 댄서", "서브 보컬", "비주얼"],
          birthYear: 1999,
          personality: ["Visual", "Bright", "Charming"],
        },
        {
          name: "주",
          position: ["서브 래퍼", "서브 보컬"],
          birthYear: 2001,
          personality: ["Youthful", "Sweet", "Positive"],
        },
      ],
    },
    {
      name: "BDC (Boys Da Capo)",
      gender: "male",
      agency: "브랜뉴뮤직",
      members: [
        {
          name: "성준",
          position: ["리더", "메인 래퍼", "서브 보컬"],
          birthYear: 1996,
          personality: ["Leader", "Cool", "Confident"],
        },
        {
          name: "시훈",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 1999,
          personality: ["DanceLine", "Bright", "Cheerful"],
        },
        {
          name: "정환",
          position: ["메인 보컬", "막내"],
          birthYear: 2001,
          personality: ["Youngest", "SoftVoice", "Warm"],
        },
      ],
    },
    {
      name: "BOTOPASS",
      gender: "female",
      agency: "WKS ENE / JMG",
      members: [
        {
          name: "미희",
          position: ["리더", "메인 보컬"],
          birthYear: 1995,
          personality: ["Leader", "PowerVocal", "Reliable"],
        },
        {
          name: "서윤",
          position: ["리드 보컬"],
          birthYear: 1996,
          personality: ["SoftVoice", "Gentle", "Bright"],
        },
        {
          name: "리아",
          position: ["리드 래퍼", "보컬"],
          birthYear: 1997,
          personality: ["Cool", "Energetic", "Charismatic"],
        },
        {
          name: "시연",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 1998,
          personality: ["DanceLine", "Graceful", "Confident"],
        },
        {
          name: "하린",
          position: ["리드 댄서", "보컬"],
          birthYear: 1999,
          personality: ["Performance", "Bright", "Fun"],
        },
        {
          name: "지원",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 1999,
          personality: ["RapLine", "Stylish", "Chic"],
        },
        {
          name: "시안",
          position: ["메인 보컬"],
          birthYear: 2000,
          personality: ["StrongVocal", "Calm", "Elegant"],
        },
        {
          name: "아윤",
          position: ["보컬", "막내"],
          birthYear: 2001,
          personality: ["Youngest", "Cute", "Friendly"],
        },
      ],
    },
    {
      name: "LE SSERAFIM",
      gender: "female",
      agency: "쏘스뮤직 / 하이브",
      members: [
        {
          name: "채원",
          position: ["리더", "보컬", "댄서"],
          birthYear: 2000,
          personality: ["Leader", "Calm", "Graceful"],
        },
        {
          name: "사쿠라",
          position: ["서브 보컬", "서브 래퍼", "비주얼"],
          birthYear: 1998,
          personality: ["Elegant", "Global", "Charming"],
        },
        {
          name: "윤진",
          position: ["메인 보컬"],
          birthYear: 2001,
          personality: ["PowerVocal", "Confident", "Bright"],
        },
        {
          name: "카즈하",
          position: ["리드 래퍼", "리드 댄서", "서브 보컬"],
          birthYear: 2003,
          personality: ["Graceful", "Elegant", "Calm"],
        },
        {
          name: "은채",
          position: ["리드 댄서", "서브 보컬", "막내"],
          birthYear: 2006,
          personality: ["Youngest", "Energetic", "Bright"],
        },
      ],
    },
    {
      name: "NewJeans",
      gender: "female",
      agency: "어도어 (하이브)",
      members: [
        {
          name: "민지",
          position: ["리더", "리드 래퍼", "서브 보컬"],
          birthYear: 2004,
          personality: ["리더십", "차분함", "프로페셔널"],
        },
        {
          name: "하니",
          position: ["메인 보컬"],
          birthYear: 2004,
          personality: ["밝음", "친근함", "활발함"],
        },
        {
          name: "다니엘",
          position: ["리드 보컬", "리드 댄서"],
          birthYear: 2005,
          personality: ["밝음", "긍정적", "에너지 넘침"],
        },
        {
          name: "해린",
          position: ["메인 보컬", "서브 래퍼"],
          birthYear: 2006,
          personality: ["차분함", "우아함", "고양이상"],
        },
        {
          name: "혜인",
          position: ["리드 보컬", "막내"],
          birthYear: 2008,
          personality: ["귀여움", "활발함", "재능있음"],
        },
      ],
    },
    {
      name: "Kep1er",
      gender: "female",
      agency: "웨이크원 엔터테인먼트 / 스윙 엔터테인먼트",
      members: [
        {
          name: "유진",
          position: ["리더", "리드 댄서", "서브 보컬", "서브 래퍼"],
          birthYear: 1996,
          personality: ["Leader", "Graceful", "Reliable"],
        },
        {
          name: "마시로",
          position: ["공동 리더", "서브 보컬", "서브 래퍼"],
          birthYear: 1999,
          personality: ["Kind", "Gentle", "Organized"],
        },
        {
          name: "샤오팅",
          position: ["메인 댄서", "서브 보컬"],
          birthYear: 1999,
          personality: ["Elegant", "Calm", "Graceful"],
        },
        {
          name: "채현",
          position: ["메인 보컬"],
          birthYear: 2002,
          personality: ["PowerVocal", "Warm", "Friendly"],
        },
        {
          name: "다연",
          position: ["메인 댄서", "서브 보컬", "서브 래퍼"],
          birthYear: 2003,
          personality: ["Performance", "Energetic", "Positive"],
        },
        {
          name: "히카루",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2004,
          personality: ["Charismatic", "Cool", "Dynamic"],
        },
        {
          name: "휴닝 바히에",
          position: ["서브 보컬", "서브 래퍼"],
          birthYear: 2004,
          personality: ["Sweet", "Soft", "Gentle"],
        },
        {
          name: "영은",
          position: ["메인 댄서", "리드 래퍼", "서브 보컬"],
          birthYear: 2004,
          personality: ["Performance", "Bright", "Charming"],
        },
        {
          name: "예서",
          position: ["리드 댄서", "리드 보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Cute", "Energetic"],
        },
      ],
    },
    {
      name: "NMIXX",
      gender: "female",
      agency: "JYP 엔터테인먼트",
      members: [
        {
          name: "해원",
          position: ["리더", "메인 보컬"],
          birthYear: 2003,
          personality: ["Leader", "Reliable", "StrongVocal"],
        },
        {
          name: "릴리",
          position: ["메인 보컬"],
          birthYear: 2002,
          personality: ["Global", "Passionate", "Bright"],
        },
        {
          name: "설윤",
          position: ["보컬", "비주얼"],
          birthYear: 2004,
          personality: ["Visual", "Gentle", "Graceful"],
        },
        {
          name: "배이",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 2004,
          personality: ["Calm", "Elegant", "Charming"],
        },
        {
          name: "지우",
          position: ["메인 래퍼", "메인 댄서", "서브 보컬"],
          birthYear: 2005,
          personality: ["Charismatic", "Confident", "Stylish"],
        },
        {
          name: "규진",
          position: ["메인 댄서", "리드 래퍼", "막내"],
          birthYear: 2006,
          personality: ["Youngest", "Energetic", "Bright"],
        },
      ],
    },
    {
      name: "XG",
      gender: "female",
      agency: "XGALX",
      members: [
        {
          name: "주린",
          position: ["리더", "메인 래퍼", "리드 댄서"],
          birthYear: 2002,
          personality: ["Leader", "Powerful", "Charismatic"],
        },
        {
          name: "치사",
          position: ["메인 보컬"],
          birthYear: 2002,
          personality: ["SoftVoice", "Warm", "Gentle"],
        },
        {
          name: "하비",
          position: ["리드 래퍼", "리드 댄서"],
          birthYear: 2002,
          personality: ["Cool", "Confident", "Creative"],
        },
        {
          name: "히나타",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 2002,
          personality: ["Graceful", "Calm", "Bright"],
        },
        {
          name: "주리아",
          position: ["메인 보컬"],
          birthYear: 2004,
          personality: ["StrongVocal", "Kind", "Cheerful"],
        },
        {
          name: "마야",
          position: ["메인 래퍼", "리드 보컬"],
          birthYear: 2005,
          personality: ["Versatile", "Energetic", "Chic"],
        },
        {
          name: "코코나",
          position: ["메인 래퍼", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Bold", "Cool"],
        },
      ],
    },
    {
      name: "TNX",
      gender: "male",
      agency: "피네이션",
      members: [
        {
          name: "태훈",
          position: ["리더", "메인 보컬"],
          birthYear: 2000,
          personality: ["Leader", "Gentle", "Reliable"],
        },
        {
          name: "경준",
          position: ["리드 래퍼"],
          birthYear: 2003,
          personality: ["Cool", "Bright", "Friendly"],
        },
        {
          name: "현수",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 2003,
          personality: ["Performance", "Cheerful", "Charming"],
        },
        {
          name: "준혁",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2004,
          personality: ["Dynamic", "Strong", "Confident"],
        },
        {
          name: "휘",
          position: ["메인 보컬", "서브 래퍼"],
          birthYear: 2004,
          personality: ["Bright", "Warm", "Positive"],
        },
        {
          name: "성준",
          position: ["리드 래퍼", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Playful", "Energetic"],
        },
      ],
    },
    {
      name: "BAE173",
      gender: "male",
      agency: "포켓돌 스튜디오",
      members: [
        {
          name: "제이민",
          position: ["리더", "메인 래퍼"],
          birthYear: 1999,
          personality: ["Leader", "Confident", "Calm"],
        },
        {
          name: "한결",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 1999,
          personality: ["Bright", "Friendly", "Charming"],
        },
        {
          name: "유준",
          position: ["리드 래퍼", "보컬"],
          birthYear: 2000,
          personality: ["Cool", "Stylish", "Reliable"],
        },
        {
          name: "무진",
          position: ["메인 댄서", "서브 래퍼"],
          birthYear: 2000,
          personality: ["DanceLine", "Energetic", "Fun"],
        },
        {
          name: "준서",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 2001,
          personality: ["Gentle", "Kind", "Bright"],
        },
        {
          name: "영서",
          position: ["메인 보컬"],
          birthYear: 2001,
          personality: ["PowerVocal", "Warm", "Sincere"],
        },
        {
          name: "도하",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 2004,
          personality: ["Young", "Confident", "Stylish"],
        },
        {
          name: "빛",
          position: ["서브 래퍼", "보컬"],
          birthYear: 2004,
          personality: ["Bright", "Friendly", "Playful"],
        },
        {
          name: "도현",
          position: ["메인 래퍼", "막내"],
          birthYear: 2004,
          personality: ["Youngest", "Bold", "Energetic"],
        },
      ],
    },
    {
      name: "BOYNEXTDOOR",
      gender: "male",
      agency: "코즈 엔터테인먼트 (하이브)",
      members: [
        {
          name: "재현",
          position: ["리더", "보컬", "래퍼"],
          birthYear: 2003,
          personality: ["Leader", "Cool", "Calm"],
        },
        {
          name: "성호",
          position: ["메인 보컬"],
          birthYear: 2003,
          personality: ["Bright", "Warm", "Friendly"],
        },
        {
          name: "리우",
          position: ["메인 댄서", "보컬"],
          birthYear: 2003,
          personality: ["DanceLine", "Energetic", "Cheerful"],
        },
        {
          name: "태산",
          position: ["메인 래퍼", "보컬"],
          birthYear: 2004,
          personality: ["Charismatic", "Confident", "Stylish"],
        },
        {
          name: "리한",
          position: ["서브 보컬", "비주얼"],
          birthYear: 2004,
          personality: ["Visual", "Gentle", "Elegant"],
        },
        {
          name: "운학",
          position: ["리드 래퍼", "막내"],
          birthYear: 2006,
          personality: ["Youngest", "Playful", "Bright"],
        },
      ],
    },
    {
      name: "ZEROBASEONE (ZB1)",
      gender: "male",
      agency: "웨이크원 엔터테인먼트",
      members: [
        {
          name: "성한빈",
          position: ["리더", "메인 댄서", "리드 보컬"],
          birthYear: 2001,
          personality: ["Leader", "Elegant", "Reliable"],
        },
        {
          name: "김지웅",
          position: ["리드 보컬", "비주얼"],
          birthYear: 1998,
          personality: ["Cool", "Charming", "Calm"],
        },
        {
          name: "장하오",
          position: ["센터", "메인 보컬"],
          birthYear: 2000,
          personality: ["Gentle", "Focused", "Sincere"],
        },
        {
          name: "석매튜",
          position: ["리드 보컬"],
          birthYear: 2002,
          personality: ["Bright", "Energetic", "Friendly"],
        },
        {
          name: "김태래",
          position: ["메인 보컬"],
          birthYear: 2002,
          personality: ["Warm", "Kind", "Reliable"],
        },
        {
          name: "리키",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 2004,
          personality: ["Stylish", "Confident", "Calm"],
        },
        {
          name: "김규빈",
          position: ["메인 댄서", "서브 보컬", "비주얼"],
          birthYear: 2004,
          personality: ["Visual", "Charming", "Bright"],
        },
        {
          name: "박건욱",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2005,
          personality: ["Cool", "Dynamic", "Confident"],
        },
        {
          name: "한유진",
          position: ["리드 댄서", "서브 보컬", "막내"],
          birthYear: 2007,
          personality: ["Youngest", "Energetic", "Cheerful"],
        },
      ],
    },
    {
      name: "RIIZE",
      gender: "male",
      agency: "SM 엔터테인먼트",
      members: [
        {
          name: "쇼타로",
          position: ["메인 댄서", "리드 래퍼"],
          birthYear: 2000,
          personality: ["Performance", "Bright", "Kind"],
        },
        {
          name: "은석",
          position: ["리드 래퍼", "비주얼"],
          birthYear: 2001,
          personality: ["Visual", "Calm", "Gentle"],
        },
        {
          name: "성찬",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2000,
          personality: ["Charismatic", "Confident", "Cool"],
        },
        {
          name: "원빈",
          position: ["리드 래퍼", "리드 보컬"],
          birthYear: 2002,
          personality: ["Stylish", "SoftVoice", "Graceful"],
        },
        {
          name: "소희",
          position: ["메인 보컬"],
          birthYear: 2001,
          personality: ["PowerVocal", "Bright", "Warm"],
        },
        {
          name: "앤톤",
          position: ["리드 보컬", "막내"],
          birthYear: 2004,
          personality: ["Youngest", "Gentle", "Sweet"],
        },
      ],
    },
    {
      name: "KISS OF LIFE",
      gender: "female",
      agency: "에스투 엔터테인먼트",
      members: [
        {
          name: "줄리",
          position: ["리더", "메인 래퍼"],
          birthYear: 2000,
          personality: ["Leader", "Charismatic", "Bold"],
        },
        {
          name: "나띠",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 2002,
          personality: ["Performance", "Energetic", "Cheerful"],
        },
        {
          name: "벨",
          position: ["메인 보컬"],
          birthYear: 2004,
          personality: ["BrightVoice", "Kind", "Sincere"],
        },
        {
          name: "하늘",
          position: ["리드 보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "SoftVoice", "Friendly"],
        },
      ],
    },
    {
      name: "PLAVE",
      gender: "male",
      agency: "브이래스트",
      members: [
        {
          name: "예준",
          position: ["리더", "메인 보컬"],
          birthYear: 2002,
          personality: ["Leader", "Calm", "Warm"],
        },
        {
          name: "노아",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 2003,
          personality: ["Creative", "Confident", "Charming"],
        },
        {
          name: "밤비",
          position: ["메인 댄서", "보컬"],
          birthYear: 2003,
          personality: ["DanceLine", "Bright", "Playful"],
        },
        {
          name: "은호",
          position: ["리드 래퍼", "보컬"],
          birthYear: 2004,
          personality: ["Kind", "Chic", "Cool"],
        },
        {
          name: "하민",
          position: ["리드 보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Bright", "Cute"],
        },
      ],
    },
    {
      name: "BABYMONSTER",
      gender: "female",
      agency: "YG 엔터테인먼트",
      members: [
        {
          name: "루카",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2002,
          personality: ["Charismatic", "Confident", "Cool"],
        },
        {
          name: "파리타",
          position: ["메인 보컬"],
          birthYear: 2005,
          personality: ["StrongVocal", "Warm", "Graceful"],
        },
        {
          name: "아사",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2006,
          personality: ["Powerful", "Energetic", "Creative"],
        },
        {
          name: "아현",
          position: ["메인 보컬", "리드 래퍼"],
          birthYear: 2007,
          personality: ["Bright", "Versatile", "Cheerful"],
        },
        {
          name: "라미(하람)",
          position: ["메인 보컬"],
          birthYear: 2007,
          personality: ["Elegant", "Calm", "Warm"],
        },
        {
          name: "치키타",
          position: ["리드 보컬", "막내"],
          birthYear: 2009,
          personality: ["Youngest", "Cute", "Energetic"],
        },
        {
          name: "로라",
          position: ["리드 보컬"],
          birthYear: 2008,
          personality: ["Sweet", "Bright", "Friendly"],
        },
      ],
    },
    {
      name: "ILLIT",
      gender: "female",
      agency: "빌리프랩 (하이브)",
      members: [
        {
          name: "유나",
          position: ["리더", "메인 보컬"],
          birthYear: 2004,
          personality: ["Leader", "Gentle", "Reliable"],
        },
        {
          name: "민주",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2004,
          personality: ["Confident", "Stylish", "Cool"],
        },
        {
          name: "모카",
          position: ["리드 보컬"],
          birthYear: 2004,
          personality: ["Calm", "Elegant", "Graceful"],
        },
        {
          name: "원희",
          position: ["메인 보컬", "센터"],
          birthYear: 2007,
          personality: ["Bright", "Charming", "Positive"],
        },
        {
          name: "이로하",
          position: ["리드 댄서", "서브 보컬", "막내"],
          birthYear: 2008,
          personality: ["Youngest", "Cute", "Energetic"],
        },
      ],
    },
    {
      name: "UNIS",
      gender: "female",
      agency: "F&F 엔터테인먼트 / 카카오 엔터테인먼트",
      members: [
        {
          name: "진현주",
          position: ["리더", "메인 보컬"],
          birthYear: 2002,
          personality: ["Leader", "StrongVocal", "Reliable"],
        },
        {
          name: "임윤서",
          position: ["리드 보컬"],
          birthYear: 2004,
          personality: ["Bright", "Friendly", "Warm"],
        },
        {
          name: "나나미",
          position: ["리드 댄서", "보컬"],
          birthYear: 2005,
          personality: ["Graceful", "Calm", "Kind"],
        },
        {
          name: "코토네",
          position: ["리드 래퍼", "보컬"],
          birthYear: 2006,
          personality: ["Cool", "Creative", "Energetic"],
        },
        {
          name: "엘리시아",
          position: ["메인 보컬"],
          birthYear: 2009,
          personality: ["Young", "StrongVocal", "Passionate"],
        },
        {
          name: "오예원",
          position: ["리드 래퍼", "서브 보컬"],
          birthYear: 2008,
          personality: ["Playful", "Bright", "Friendly"],
        },
        {
          name: "카밀라",
          position: ["메인 댄서", "보컬"],
          birthYear: 2006,
          personality: ["Performance", "Energetic", "Charming"],
        },
        {
          name: "임서원",
          position: ["서브 보컬", "막내"],
          birthYear: 2008,
          personality: ["Youngest", "Cute", "Positive"],
        },
      ],
    },
    {
      name: "TWS",
      gender: "male",
      agency: "플레디스 엔터테인먼트 (하이브)",
      members: [
        {
          name: "신유",
          position: ["리더", "리드 래퍼", "서브 보컬"],
          birthYear: 2003,
          personality: ["Leader", "Calm", "Reliable"],
        },
        {
          name: "도훈",
          position: ["메인 보컬"],
          birthYear: 2005,
          personality: ["Bright", "Warm", "Cheerful"],
        },
        {
          name: "영재",
          position: ["리드 보컬"],
          birthYear: 2005,
          personality: ["Gentle", "Positive", "Friendly"],
        },
        {
          name: "경민",
          position: ["메인 래퍼"],
          birthYear: 2004,
          personality: ["Confident", "Stylish", "Cool"],
        },
        {
          name: "한진",
          position: ["메인 댄서", "보컬"],
          birthYear: 2006,
          personality: ["DanceLine", "Energetic", "Fun"],
        },
        {
          name: "지훈",
          position: ["리드 댄서", "서브 보컬", "막내"],
          birthYear: 2007,
          personality: ["Youngest", "Cute", "Bright"],
        },
      ],
    },
    {
      name: "KATSEYE",
      gender: "female",
      agency: "하이브 × 게펜 레코즈",
      members: [
        {
          name: "라라 라자고팔",
          position: ["리더", "메인 보컬"],
          birthYear: 2005,
          personality: ["Leader", "Graceful", "Confident"],
        },
        {
          name: "소피아 라포르테자",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2002,
          personality: ["Cool", "Powerful", "Creative"],
        },
        {
          name: "다니엘라 아반지니",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 2004,
          personality: ["Charming", "Energetic", "Bright"],
        },
        {
          name: "마농 배너먼",
          position: ["리드 래퍼", "보컬"],
          birthYear: 2003,
          personality: ["Stylish", "Chic", "Confident"],
        },
        {
          name: "메건 스키엔지엘",
          position: ["리드 보컬"],
          birthYear: 2006,
          personality: ["SoftVoice", "Friendly", "Positive"],
        },
        {
          name: "정윤채",
          position: ["서브 보컬", "막내"],
          birthYear: 2007,
          personality: ["Youngest", "Cute", "Cheerful"],
        },
      ],
    },
    {
      name: "RESCENE",
      gender: "female",
      agency: "그레이트엠 엔터테인먼트",
      members: [
        {
          name: "원이",
          position: ["리더", "메인 댄서", "보컬"],
          birthYear: 2004,
          personality: ["Leader", "Bright", "Charming"],
        },
        {
          name: "리브",
          position: ["메인 보컬"],
          birthYear: 2005,
          personality: ["StrongVocal", "Graceful", "Kind"],
        },
        {
          name: "미나미",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 2005,
          personality: ["DanceLine", "Calm", "Cute"],
        },
        {
          name: "마유",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 2006,
          personality: ["Cool", "Creative", "Fun"],
        },
        {
          name: "유즈",
          position: ["리드 보컬", "막내"],
          birthYear: 2007,
          personality: ["Youngest", "Bright", "Playful"],
        },
      ],
    },
    {
      name: "ALL(H)OURS",
      gender: "male",
      agency: "이든 엔터테인먼트",
      members: [
        {
          name: "민규",
          position: ["리더", "메인 보컬"],
          birthYear: 2001,
          personality: ["Leader", "Reliable", "Warm"],
        },
        {
          name: "정민",
          position: ["메인 댄서", "리드 래퍼"],
          birthYear: 2003,
          personality: ["Energetic", "Performance", "Charming"],
        },
        {
          name: "현우",
          position: ["메인 래퍼", "보컬"],
          birthYear: 2003,
          personality: ["Cool", "Stylish", "Confident"],
        },
        {
          name: "윤민",
          position: ["리드 보컬", "서브 래퍼"],
          birthYear: 2003,
          personality: ["Gentle", "Friendly", "Bright"],
        },
        {
          name: "진성",
          position: ["메인 댄서", "서브 보컬"],
          birthYear: 2004,
          personality: ["DanceLine", "Fun", "Positive"],
        },
        {
          name: "시온",
          position: ["리드 보컬", "막내"],
          birthYear: 2005,
          personality: ["Youngest", "Cute", "Warm"],
        },
      ],
    },
    {
      name: "AMPERS&ONE",
      gender: "male",
      agency: "FNC 엔터테인먼트",
      members: [
        {
          name: "캠든",
          position: ["리더", "메인 래퍼"],
          birthYear: 2001,
          personality: ["Leader", "Confident", "Stylish"],
        },
        {
          name: "브라이언",
          position: ["메인 보컬"],
          birthYear: 2003,
          personality: ["Bright", "Gentle", "Warm"],
        },
        {
          name: "지호",
          position: ["리드 보컬"],
          birthYear: 2004,
          personality: ["Calm", "Charming", "Kind"],
        },
        {
          name: "승모",
          position: ["메인 댄서", "보컬"],
          birthYear: 2003,
          personality: ["Performance", "Energetic", "Friendly"],
        },
        {
          name: "카이렐",
          position: ["리드 래퍼"],
          birthYear: 2003,
          personality: ["Cool", "Creative", "Chic"],
        },
        {
          name: "상민",
          position: ["메인 보컬"],
          birthYear: 2004,
          personality: ["PowerVocal", "Bright", "Positive"],
        },
        {
          name: "경민",
          position: ["리드 래퍼", "막내"],
          birthYear: 2006,
          personality: ["Youngest", "Playful", "Energetic"],
        },
      ],
    },
    {
      name: "NOWADAYS",
      gender: "male",
      agency: "큐브 엔터테인먼트",
      members: [
        {
          name: "진혁",
          position: ["리더", "메인 보컬"],
          birthYear: 2004,
          personality: ["Leader", "Reliable", "Bright"],
        },
        {
          name: "우혁",
          position: ["메인 래퍼", "리드 댄서"],
          birthYear: 2004,
          personality: ["Cool", "Confident", "Dynamic"],
        },
        {
          name: "석민",
          position: ["리드 보컬"],
          birthYear: 2005,
          personality: ["Gentle", "Kind", "Bright"],
        },
        {
          name: "유진",
          position: ["메인 댄서", "보컬"],
          birthYear: 2005,
          personality: ["DanceLine", "Cheerful", "Friendly"],
        },
        {
          name: "현서",
          position: ["리드 래퍼", "막내"],
          birthYear: 2006,
          personality: ["Youngest", "Playful", "Cute"],
        },
      ],
    },
    {
      name: "EXO",
      gender: "male",
      agency: "SM 엔터테인먼트",
      members: [
        {
          name: "수호",
          position: ["리더", "리드 보컬"],
          birthYear: 1991,
          personality: ["Leader", "Gentle", "Responsible"],
        },
        {
          name: "시우민",
          position: ["리드 보컬", "리드 댄서"],
          birthYear: 1990,
          personality: ["Reliable", "Calm", "Bright"],
        },
        {
          name: "레이",
          position: ["메인 댄서", "보컬"],
          birthYear: 1991,
          personality: ["Artistic", "Graceful", "Kind"],
        },
        {
          name: "백현",
          position: ["메인 보컬"],
          birthYear: 1992,
          personality: ["Charismatic", "Cheerful", "VocalKing"],
        },
        {
          name: "첸",
          position: ["메인 보컬"],
          birthYear: 1992,
          personality: ["StrongVocal", "Sincere", "Warm"],
        },
        {
          name: "찬열",
          position: ["메인 래퍼", "보컬"],
          birthYear: 1992,
          personality: ["Energetic", "Creative", "Bright"],
        },
        {
          name: "디오",
          position: ["메인 보컬"],
          birthYear: 1993,
          personality: ["Calm", "Gentle", "Warm"],
        },
        {
          name: "카이",
          position: ["메인 댄서", "서브 래퍼", "비주얼", "센터"],
          birthYear: 1994,
          personality: ["PerformanceKing", "Charming", "Stylish"],
        },
        {
          name: "세훈",
          position: ["리드 댄서", "서브 래퍼", "비주얼", "막내"],
          birthYear: 1994,
          personality: ["Youngest", "Cool", "Chic"],
        },
      ],
    },
    {
      name: "Red Velvet",
      gender: "female",
      agency: "SM 엔터테인먼트",
      members: [
        {
          name: "아이린",
          position: ["리더", "메인 래퍼", "리드 댄서", "비주얼"],
          birthYear: 1991,
          personality: ["Leader", "Elegant", "Charismatic"],
        },
        {
          name: "슬기",
          position: ["메인 댄서", "리드 보컬"],
          birthYear: 1994,
          personality: ["Powerful", "Versatile", "Reliable"],
        },
        {
          name: "웬디",
          position: ["메인 보컬"],
          birthYear: 1994,
          personality: ["Warm", "StrongVocal", "Positive"],
        },
        {
          name: "조이",
          position: ["리드 래퍼", "서브 보컬"],
          birthYear: 1996,
          personality: ["Bright", "Charming", "Friendly"],
        },
        {
          name: "예리",
          position: ["서브 보컬", "서브 래퍼", "막내"],
          birthYear: 1999,
          personality: ["Youngest", "Playful", "Creative"],
        },
      ],
    },
    {
      name: "SEVENTEEN",
      gender: "male",
      agency: "플레디스 엔터테인먼트 (하이브)",
      members: [
        {
          name: "에스쿱스",
          position: ["리더", "힙합팀 리더", "메인 래퍼"],
          birthYear: 1995,
          personality: ["Leader", "Dependable", "Charismatic"],
        },
        {
          name: "정한",
          position: ["리드 보컬"],
          birthYear: 1995,
          personality: ["Playful", "Charming", "Kind"],
        },
        {
          name: "조슈아",
          position: ["리드 보컬"],
          birthYear: 1995,
          personality: ["Gentle", "Polite", "Warm"],
        },
        {
          name: "준",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 1996,
          personality: ["Graceful", "Calm", "Artistic"],
        },
        {
          name: "호시",
          position: ["퍼포먼스팀 리더", "메인 댄서", "리드 보컬"],
          birthYear: 1996,
          personality: ["Energetic", "Creative", "Leader"],
        },
        {
          name: "원우",
          position: ["리드 래퍼"],
          birthYear: 1996,
          personality: ["Calm", "Intellectual", "Cool"],
        },
        {
          name: "우지",
          position: ["보컬팀 리더", "리드 보컬", "프로듀서"],
          birthYear: 1996,
          personality: ["Producer", "Focused", "Genius"],
        },
        {
          name: "도겸",
          position: ["메인 보컬"],
          birthYear: 1997,
          personality: ["PowerVocal", "Bright", "Optimistic"],
        },
        {
          name: "민규",
          position: ["리드 래퍼", "비주얼"],
          birthYear: 1997,
          personality: ["Visual", "Charming", "Friendly"],
        },
        {
          name: "디에잇",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 1997,
          personality: ["Artistic", "Elegant", "Philosophical"],
        },
        {
          name: "승관",
          position: ["메인 보컬"],
          birthYear: 1998,
          personality: ["VocalKing", "Funny", "BrightEnergy"],
        },
        {
          name: "버논",
          position: ["메인 래퍼"],
          birthYear: 1998,
          personality: ["Cool", "Creative", "FreeSpirit"],
        },
        {
          name: "디노",
          position: ["메인 댄서", "서브 보컬", "막내"],
          birthYear: 1999,
          personality: ["Youngest", "Passionate", "Perfectionist"],
        },
      ],
    },
    {
      name: "TWICE",
      gender: "female",
      agency: "JYP 엔터테인먼트",
      members: [
        {
          name: "나연",
          position: ["리드 보컬", "센터"],
          birthYear: 1995,
          personality: ["Bright", "Friendly", "Energetic"],
        },
        {
          name: "정연",
          position: ["리드 보컬"],
          birthYear: 1996,
          personality: ["Calm", "Honest", "Reliable"],
        },
        {
          name: "모모",
          position: ["메인 댄서", "서브 보컬", "서브 래퍼"],
          birthYear: 1996,
          personality: ["PerformanceQueen", "Fun", "Kind"],
        },
        {
          name: "사나",
          position: ["서브 보컬"],
          birthYear: 1996,
          personality: ["Cute", "Friendly", "Positive"],
        },
        {
          name: "지효",
          position: ["리더", "메인 보컬"],
          birthYear: 1997,
          personality: ["Leader", "StrongVocal", "Reliable"],
        },
        {
          name: "미나",
          position: ["메인 댄서", "서브 보컬"],
          birthYear: 1997,
          personality: ["Elegant", "Calm", "Graceful"],
        },
        {
          name: "다현",
          position: ["리드 래퍼", "서브 보컬"],
          birthYear: 1998,
          personality: ["Funny", "Bright", "Confident"],
        },
        {
          name: "채영",
          position: ["메인 래퍼", "서브 보컬"],
          birthYear: 1999,
          personality: ["Creative", "Artistic", "Charming"],
        },
        {
          name: "쯔위",
          position: ["리드 댄서", "서브 보컬", "비주얼", "막내"],
          birthYear: 1999,
          personality: ["Youngest", "Elegant", "Gentle"],
        },
      ],
    },
    {
      name: "GFRIEND",
      gender: "female",
      agency: "쏘스뮤직",
      members: [
        {
          name: "소원",
          position: ["리더", "서브 보컬", "비주얼"],
          birthYear: 1995,
          personality: ["Leader", "Graceful", "Dependable"],
        },
        {
          name: "예린",
          position: ["리드 댄서", "서브 보컬"],
          birthYear: 1996,
          personality: ["Bright", "Playful", "Kind"],
        },
        {
          name: "은하",
          position: ["리드 보컬"],
          birthYear: 1997,
          personality: ["SoftVoice", "Cute", "Warm"],
        },
        {
          name: "유주",
          position: ["메인 보컬"],
          birthYear: 1997,
          personality: ["PowerVocal", "Passionate", "Sincere"],
        },
        {
          name: "신비",
          position: ["메인 댄서", "서브 보컬"],
          birthYear: 1998,
          personality: ["Cool", "Confident", "Focused"],
        },
        {
          name: "엄지",
          position: ["서브 보컬", "막내"],
          birthYear: 1998,
          personality: ["Youngest", "Bright", "Positive"],
        },
      ],
    },
    {
      name: "MAMAMOO",
      gender: "female",
      agency: "RBW 엔터테인먼트",
      members: [
        {
          name: "솔라",
          position: ["리더", "메인 보컬"],
          birthYear: 1991,
          personality: ["Leader", "Charismatic", "Passionate"],
        },
        {
          name: "문별",
          position: ["메인 래퍼", "메인 댄서"],
          birthYear: 1992,
          personality: ["Cool", "Confident", "Reliable"],
        },
        {
          name: "휘인",
          position: ["리드 보컬", "리드 댄서"],
          birthYear: 1995,
          personality: ["Artistic", "Charming", "Calm"],
        },
        {
          name: "화사",
          position: ["리드 래퍼", "서브 보컬", "막내"],
          birthYear: 1995,
          personality: ["Youngest", "Bold", "Charismatic"],
        },
      ],
    },
    {
      name: "iKON",
      gender: "male",
      agency: "YG 엔터테인먼트",
      members: [
        {
          name: "비아이",
          position: ["리더", "메인 래퍼"],
          birthYear: 1996,
          personality: ["Leader", "Creative", "ProducerMind"],
        },
        {
          name: "바비",
          position: ["메인 래퍼", "보컬"],
          birthYear: 1995,
          personality: ["Energetic", "Confident", "Charismatic"],
        },
        {
          name: "진환",
          position: ["메인 보컬", "리드 댄서"],
          birthYear: 1994,
          personality: ["Gentle", "Sexy", "Artistic"],
        },
        {
          name: "윤형",
          position: ["리드 보컬"],
          birthYear: 1995,
          personality: ["Kind", "Reliable", "Bright"],
        },
        {
          name: "동혁",
          position: ["메인 댄서", "보컬"],
          birthYear: 1997,
          personality: ["DanceLine", "Cheerful", "Positive"],
        },
        {
          name: "준회",
          position: ["메인 보컬"],
          birthYear: 1997,
          personality: ["PowerVocal", "Confident", "Stylish"],
        },
        {
          name: "찬우",
          position: ["서브 보컬", "막내"],
          birthYear: 1998,
          personality: ["Youngest", "Cute", "Playful"],
        },
      ],
    },
    {
      name: "WINNER",
      gender: "male",
      agency: "YG 엔터테인먼트",
      members: [
        {
          name: "진우",
          position: ["리드 보컬", "비주얼"],
          birthYear: 1991,
          personality: ["Visual", "Gentle", "Charming"],
        },
        {
          name: "승훈",
          position: ["메인 댄서", "래퍼"],
          birthYear: 1992,
          personality: ["Energetic", "Funny", "Creative"],
        },
        {
          name: "민호",
          position: ["메인 래퍼", "보컬"],
          birthYear: 1993,
          personality: ["Cool", "Charismatic", "Stylish"],
        },
        {
          name: "승윤",
          position: ["리더", "메인 보컬", "막내"],
          birthYear: 1994,
          personality: ["Leader", "Passionate", "Versatile"],
        },
      ],
    },
  ],
};

export type KpopGroup = (typeof kpopGroupsData.groups)[0];
export type KpopMember = KpopGroup["members"][0];
