export const kpopGroupsData = {
  groups: [
    {
      name: "BTS",
      agency: "빅히트 뮤직",
      members: [
        { name: "RM", position: ["리더", "메인 래퍼"] },
        { name: "진", position: ["서브 보컬", "비주얼"] },
        { name: "슈가", position: ["리드 래퍼"] },
        {
          name: "제이홉",
          position: ["메인 댄서", "서브 래퍼", "서브 보컬"],
        },
        { name: "지민", position: ["메인 댄서", "리드 보컬"] },
        { name: "뷔", position: ["리드 댄서", "서브 보컬", "비주얼"] },
        {
          name: "정국",
          position: ["메인 보컬", "리드 댄서", "서브 래퍼", "센터", "막내"],
        },
      ],
    },
    {
      name: "BLACKPINK",
      agency: "YG 엔터테인먼트",
      members: [
        { name: "지수", position: ["리드 보컬", "비주얼"] },
        { name: "제니", position: ["메인 래퍼", "리드 보컬"] },
        { name: "로제", position: ["메인 보컬", "리드 댄서"] },
        {
          name: "리사",
          position: ["메인 댄서", "리드 래퍼", "서브 보컬", "막내"],
        },
      ],
    },
    {
      name: "IVE",
      agency: "스타쉽 엔터테인먼트",
      members: [
        { name: "안유진", position: ["리더", "리드 보컬"] },
        { name: "가을", position: ["메인 래퍼", "서브 보컬"] },
        { name: "레이", position: ["래퍼", "서브 보컬"] },
        {
          name: "장원영",
          position: ["리드 댄서", "서브 보컬", "비주얼", "센터"],
        },
        { name: "리즈", position: ["메인 보컬"] },
        { name: "이서", position: ["서브 보컬", "막내"] },
      ],
    },
    {
      name: "aespa",
      agency: "SM 엔터테인먼트",
      members: [
        {
          name: "카리나",
          position: [
            "리더",
            "메인 댄서",
            "리드 래퍼",
            "서브 보컬",
            "비주얼",
            "센터",
          ],
        },
        { name: "지젤", position: ["메인 래퍼", "서브 보컬"] },
        { name: "윈터", position: ["리드 보컬", "리드 댄서", "비주얼"] },
        { name: "닝닝", position: ["메인 보컬", "막내"] },
      ],
    },
    {
      name: "(G)I-DLE",
      agency: "큐브 엔터테인먼트",
      members: [
        {
          name: "소연",
          position: ["리더", "메인 래퍼", "센터", "서브 보컬"],
        },
        { name: "민니", position: ["메인 보컬"] },
        { name: "우기", position: ["리드 댄서", "서브 보컬", "서브 래퍼"] },
        { name: "슈화", position: ["서브 보컬", "비주얼", "막내"] },
        { name: "미연", position: ["메인 보컬", "비주얼"] },
      ],
    },
    {
      name: "KIIRAS",
      agency: "LeanBranding",
      members: [
        { name: "링링", position: ["리더", "메인 래퍼", "서브 보컬"] },
        { name: "쿠루미", position: ["메인 보컬"] },
        { name: "하린", position: ["센터"] },
        { name: "카일리", position: ["메인 래퍼"] },
        { name: "도연", position: ["서브 보컬"] },
        { name: "로아", position: ["메인 보컬", "막내"] },
      ],
    },
    {
      name: "KickFlip",
      agency: "JYP 엔터테인먼트",
      members: [
        { name: "계훈", position: ["리더", "에이스"] },
        { name: "아마루", position: ["보컬", "랩"] },
        { name: "동화", position: ["댄스"] },
        { name: "주왕", position: ["보컬"] },
        { name: "민제", position: ["비주얼", "랩"] },
        { name: "케이주", position: ["댄스"] },
        { name: "동현", position: ["막내", "보컬"] },
      ],
    },
    {
      name: "Hearts2Hearts",
      agency: "SM 엔터테인먼트",
      members: [
        { name: "지우", position: ["리더", "메인 댄서", "비주얼"] },
        { name: "카르멘", position: ["메인 보컬"] },
        { name: "유하", position: ["리드 보컬", "리드 댄서"] },
        { name: "스텔라", position: ["리드 보컬"] },
        { name: "준", position: ["메인 댄서", "메인 래퍼", "서브 보컬"] },
        { name: "아나", position: ["리드 보컬", "비주얼"] },
        {
          name: "이안",
          position: ["센터", "비주얼", "리드 댄서", "서브 보컬"],
        },
        { name: "예온", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "ifeye",
      agency: "하이햇 엔터테인먼트",
      members: [
        { name: "카시아", position: ["리더", "래퍼"] },
        { name: "원화연", position: ["보컬", "센터"] },
        { name: "태린", position: ["메인 댄서"] },
        { name: "라희", position: ["올라운더"] },
        { name: "뮤", position: ["리드 보컬", "댄서"] },
        { name: "사샤", position: ["메인 보컬", "막내"] },
      ],
    },
    {
      name: "Stray Kids",
      agency: "JYP 엔터테인먼트",
      members: [
        {
          name: "방찬",
          position: ["리더", "프로듀서", "리드 보컬", "리드 댄서", "래퍼"],
        },
        { name: "리노", position: ["메인 댄서", "보컬", "서브 래퍼"] },
        { name: "창빈", position: ["메인 래퍼", "프로듀서", "보컬"] },
        {
          name: "현진",
          position: ["메인 댄서", "리드 래퍼", "서브 보컬", "비주얼"],
        },
        { name: "한", position: ["메인 래퍼", "리드 보컬", "프로듀서"] },
        { name: "필릭스", position: ["리드 댄서", "리드 래퍼", "서브 보컬"] },
        { name: "승민", position: ["메인 보컬"] },
        { name: "아이엔", position: ["보컬", "막내"] },
      ],
    },
    {
      name: "ATEEZ",
      agency: "KQ 엔터테인먼트",
      members: [
        { name: "홍중", position: ["리더", "래퍼", "작곡가"] },
        { name: "성화", position: ["보컬", "비주얼"] },
        { name: "윤호", position: ["메인 댄서", "보컬"] },
        { name: "여상", position: ["리드 댄서", "보컬", "비주얼"] },
        { name: "산", position: ["리드 보컬", "메인 댄서"] },
        { name: "민기", position: ["메인 래퍼", "퍼포머"] },
        { name: "우영", position: ["메인 댄서", "보컬", "퍼포머"] },
        { name: "종호", position: ["메인 보컬", "막내"] },
      ],
    },
    {
      name: "LOONA",
      agency: "블록베리 크리에이티브",
      members: [
        { name: "희진", position: ["댄서", "보컬", "비주얼"] },
        { name: "현진", position: ["댄서", "보컬"] },
        { name: "하슬", position: ["리더", "보컬"] },
        { name: "여진", position: ["보컬", "막내"] },
        { name: "비비", position: ["보컬"] },
        { name: "김립", position: ["메인 보컬", "댄서"] },
        { name: "진솔", position: ["메인 래퍼", "보컬"] },
        { name: "최리", position: ["래퍼", "댄서", "보컬"] },
        { name: "이브", position: ["보컬", "댄서"] },
        { name: "츄", position: ["메인 보컬", "그룹 얼굴"] },
        { name: "고원", position: ["래퍼", "댄서", "보컬"] },
        { name: "올리비아 혜", position: ["리드 래퍼", "댄서", "보컬"] },
      ],
    },
    {
      name: "THE BOYZ",
      agency: "IST 엔터테인먼트",
      members: [
        { name: "상연", position: ["리더", "메인 보컬"] },
        { name: "제이콥", position: ["리드 보컬"] },
        { name: "영훈", position: ["보컬", "비주얼"] },
        { name: "현재", position: ["리드 보컬", "리드 댄서", "비주얼"] },
        { name: "주연", position: ["메인 댄서", "보컬", "비주얼"] },
        { name: "케빈", position: ["메인 보컬"] },
        { name: "뉴", position: ["메인 보컬"] },
        { name: "큐", position: ["메인 댄서", "보컬"] },
        { name: "주학년", position: ["리드 댄서", "래퍼", "보컬"] },
        { name: "선우", position: ["메인 래퍼"] },
        { name: "에릭", position: ["리드 댄서", "리드 래퍼", "막내"] },
        { name: "활", position: ["리드 댄서", "보컬", "래퍼"] },
      ],
    },
    {
      name: "Golden Child",
      agency: "울림 엔터테인먼트",
      members: [
        { name: "대열", position: ["리더", "리드 댄서", "보컬"] },
        { name: "와이", position: ["메인 보컬", "리드 댄서"] },
        { name: "장준", position: ["메인 래퍼", "리드 댄서"] },
        { name: "태그", position: ["메인 래퍼", "보컬"] },
        { name: "승민", position: ["리드 보컬"] },
        { name: "재현", position: ["서브 보컬"] },
        { name: "동현", position: ["리드 댄서", "서브 보컬"] },
        { name: "주찬", position: ["메인 보컬"] },
        { name: "지범", position: ["리드 보컬"] },
        {
          name: "보민",
          position: ["리드 댄서", "서브 보컬", "막내", "비주얼"],
        },
      ],
    },
    {
      name: "Weki Meki",
      agency: "판타지오",
      members: [
        { name: "수연", position: ["리더", "메인 보컬"] },
        { name: "엘리", position: ["메인 보컬"] },
        { name: "유정", position: ["메인 래퍼", "메인 댄서", "리드 보컬"] },
        {
          name: "도연",
          position: ["리드 보컬", "리드 댄서", "비주얼", "센터"],
        },
        { name: "세이", position: ["리드 보컬"] },
        { name: "루아", position: ["메인 댄서", "서브 보컬", "래퍼"] },
        { name: "리나", position: ["리드 래퍼", "서브 보컬", "비주얼"] },
        { name: "루시", position: ["리드 래퍼", "리드 댄서", "막내"] },
      ],
    },
    {
      name: "ONF",
      agency: "WM 엔터테인먼트",
      members: [
        { name: "효진", position: ["리더(ON팀)", "메인 보컬"] },
        { name: "이션", position: ["리드 보컬"] },
        {
          name: "제이어스",
          position: ["리더(OFF팀)", "메인 댄서", "리드 보컬"],
        },
        { name: "와이엇", position: ["메인 래퍼", "리드 댄서"] },
        { name: "엠케이", position: ["메인 보컬"] },
        { name: "유", position: ["메인 댄서", "보컬", "막내"] },
        { name: "라운", position: ["리드 댄서", "보컬"] },
      ],
    },
    {
      name: "Dreamcatcher",
      agency: "드림캐쳐 컴퍼니",
      members: [
        { name: "지유", position: ["리더", "리드 댄서", "보컬", "비주얼"] },
        { name: "수아", position: ["메인 댄서", "리드 래퍼", "보컬"] },
        { name: "시연", position: ["메인 보컬"] },
        { name: "한동", position: ["보컬"] },
        { name: "유현", position: ["리드 보컬"] },
        { name: "다미", position: ["메인 래퍼", "리드 댄서"] },
        { name: "가현", position: ["리드 래퍼", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "fromis_9",
      agency: "오프더레코드 엔터테인먼트",
      members: [
        { name: "새롬", position: ["리더", "리드 댄서", "보컬", "비주얼"] },
        { name: "하영", position: ["리드 보컬", "리드 댄서"] },
        { name: "규리", position: ["리드 보컬", "비주얼"] },
        { name: "지원", position: ["메인 보컬"] },
        { name: "지선", position: ["리드 보컬", "리드 댄서", "센터"] },
        { name: "서연", position: ["메인 래퍼", "보컬", "메인 댄서"] },
        { name: "채영", position: ["메인 래퍼", "메인 댄서", "보컬"] },
        { name: "나경", position: ["리드 래퍼", "서브 보컬", "비주얼"] },
        { name: "지헌", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "NATURE",
      agency: "n.CH 엔터테인먼트",
      members: [
        { name: "루", position: ["리더", "메인 보컬"] },
        { name: "새봄", position: ["리드 래퍼", "보컬"] },
        { name: "오로라", position: ["메인 댄서", "보컬"] },
        { name: "채빈", position: ["메인 보컬"] },
        { name: "하루", position: ["메인 댄서", "보컬"] },
        { name: "로하", position: ["메인 보컬"] },
        { name: "유채", position: ["리드 댄서", "보컬", "비주얼"] },
        { name: "선샤인", position: ["리드 보컬"] },
        { name: "소희", position: ["보컬", "막내"] },
      ],
    },
    {
      name: "D-CRUNCH",
      agency: "올에스 컴퍼니",
      members: [
        { name: "오브이", position: ["리더", "메인 래퍼"] },
        { name: "현욱", position: ["메인 보컬"] },
        { name: "현호", position: ["리드 보컬"] },
        { name: "현오", position: ["보컬"] },
        { name: "현우", position: ["서브 보컬"] },
        { name: "민혁", position: ["서브 래퍼"] },
        { name: "찬영", position: ["메인 댄서", "리드 래퍼"] },
        { name: "정승", position: ["리드 보컬"] },
        { name: "딜런", position: ["래퍼", "막내"] },
      ],
    },
    {
      name: "DreamNote",
      agency: "아이미 코리아",
      members: [
        { name: "수민", position: ["리더", "리드 보컬"] },
        { name: "은조", position: ["리드 댄서", "보컬"] },
        { name: "라라", position: ["메인 보컬"] },
        { name: "미소", position: ["메인 댄서", "리드 래퍼"] },
        { name: "유이", position: ["리드 보컬", "비주얼"] },
        { name: "보니", position: ["리드 보컬"] },
        { name: "하빈", position: ["메인 댄서", "래퍼"] },
        { name: "한별", position: ["보컬", "막내"] },
      ],
    },
    {
      name: "IZ*ONE",
      agency: "오프더레코드 엔터테인먼트",
      members: [
        { name: "은비", position: ["리더", "리드 보컬", "리드 댄서"] },
        { name: "사쿠라", position: ["서브 보컬", "비주얼"] },
        { name: "혜원", position: ["리드 래퍼", "서브 보컬"] },
        { name: "유리", position: ["메인 보컬"] },
        { name: "예나", position: ["메인 래퍼", "리드 댄서", "보컬"] },
        { name: "채연", position: ["메인 댄서", "리드 보컬", "리드 래퍼"] },
        { name: "민주", position: ["리드 래퍼", "서브 보컬", "비주얼"] },
        { name: "나코", position: ["서브 보컬"] },
        { name: "히토미", position: ["서브 보컬", "리드 댄서"] },
        { name: "유진", position: ["리드 보컬", "리드 댄서", "센터"] },
        {
          name: "원영",
          position: ["리드 댄서", "서브 보컬", "비주얼", "막내"],
        },
        { name: "채원", position: ["리드 보컬"] },
      ],
    },
    {
      name: "PRISTIN",
      agency: "플레디스 엔터테인먼트",
      members: [
        { name: "나영", position: ["리더", "메인 래퍼", "리드 댄서"] },
        { name: "로아", position: ["리드 보컬"] },
        { name: "유하", position: ["리드 보컬"] },
        { name: "은우", position: ["리드 보컬"] },
        { name: "레나", position: ["메인 래퍼", "리드 보컬"] },
        { name: "결경", position: ["메인 댄서", "서브 보컬", "비주얼"] },
        { name: "예하나", position: ["메인 보컬"] },
        { name: "성연", position: ["메인 보컬", "메인 프로듀서"] },
        { name: "시연", position: ["리드 래퍼", "리드 보컬"] },
        { name: "카일라", position: ["리드 래퍼", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "ELRIS",
      agency: "휴니스 엔터테인먼트",
      members: [
        { name: "벨라", position: ["리더", "메인 래퍼", "서브 보컬"] },
        { name: "혜성", position: ["리드 보컬", "메인 댄서"] },
        { name: "유경", position: ["메인 댄서", "서브 보컬"] },
        { name: "소희", position: ["메인 보컬", "그룹 얼굴"] },
        { name: "가린", position: ["서브 보컬", "막내"] },
      ],
    },
    {
      name: "IN2IT",
      agency: "MMO 엔터테인먼트",
      members: [
        { name: "지안", position: ["리더", "메인 보컬"] },
        { name: "연태", position: ["메인 보컬"] },
        { name: "인표", position: ["리드 댄서", "보컬"] },
        { name: "아이작", position: ["보컬"] },
        { name: "인호", position: ["리드 보컬"] },
        { name: "현욱", position: ["메인 댄서", "래퍼"] },
        { name: "진섭", position: ["메인 보컬"] },
        { name: "성현", position: ["메인 댄서", "막내"] },
      ],
    },
    {
      name: "The Rose",
      agency: "J&Star 컴퍼니",
      members: [
        { name: "우성", position: ["리더", "메인 보컬", "일렉 기타"] },
        { name: "도준", position: ["키보드", "어쿠스틱 기타", "메인 보컬"] },
        { name: "하준", position: ["드러머", "서브 보컬", "래퍼"] },
        {
          name: "재형",
          position: ["베이시스트", "서브 보컬", "비주얼", "막내"],
        },
      ],
    },
    {
      name: "ITZY",
      agency: "JYP 엔터테인먼트",
      members: [
        {
          name: "예지",
          position: ["리더", "메인 댄서", "리드 보컬", "서브 래퍼"],
        },
        { name: "리아", position: ["메인 보컬"] },
        {
          name: "류진",
          position: ["메인 래퍼", "리드 댄서", "센터", "서브 보컬"],
        },
        { name: "채령", position: ["메인 댄서", "서브 보컬", "서브 래퍼"] },
        {
          name: "유나",
          position: ["리드 래퍼", "리드 댄서", "비주얼", "막내"],
        },
      ],
    },
    {
      name: "TXT (Tomorrow X Together)",
      agency: "빅히트 뮤직",
      members: [
        { name: "수빈", position: ["리더", "보컬", "래퍼"] },
        { name: "연준", position: ["래퍼", "댄서", "보컬"] },
        { name: "범규", position: ["보컬", "댄서", "래퍼", "센터", "비주얼"] },
        { name: "태현", position: ["메인 보컬", "댄서"] },
        { name: "휴닝카이", position: ["리드 보컬", "댄서", "막내"] },
      ],
    },
    {
      name: "TREASURE",
      agency: "YG 엔터테인먼트",
      members: [
        { name: "최현석", position: ["리더", "메인 래퍼", "메인 댄서"] },
        { name: "지훈", position: ["리더", "리드 보컬", "리드 댄서"] },
        { name: "요시", position: ["리드 래퍼", "보컬"] },
        { name: "준규", position: ["리드 보컬", "비주얼"] },
        { name: "마시호", position: ["리드 댄서", "리드 보컬", "비주얼"] },
        { name: "윤재혁", position: ["서브 보컬"] },
        { name: "아사히", position: ["리드 보컬", "비주얼"] },
        { name: "방예담", position: ["메인 보컬"] },
        { name: "도영", position: ["메인 댄서", "보컬"] },
        { name: "하루토", position: ["메인 래퍼", "비주얼"] },
        { name: "박정우", position: ["메인 보컬"] },
        { name: "소정환", position: ["리드 댄서", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "CRAVITY",
      agency: "스타쉽 엔터테인먼트",
      members: [
        { name: "세림", position: ["리더", "메인 래퍼", "비주얼"] },
        { name: "앨런", position: ["메인 댄서", "리드 래퍼"] },
        { name: "정모", position: ["리드 보컬", "비주얼"] },
        { name: "우빈", position: ["메인 보컬"] },
        { name: "원진", position: ["리드 보컬", "리드 댄서"] },
        { name: "민희", position: ["리드 보컬", "비주얼"] },
        { name: "형준", position: ["메인 댄서", "보컬"] },
        { name: "태영", position: ["리드 댄서", "보컬"] },
        { name: "성민", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "MCND",
      agency: "티오피미디어",
      members: [
        { name: "캐슬제이", position: ["리더", "메인 래퍼"] },
        { name: "빅", position: ["메인 댄서", "리드 래퍼"] },
        { name: "민재", position: ["메인 보컬"] },
        { name: "휘준", position: ["메인 보컬"] },
        { name: "윈", position: ["리드 래퍼", "막내"] },
      ],
    },
    {
      name: "cignature",
      agency: "J9 엔터테인먼트",
      members: [
        { name: "채솔", position: ["리더", "리드 댄서", "보컬"] },
        { name: "지원", position: ["리드 보컬", "리드 래퍼"] },
        { name: "셀린", position: ["리드 보컬"] },
        { name: "클로이", position: ["메인 래퍼", "서브 보컬"] },
        { name: "세미", position: ["메인 댄서", "리드 보컬"] },
        { name: "도희", position: ["리드 보컬"] },
        { name: "벨", position: ["메인 보컬"] },
      ],
    },
    {
      name: "STAYC",
      agency: "하이업 엔터테인먼트",
      members: [
        { name: "수민", position: ["리더", "리드 보컬", "리드 댄서", "래퍼"] },
        { name: "시은", position: ["메인 보컬"] },
        { name: "아이사", position: ["리드 보컬"] },
        { name: "세은", position: ["서브 보컬"] },
        { name: "윤", position: ["리드 보컬", "리드 댄서"] },
        { name: "재이", position: ["메인 래퍼", "리드 보컬", "막내"] },
      ],
    },
    {
      name: "Weeekly",
      agency: "IST 엔터테인먼트",
      members: [
        { name: "수진", position: ["리더", "메인 댄서", "리드 보컬"] },
        { name: "지윤", position: ["메인 래퍼", "리드 보컬"] },
        { name: "먼데이", position: ["메인 보컬", "메인 댄서"] },
        { name: "소은", position: ["메인 댄서", "리드 래퍼", "보컬"] },
        { name: "재희", position: ["리드 보컬", "서브 래퍼"] },
        { name: "지한", position: ["리드 보컬", "비주얼", "그룹 얼굴"] },
        { name: "조아", position: ["리드 래퍼", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "ENHYPEN",
      agency: "빌리프랩 (하이브 × CJ ENM)",
      members: [
        { name: "정원", position: ["리더", "리드 댄서", "리드 보컬", "래퍼"] },
        { name: "희승", position: ["메인 보컬", "센터", "댄서"] },
        { name: "제이", position: ["메인 래퍼", "리드 댄서", "보컬"] },
        { name: "제이크", position: ["리드 래퍼", "보컬"] },
        { name: "성훈", position: ["리드 댄서", "보컬", "비주얼"] },
        { name: "선우", position: ["리드 보컬"] },
        { name: "니키", position: ["메인 댄서", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "E'LAST",
      agency: "이 엔터테인먼트",
      members: [
        { name: "라노", position: ["리더", "메인 래퍼", "메인 댄서"] },
        { name: "최인", position: ["메인 보컬"] },
        { name: "승엽", position: ["리드 보컬"] },
        { name: "백결", position: ["보컬", "비주얼"] },
        { name: "로민", position: ["리드 보컬", "비주얼"] },
        { name: "원혁", position: ["메인 래퍼", "보컬"] },
        { name: "원준", position: ["리드 래퍼", "보컬"] },
        { name: "예준", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "DRIPPIN",
      agency: "울림 엔터테인먼트",
      members: [
        { name: "윤성", position: ["리더", "메인 댄서", "보컬"] },
        { name: "협", position: ["메인 보컬"] },
        { name: "창욱", position: ["리드 보컬"] },
        { name: "동윤", position: ["메인 래퍼", "리드 댄서"] },
        { name: "민서", position: ["리드 보컬", "막내"] },
        { name: "준호", position: ["리드 댄서", "보컬", "비주얼"] },
        { name: "알렉스", position: ["래퍼", "보컬", "막내(2019~2022 활동)"] },
      ],
    },
    {
      name: "Secret Number",
      agency: "바인 엔터테인먼트",
      members: [
        { name: "레아", position: ["리더", "리드 보컬"] },
        { name: "디타", position: ["메인 댄서", "서브 보컬"] },
        { name: "진희", position: ["메인 래퍼", "리드 댄서", "서브 보컬"] },
        { name: "민지", position: ["메인 보컬"] },
        { name: "수담", position: ["리드 댄서", "서브 보컬", "비주얼"] },
        { name: "주", position: ["서브 래퍼", "서브 보컬"] },
      ],
    },
    {
      name: "BDC (Boys Da Capo)",
      agency: "브랜뉴뮤직",
      members: [
        { name: "성준", position: ["리더", "메인 래퍼", "서브 보컬"] },
        { name: "시훈", position: ["메인 댄서", "리드 보컬"] },
        { name: "정환", position: ["메인 보컬", "막내"] },
      ],
    },
    {
      name: "BOTOPASS",
      agency: "WKS ENE / JMG",
      members: [
        { name: "미희", position: ["리더", "메인 보컬"] },
        { name: "서윤", position: ["리드 보컬"] },
        { name: "리아", position: ["리드 래퍼", "보컬"] },
        { name: "시연", position: ["메인 댄서", "리드 보컬"] },
        { name: "하린", position: ["리드 댄서", "보컬"] },
        { name: "지원", position: ["메인 래퍼", "서브 보컬"] },
        { name: "시안", position: ["메인 보컬"] },
        { name: "아윤", position: ["보컬", "막내"] },
      ],
    },
    {
      name: "LE SSERAFIM",
      agency: "쏘스뮤직 / 하이브",
      members: [
        { name: "채원", position: ["리더", "보컬", "댄서"] },
        { name: "사쿠라", position: ["서브 보컬", "서브 래퍼", "비주얼"] },
        { name: "윤진", position: ["메인 보컬"] },
        { name: "카즈하", position: ["리드 래퍼", "리드 댄서", "서브 보컬"] },
        { name: "은채", position: ["리드 댄서", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "NewJeans",
      agency: "어도어 (하이브)",
      members: [
        { name: "민지", position: ["리더", "리드 래퍼", "서브 보컬"] },
        { name: "하니", position: ["메인 보컬"] },
        { name: "다니엘", position: ["리드 보컬", "리드 댄서"] },
        { name: "해린", position: ["메인 보컬", "서브 래퍼"] },
        { name: "혜인", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "Kep1er",
      agency: "웨이크원 엔터테인먼트 / 스윙 엔터테인먼트",
      members: [
        {
          name: "유진",
          position: ["리더", "리드 댄서", "서브 보컬", "서브 래퍼"],
        },
        { name: "마시로", position: ["공동 리더", "서브 보컬", "서브 래퍼"] },
        { name: "샤오팅", position: ["메인 댄서", "서브 보컬"] },
        { name: "채현", position: ["메인 보컬"] },
        { name: "다연", position: ["메인 댄서", "서브 보컬", "서브 래퍼"] },
        { name: "히카루", position: ["메인 래퍼", "리드 댄서"] },
        { name: "휴닝 바히에", position: ["서브 보컬", "서브 래퍼"] },
        { name: "영은", position: ["메인 댄서", "리드 래퍼", "서브 보컬"] },
        { name: "예서", position: ["리드 댄서", "리드 보컬", "막내"] },
      ],
    },
    {
      name: "NMIXX",
      agency: "JYP 엔터테인먼트",
      members: [
        { name: "해원", position: ["리더", "메인 보컬"] },
        { name: "릴리", position: ["메인 보컬"] },
        { name: "설윤", position: ["보컬", "비주얼"] },
        { name: "배이", position: ["리드 댄서", "서브 보컬"] },
        { name: "지우", position: ["메인 래퍼", "메인 댄서", "서브 보컬"] },
        { name: "규진", position: ["메인 댄서", "리드 래퍼", "막내"] },
      ],
    },
    {
      name: "XG",
      agency: "XGALX",
      members: [
        { name: "주린", position: ["리더", "메인 래퍼", "리드 댄서"] },
        { name: "치사", position: ["메인 보컬"] },
        { name: "하비", position: ["리드 래퍼", "리드 댄서"] },
        { name: "히나타", position: ["리드 댄서", "서브 보컬"] },
        { name: "주리아", position: ["메인 보컬"] },
        { name: "마야", position: ["메인 래퍼", "리드 보컬"] },
        { name: "코코나", position: ["메인 래퍼", "막내"] },
      ],
    },
    {
      name: "TNX",
      agency: "피네이션",
      members: [
        { name: "태훈", position: ["리더", "메인 보컬"] },
        { name: "경준", position: ["리드 래퍼"] },
        { name: "현수", position: ["리드 댄서", "서브 보컬"] },
        { name: "준혁", position: ["메인 래퍼", "리드 댄서"] },
        { name: "휘", position: ["메인 보컬", "서브 래퍼"] },
        { name: "성준", position: ["리드 래퍼", "막내"] },
      ],
    },
    {
      name: "BAE173",
      agency: "포켓돌 스튜디오",
      members: [
        { name: "제이민", position: ["리더", "메인 래퍼"] },
        { name: "한결", position: ["메인 댄서", "리드 보컬"] },
        { name: "유준", position: ["리드 래퍼", "보컬"] },
        { name: "무진", position: ["메인 댄서", "서브 래퍼"] },
        { name: "준서", position: ["리드 댄서", "서브 보컬"] },
        { name: "영서", position: ["메인 보컬"] },
        { name: "도하", position: ["메인 래퍼", "서브 보컬"] },
        { name: "빛", position: ["서브 래퍼", "보컬"] },
        { name: "도현", position: ["메인 래퍼", "막내"] },
      ],
    },
    {
      name: "BOYNEXTDOOR",
      agency: "코즈 엔터테인먼트 (하이브)",
      members: [
        { name: "재현", position: ["리더", "보컬", "래퍼"] },
        { name: "성호", position: ["메인 보컬"] },
        { name: "리우", position: ["메인 댄서", "보컬"] },
        { name: "태산", position: ["메인 래퍼", "보컬"] },
        { name: "리한", position: ["서브 보컬", "비주얼"] },
        { name: "운학", position: ["리드 래퍼", "막내"] },
      ],
    },
    {
      name: "ZEROBASEONE (ZB1)",
      agency: "웨이크원 엔터테인먼트",
      members: [
        { name: "성한빈", position: ["리더", "메인 댄서", "리드 보컬"] },
        { name: "김지웅", position: ["리드 보컬", "비주얼"] },
        { name: "장하오", position: ["센터", "메인 보컬"] },
        { name: "석매튜", position: ["리드 보컬"] },
        { name: "김태래", position: ["메인 보컬"] },
        { name: "리키", position: ["리드 댄서", "서브 보컬"] },
        { name: "김규빈", position: ["메인 댄서", "서브 보컬", "비주얼"] },
        { name: "박건욱", position: ["메인 래퍼", "리드 댄서"] },
        { name: "한유진", position: ["리드 댄서", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "RIIZE",
      agency: "SM 엔터테인먼트",
      members: [
        { name: "쇼타로", position: ["메인 댄서", "리드 래퍼"] },
        { name: "은석", position: ["리드 래퍼", "비주얼"] },
        { name: "성찬", position: ["메인 래퍼", "리드 댄서"] },
        { name: "원빈", position: ["리드 래퍼", "리드 보컬"] },
        { name: "소희", position: ["메인 보컬"] },
        { name: "앤톤", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "KISS OF LIFE",
      agency: "에스투 엔터테인먼트",
      members: [
        { name: "줄리", position: ["리더", "메인 래퍼"] },
        { name: "나띠", position: ["메인 댄서", "리드 보컬"] },
        { name: "벨", position: ["메인 보컬"] },
        { name: "하늘", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "PLAVE",
      agency: "브이래스트",
      members: [
        { name: "예준", position: ["리더", "메인 보컬"] },
        { name: "노아", position: ["메인 래퍼", "서브 보컬"] },
        { name: "밤비", position: ["메인 댄서", "보컬"] },
        { name: "은호", position: ["리드 래퍼", "보컬"] },
        { name: "하민", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "BABYMONSTER",
      agency: "YG 엔터테인먼트",
      members: [
        { name: "루카", position: ["메인 래퍼", "리드 댄서"] },
        { name: "파리타", position: ["메인 보컬"] },
        { name: "아사", position: ["메인 래퍼", "리드 댄서"] },
        { name: "아현", position: ["메인 보컬", "리드 래퍼"] },
        { name: "라미(하람)", position: ["메인 보컬"] },
        { name: "치키타", position: ["리드 보컬", "막내"] },
        { name: "로라", position: ["리드 보컬"] },
      ],
    },
    {
      name: "ILLIT",
      agency: "빌리프랩 (하이브)",
      members: [
        { name: "유나", position: ["리더", "메인 보컬"] },
        { name: "민주", position: ["메인 래퍼", "리드 댄서"] },
        { name: "모카", position: ["리드 보컬"] },
        { name: "원희", position: ["메인 보컬", "센터"] },
        { name: "이로하", position: ["리드 댄서", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "UNIS",
      agency: "F&F 엔터테인먼트 / 카카오 엔터테인먼트",
      members: [
        { name: "진현주", position: ["리더", "메인 보컬"] },
        { name: "임윤서", position: ["리드 보컬"] },
        { name: "나나미", position: ["리드 댄서", "보컬"] },
        { name: "코토네", position: ["리드 래퍼", "보컬"] },
        { name: "엘리시아", position: ["메인 보컬"] },
        { name: "오예원", position: ["리드 래퍼", "서브 보컬"] },
        { name: "카밀라", position: ["메인 댄서", "보컬"] },
        { name: "임서원", position: ["서브 보컬", "막내"] },
      ],
    },
    {
      name: "TWS",
      agency: "플레디스 엔터테인먼트 (하이브)",
      members: [
        { name: "신유", position: ["리더", "리드 래퍼", "서브 보컬"] },
        { name: "도훈", position: ["메인 보컬"] },
        { name: "영재", position: ["리드 보컬"] },
        { name: "경민", position: ["메인 래퍼"] },
        { name: "한진", position: ["메인 댄서", "보컬"] },
        { name: "지훈", position: ["리드 댄서", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "KATSEYE",
      agency: "하이브 × 게펜 레코즈",
      members: [
        { name: "라라 라자고팔", position: ["리더", "메인 보컬"] },
        { name: "소피아 라포르테자", position: ["메인 래퍼", "리드 댄서"] },
        { name: "다니엘라 아반지니", position: ["메인 댄서", "리드 보컬"] },
        { name: "마농 배너먼", position: ["리드 래퍼", "보컬"] },
        { name: "메건 스키엔지엘", position: ["리드 보컬"] },
        { name: "정윤채", position: ["서브 보컬", "막내"] },
      ],
    },
    {
      name: "RESCENE",
      agency: "그레이트엠 엔터테인먼트",
      members: [
        { name: "원이", position: ["리더", "메인 댄서", "보컬"] },
        { name: "리브", position: ["메인 보컬"] },
        { name: "미나미", position: ["리드 댄서", "서브 보컬"] },
        { name: "마유", position: ["메인 래퍼", "서브 보컬"] },
        { name: "유즈", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "ALL(H)OURS",
      agency: "이든 엔터테인먼트",
      members: [
        { name: "민규", position: ["리더", "메인 보컬"] },
        { name: "정민", position: ["메인 댄서", "리드 래퍼"] },
        { name: "현우", position: ["메인 래퍼", "보컬"] },
        { name: "윤민", position: ["리드 보컬", "서브 래퍼"] },
        { name: "진성", position: ["메인 댄서", "서브 보컬"] },
        { name: "시온", position: ["리드 보컬", "막내"] },
      ],
    },
    {
      name: "AMPERS&ONE",
      agency: "FNC 엔터테인먼트",
      members: [
        { name: "캠든", position: ["리더", "메인 래퍼"] },
        { name: "브라이언", position: ["메인 보컬"] },
        { name: "지호", position: ["리드 보컬"] },
        { name: "승모", position: ["메인 댄서", "보컬"] },
        { name: "카이렐", position: ["리드 래퍼"] },
        { name: "상민", position: ["메인 보컬"] },
        { name: "경민", position: ["리드 래퍼", "막내"] },
      ],
    },
    {
      name: "NOWADAYS",
      agency: "큐브 엔터테인먼트",
      members: [
        { name: "진혁", position: ["리더", "메인 보컬"] },
        { name: "우혁", position: ["메인 래퍼", "리드 댄서"] },
        { name: "석민", position: ["리드 보컬"] },
        { name: "유진", position: ["메인 댄서", "보컬"] },
        { name: "현서", position: ["리드 래퍼", "막내"] },
      ],
    },
    {
      name: "EXO",
      agency: "SM 엔터테인먼트",
      members: [
        { name: "수호", position: ["리더", "리드 보컬"] },
        { name: "시우민", position: ["리드 보컬", "리드 댄서"] },
        { name: "레이", position: ["메인 댄서", "보컬"] },
        { name: "백현", position: ["메인 보컬"] },
        { name: "첸", position: ["메인 보컬"] },
        { name: "찬열", position: ["메인 래퍼", "보컬"] },
        { name: "디오", position: ["메인 보컬"] },
        {
          name: "카이",
          position: ["메인 댄서", "서브 래퍼", "비주얼", "센터"],
        },
        {
          name: "세훈",
          position: ["리드 댄서", "서브 래퍼", "비주얼", "막내"],
        },
      ],
    },
    {
      name: "Red Velvet",
      agency: "SM 엔터테인먼트",
      members: [
        {
          name: "아이린",
          position: ["리더", "메인 래퍼", "리드 댄서", "비주얼"],
        },
        { name: "슬기", position: ["메인 댄서", "리드 보컬"] },
        { name: "웬디", position: ["메인 보컬"] },
        { name: "조이", position: ["리드 래퍼", "서브 보컬"] },
        { name: "예리", position: ["서브 보컬", "서브 래퍼", "막내"] },
      ],
    },
    {
      name: "SEVENTEEN",
      agency: "플레디스 엔터테인먼트 (하이브)",
      members: [
        { name: "에스쿱스", position: ["리더", "힙합팀 리더", "메인 래퍼"] },
        { name: "정한", position: ["리드 보컬"] },
        { name: "조슈아", position: ["리드 보컬"] },
        { name: "준", position: ["리드 댄서", "서브 보컬"] },
        {
          name: "호시",
          position: ["퍼포먼스팀 리더", "메인 댄서", "리드 보컬"],
        },
        { name: "원우", position: ["리드 래퍼"] },
        { name: "우지", position: ["보컬팀 리더", "리드 보컬", "프로듀서"] },
        { name: "도겸", position: ["메인 보컬"] },
        { name: "민규", position: ["리드 래퍼", "비주얼"] },
        { name: "디에잇", position: ["리드 댄서", "서브 보컬"] },
        { name: "승관", position: ["메인 보컬"] },
        { name: "버논", position: ["메인 래퍼"] },
        { name: "디노", position: ["메인 댄서", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "TWICE",
      agency: "JYP 엔터테인먼트",
      members: [
        { name: "나연", position: ["리드 보컬", "센터"] },
        { name: "정연", position: ["리드 보컬"] },
        { name: "모모", position: ["메인 댄서", "서브 보컬", "서브 래퍼"] },
        { name: "사나", position: ["서브 보컬"] },
        { name: "지효", position: ["리더", "메인 보컬"] },
        { name: "미나", position: ["메인 댄서", "서브 보컬"] },
        { name: "다현", position: ["리드 래퍼", "서브 보컬"] },
        { name: "채영", position: ["메인 래퍼", "서브 보컬"] },
        {
          name: "쯔위",
          position: ["리드 댄서", "서브 보컬", "비주얼", "막내"],
        },
      ],
    },
    {
      name: "GFRIEND",
      agency: "쏘스뮤직",
      members: [
        { name: "소원", position: ["리더", "서브 보컬", "비주얼"] },
        { name: "예린", position: ["리드 댄서", "서브 보컬"] },
        { name: "은하", position: ["리드 보컬"] },
        { name: "유주", position: ["메인 보컬"] },
        { name: "신비", position: ["메인 댄서", "서브 보컬"] },
        { name: "엄지", position: ["서브 보컬", "막내"] },
      ],
    },
    {
      name: "MAMAMOO",
      agency: "RBW 엔터테인먼트",
      members: [
        { name: "솔라", position: ["리더", "메인 보컬"] },
        { name: "문별", position: ["메인 래퍼", "메인 댄서"] },
        { name: "휘인", position: ["리드 보컬", "리드 댄서"] },
        { name: "화사", position: ["리드 래퍼", "서브 보컬", "막내"] },
      ],
    },
    {
      name: "iKON",
      agency: "YG 엔터테인먼트",
      members: [
        { name: "비아이", position: ["리더", "메인 래퍼"] },
        { name: "바비", position: ["메인 래퍼", "보컬"] },
        { name: "진환", position: ["메인 보컬", "리드 댄서"] },
        { name: "윤형", position: ["리드 보컬"] },
        { name: "동혁", position: ["메인 댄서", "보컬"] },
        { name: "준회", position: ["메인 보컬"] },
        { name: "찬우", position: ["서브 보컬", "막내"] },
      ],
    },
    {
      name: "WINNER",
      agency: "YG 엔터테인먼트",
      members: [
        { name: "진우", position: ["리드 보컬", "비주얼"] },
        { name: "후니", position: ["메인 댄서", "래퍼"] },
        { name: "민호", position: ["메인 래퍼", "보컬"] },
        { name: "승윤", position: ["리더", "메인 보컬", "막내"] },
      ],
    },
  ],
};

export type KpopGroup = (typeof kpopGroupsData.groups)[0];
export type KpopMember = KpopGroup["members"][0];
